"""Build work/akademija-namaza.en.html from work/akademija-namaza.bs.html.
Run from project root:  python3 tools/tr/akademija-namaza_build.py && python3 tools/skel.py build akademija-namaza
The 158-question bank is translated through the map M (one entry per unique Bosnian string, so the same
Bosnian text always gets the same English and the section names match the `sections` array)."""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
G = 'akademija-namaza'
src = open(os.path.join(ROOT, 'work', G + '.bs.html'), encoding='utf-8').read()

SECTIONS = {
    "Sabah-Namaz": "Fajr Salah",
    "Podne-Namaz": "Dhuhr Salah",
    "Ikindija-Namaz": "Asr Salah",
    "Akšam-Namaz": "Maghrib Salah",
    "Jacija-Namaz": "Isha Salah",
    "Vitr-Namaz": "Witr Salah",
    "Pokreti I Učenje": "Movements and Recitation",
    "Tesbih I Dova": "Tasbih and Dua",
}

M = {
# ---- Fajr
"Koliko rekata ima sabahski sunnet?": "How many rak’ahs (units of prayer) does the Fajr Sunnah have?",
"Koliko rekata ima sabahski farz?": "How many rak’ahs does the Fajr fard (obligatory prayer) have?",
"Koliko ukupno rekata imaju sabahski sunnet i farz?": "How many rak’ahs do the Fajr Sunnah and fard have altogether?",
"Šta se prvo klanja kod sabah-namaza?": "What is prayed first at Fajr?",
"Farz": "Fard",
"Vitr": "Witr",
"Sunnet": "Sunnah",
"Nafila": "Nafl (voluntary prayer)",
"Šta klanjamo nakon dva rekata sabahskog sunneta?": "What do we pray after the two rak’ahs of the Fajr Sunnah?",
"Dva rekata farza": "Two rak’ahs of fard",
"Četiri rekata farza": "Four rak’ahs of fard",
"Još dva sunneta": "Two more Sunnah rak’ahs",
"Šta učimo na početku prvog rekata sabahskog sunneta?": "What do we recite at the start of the first rak’ah of the Fajr Sunnah?",
"Ettehijjatu": "At-Tahiyyat",
"Subhaneke": "Subhanaka",
"Kunut-dovu": "The Qunut dua",
"Salavate": "Salawat",
"Šta slijedi nakon Subhaneke na prvom rekatu?": "What comes after Subhanaka in the first rak’ah?",
"Euzu": "A’udhu billah",
"Selam": "Salam",
"Kunut-dova": "Qunut dua",
"Šta slijedi nakon Euze?": "What comes after A’udhu billah?",
"Salavati": "Salawat",
"Bismilla": "Bismillah",
"Rukū": "Ruku’",
"Šta učimo nakon Bismille na prvom rekatu?": "What do we recite after Bismillah in the first rak’ah?",
"Fatihu": "Al-Fatiha",
"Šta učimo nakon Fatihe na prvom rekatu?": "What do we recite after Al-Fatiha in the first rak’ah?",
"Suru": "A surah",
"Šta učimo na početku drugog rekata?": "What do we recite at the start of the second rak’ah?",
"Bismillu": "Bismillah",
"Šta učimo nakon Fatihe na drugom rekatu?": "What do we recite after Al-Fatiha in the second rak’ah?",
"Koliko rukūa ima prvi rekat sabahskog namaza?": "How many Ruku’ (bowings) are in the first rak’ah of Fajr?",
"Koliko sedždi činimo na prvom rekatu?": "How many Sajdahs (prostrations) do we make in the first rak’ah?",
"Šta slijedi nakon druge sedžde prvog rekata?": "What comes after the second Sajdah of the first rak’ah?",
"Predajemo selam": "We give salam",
"Ustajemo na drugi rekat": "We stand up for the second rak’ah",
"Učimo Kunut-dovu": "We recite the Qunut dua",
"Završavamo namaz": "We finish the Salah",
"Nakon kojeg rekata sabahskog sunneta sjedimo na posljednjem sjedenju?": "After which rak’ah of the Fajr Sunnah do we sit for the final sitting?",
"Prvog": "The first",
"Drugog": "The second",
"Trećeg": "The third",
"Četvrtog": "The fourth",
"Nakon kojeg rekata sabahskog farza je posljednje sjedenje?": "After which rak’ah of the Fajr fard is the final sitting?",
"Šta učimo na posljednjem sjedenju?": "What do we recite in the final sitting?",
"Samo Fatihu": "Only Al-Fatiha",
"Ettehijjatu, salavate i dovu": "At-Tahiyyat, Salawat and a dua",
"Subhaneke i Euzu": "Subhanaka and A’udhu billah",
"Čime završavamo dva rekata sabahskog sunneta?": "How do we end the two rak’ahs of the Fajr Sunnah?",
"Tekbirom": "With a Takbir",
"Selamom": "With salam",
"Fatihom": "With Al-Fatiha",
"Rukūom": "With Ruku’",
"Koji je pravilan redoslijed sabah-namaza?": "What is the correct order of Fajr?",
"2 farza → 2 sunneta": "2 fard → 2 Sunnah",
"4 sunneta → 2 farza": "4 Sunnah → 2 fard",
"2 sunneta → 2 farza": "2 Sunnah → 2 fard",
"3 farza → 2 sunneta": "3 fard → 2 Sunnah",
# ---- Dhuhr
"Koliko rekata ima prvi sunnet podne-namaza?": "How many rak’ahs does the first Sunnah of Dhuhr have?",
"Koliko rekata ima podnevski farz?": "How many rak’ahs does the Dhuhr fard have?",
"Koliko rekata ima posljednji sunnet podne-namaza?": "How many rak’ahs does the last Sunnah of Dhuhr have?",
"Koji je pravilan redoslijed podne-namaza?": "What is the correct order of Dhuhr?",
"4 sunneta → 4 farza → 2 sunneta": "4 Sunnah → 4 fard → 2 Sunnah",
"4 farza → 4 sunneta → 2 sunneta": "4 fard → 4 Sunnah → 2 Sunnah",
"2 sunneta → 4 farza → 4 sunneta": "2 Sunnah → 4 fard → 4 Sunnah",
"4 sunneta → 2 farza → 4 sunneta": "4 Sunnah → 2 fard → 4 Sunnah",
"Koliko ukupno rekata ima ovaj redovni slijed podne-namaza?": "How many rak’ahs are there altogether in this regular order of Dhuhr?",
"Šta učimo na prvom rekatu prvog sunneta?": "What do we recite in the first rak’ah of the first Sunnah?",
"Subhaneke → Euzu → Bismilla → Fatiha → sura": "Subhanaka → A’udhu billah → Bismillah → Al-Fatiha → a surah",
"Bismilla → Fatiha": "Bismillah → Al-Fatiha",
"Šta učimo na drugom rekatu prvog sunneta?": "What do we recite in the second rak’ah of the first Sunnah?",
"Bismilla → Fatiha → sura": "Bismillah → Al-Fatiha → a surah",
"Subhaneke → Fatiha": "Subhanaka → Al-Fatiha",
"Šta učimo na trećem rekatu podnevskog sunneta?": "What do we recite in the third rak’ah of the Dhuhr Sunnah?",
"Šta učimo na četvrtom rekatu podnevskog sunneta?": "What do we recite in the fourth rak’ah of the Dhuhr Sunnah?",
"Samo suru": "Only a surah",
"Šta učimo na prvom sjedenju četverorekatnog sunneta?": "What do we recite in the first sitting of a four-rak’ah Sunnah?",
"Nakon prvog sjedenja podnevskog sunneta ustajemo na:": "After the first sitting of the Dhuhr Sunnah we stand up for:",
"Drugi rekat": "The second rak’ah",
"Treći rekat": "The third rak’ah",
"Četvrti rekat": "The fourth rak’ah",
"Novi namaz": "A new Salah",
"Šta učimo na prvom rekatu podnevskog farza?": "What do we recite in the first rak’ah of the Dhuhr fard?",
"Fatiha i sura": "Al-Fatiha and a surah",
"Šta učimo na drugom rekatu podnevskog farza?": "What do we recite in the second rak’ah of the Dhuhr fard?",
"Samo Subhaneke": "Only Subhanaka",
"Šta učimo na trećem rekatu podnevskog farza?": "What do we recite in the third rak’ah of the Dhuhr fard?",
"Bismilla i Fatiha": "Bismillah and Al-Fatiha",
"Subhaneke i sura": "Subhanaka and a surah",
"Uči li se dodatna sura nakon Fatihe na trećem rekatu farza?": "Is an extra surah recited after Al-Fatiha in the third rak’ah of the fard?",
"Da": "Yes",
"Samo petkom": "Only on Fridays",
"Ne": "No",
"Samo u džematu": "Only in congregation (jama’ah)",
"Šta učimo na četvrtom rekatu podnevskog farza?": "What do we recite in the fourth rak’ah of the Dhuhr fard?",
"Nakon kojeg rekata farza je prvo sjedenje?": "After which rak’ah of the fard is the first sitting?",
"Nakon kojeg rekata farza je posljednje sjedenje?": "After which rak’ah of the fard is the final sitting?",
"Šta klanjamo poslije četiri rekata podnevskog farza?": "What do we pray after the four rak’ahs of the Dhuhr fard?",
"2 rekata sunneta": "2 rak’ahs of Sunnah",
"4 rekata farza": "4 rak’ahs of fard",
"Sabahski sunnet": "The Fajr Sunnah",
"Koliko rekata ima završni podnevski sunnet?": "How many rak’ahs does the closing Dhuhr Sunnah have?",
# ---- Asr
"Koliko rekata ima ikindijski sunnet?": "How many rak’ahs does the Asr Sunnah have?",
"Koliko rekata ima ikindijski farz?": "How many rak’ahs does the Asr fard have?",
"Šta prvo klanjamo kod ikindije?": "What do we pray first at Asr?",
"Nafilu poslije farza": "A nafl prayer after the fard",
"Šta klanjamo poslije ikindijskog sunneta?": "What do we pray after the Asr Sunnah?",
"Akšam": "Maghrib",
"Koliko ukupno rekata imaju navedeni ikindijski sunnet i farz?": "How many rak’ahs do this Asr Sunnah and fard have altogether?",
"Šta učimo na prvom rekatu ikindijskog sunneta?": "What do we recite in the first rak’ah of the Asr Sunnah?",
"Šta učimo na drugom rekatu sunneta?": "What do we recite in the second rak’ah of the Sunnah?",
"Subhaneke → selam": "Subhanaka → salam",
"Šta učimo na prvom sjedenju ikindijskog sunneta?": "What do we recite in the first sitting of the Asr Sunnah?",
"Čime započinjemo učenje na trećem rekatu ikindijskog sunneta?": "What do we start reciting with in the third rak’ah of the Asr Sunnah?",
"Kunut-dovom": "With the Qunut dua",
"Šta slijedi nakon Subhaneke na trećem rekatu?": "What comes after Subhanaka in the third rak’ah?",
"Šta učimo nakon Fatihe na trećem rekatu sunneta?": "What do we recite after Al-Fatiha in the third rak’ah of the Sunnah?",
"Šta učimo na četvrtom rekatu sunneta?": "What do we recite in the fourth rak’ah of the Sunnah?",
"Subhaneke → Euzu": "Subhanaka → A’udhu billah",
"Na kojim rekatima ikindijskog farza učimo Fatihu i suru?": "In which rak’ahs of the Asr fard do we recite Al-Fatiha and a surah?",
"Samo na četvrtom": "Only in the fourth",
"Na prvom i drugom": "In the first and second",
"Na trećem i četvrtom": "In the third and fourth",
"Samo na trećem": "Only in the third",
"Šta učimo na trećem rekatu ikindijskog farza?": "What do we recite in the third rak’ah of the Asr fard?",
"Fatiha → sura": "Al-Fatiha → a surah",
"Subhaneke → sura": "Subhanaka → a surah",
"Šta učimo na četvrtom rekatu farza?": "What do we recite in the fourth rak’ah of the fard?",
"Nakon kojeg rekata ikindijskog farza prvi put sjedimo?": "After which rak’ah of the Asr fard do we sit for the first time?",
"Šta učimo na tom prvom sjedenju?": "What do we recite in that first sitting?",
"Čime završavamo ikindijski farz?": "How do we end the Asr fard?",
"Početnim tekbirom": "With the opening Takbir",
# ---- Maghrib
"Koliko rekata ima akšamski farz?": "How many rak’ahs does the Maghrib fard have?",
"Koliko rekata ima akšamski sunnet poslije farza?": "How many rak’ahs does the Maghrib Sunnah after the fard have?",
"Šta prvo klanjamo kod akšama?": "What do we pray first at Maghrib?",
"Nafilu": "A nafl prayer",
"Šta klanjamo nakon akšamskog farza?": "What do we pray after the Maghrib fard?",
"Dva rekata sunneta": "Two rak’ahs of Sunnah",
"Sabah": "Fajr",
"Koliko rekata zajedno imaju akšamski farz i sunnet?": "How many rak’ahs do the Maghrib fard and Sunnah have together?",
"Šta učimo na prvom rekatu akšamskog farza kada klanjamo sami?": "What do we recite in the first rak’ah of the Maghrib fard when we pray alone?",
"Šta učimo na drugom rekatu akšamskog farza kada klanjamo sami?": "What do we recite in the second rak’ah of the Maghrib fard when we pray alone?",
"Fatihu i suru": "Al-Fatiha and a surah",
"Nakon kojeg rekata akšamskog farza je prvo sjedenje?": "After which rak’ah of the Maghrib fard is the first sitting?",
"Nema sjedenja": "There is no sitting",
"Šta učimo na prvom sjedenju?": "What do we recite in the first sitting?",
"Šta činimo nakon prvog sjedenja akšamskog farza?": "What do we do after the first sitting of the Maghrib fard?",
"Ustajemo na treći rekat": "We stand up for the third rak’ah",
"Učimo tesbih": "We say the tasbih",
"Šta učimo na trećem rekatu akšamskog farza?": "What do we recite in the third rak’ah of the Maghrib fard?",
"Učimo li dodatnu suru nakon Fatihe na trećem rekatu farza?": "Do we recite an extra surah after Al-Fatiha in the third rak’ah of the fard?",
"Nakon kojeg rekata je posljednje sjedenje akšamskog farza?": "After which rak’ah is the final sitting of the Maghrib fard?",
"Čime završavamo akšamski farz?": "How do we end the Maghrib fard?",
"Sedždom": "With a Sajdah",
"Koliko rekata klanjamo poslije akšamskog farza kao redovni sunnet?": "How many rak’ahs do we pray after the Maghrib fard as the regular Sunnah?",
"Šta učimo na prvom rekatu akšamskog sunneta?": "What do we recite in the first rak’ah of the Maghrib Sunnah?",
"Šta učimo na drugom rekatu akšamskog sunneta?": "What do we recite in the second rak’ah of the Maghrib Sunnah?",
"Koliko sjedenja ima trorekatni akšamski farz?": "How many sittings does the three-rak’ah Maghrib fard have?",
"Jedno": "One",
"Dva": "Two",
"Tri": "Three",
"Nijedno": "None",
"Koji je pravilan redoslijed?": "What is the correct order?",
"2 sunneta → 3 farza": "2 Sunnah → 3 fard",
"4 farza → 2 sunneta": "4 fard → 2 Sunnah",
"3 sunneta → 2 farza": "3 Sunnah → 2 fard",
# ---- Isha
"Koliko rekata ima sunnet prije jacijskog farza?": "How many rak’ahs does the Sunnah before the Isha fard have?",
"Koliko rekata ima jacijski farz?": "How many rak’ahs does the Isha fard have?",
"Koliko rekata ima sunnet poslije jacijskog farza?": "How many rak’ahs does the Sunnah after the Isha fard have?",
"Šta prvo klanjamo u redovnom slijedu jacije?": "What do we pray first in the regular order of Isha?",
"Četiri rekata sunneta": "Four rak’ahs of Sunnah",
"Šta slijedi nakon četiri rekata sunneta prije farza?": "What comes after the four rak’ahs of Sunnah before the fard?",
"Tesbih": "Tasbih",
"Šta slijedi nakon jacijskog farza?": "What comes after the Isha fard?",
"Podnevski farz": "The Dhuhr fard",
"Bajram": "Eid",
"Koji namaz se potom klanja?": "Which Salah is prayed after that?",
"Podne": "Dhuhr",
"Ikindija": "Asr",
"Kako počinje prvi rekat jacijskog sunneta?": "How does the first rak’ah of the Isha Sunnah begin?",
"Subhaneke → Euzu → Bismilla": "Subhanaka → A’udhu billah → Bismillah",
"Samo Fatiha": "Only Al-Fatiha",
"Šta učimo nakon Fatihe na prvom rekatu sunneta?": "What do we recite after Al-Fatiha in the first rak’ah of the Sunnah?",
"Šta učimo na prvom sjedenju jacijskog sunneta?": "What do we recite in the first sitting of the Isha Sunnah?",
"Samo salavate": "Only Salawat",
"Kako započinjemo učenje na trećem rekatu jacijskog sunneta prema pravilima koja učimo?": "How do we start reciting in the third rak’ah of the Isha Sunnah, following the rules we are learning?",
"Samo Fatihom": "With Al-Fatiha only",
"Na kojim rekatima jacijskog farza učimo Fatihu i suru kada klanjamo sami?": "In which rak’ahs of the Isha fard do we recite Al-Fatiha and a surah when we pray alone?",
"Na 1. i 2.": "In the 1st and 2nd",
"Na 2. i 3.": "In the 2nd and 3rd",
"Na 3. i 4.": "In the 3rd and 4th",
"Samo na 4.": "Only in the 4th",
"Šta učimo na trećem rekatu farza?": "What do we recite in the third rak’ah of the fard?",
"Ettehijjatu stojeći": "At-Tahiyyat while standing",
"Čime završavamo jacijski farz?": "How do we end the Isha fard?",
"Koji namaz je povezan s vremenom nakon jacije i prije izlaska zore?": "Which Salah belongs to the time after Isha and before dawn?",
# ---- Witr
"Koliko rekata ima vitr-namaz prema hanefijskom mezhebu?": "How many rak’ahs does the Witr Salah have in the Hanafi madhhab (school)?",
"Kakav je vitr-namaz prema hanefijskom mezhebu?": "What kind of prayer is Witr in the Hanafi madhhab?",
"Vadžib": "Wajib",
"Samo nafila": "Only nafl",
"Džuma": "Jumu’ah",
"Kada se klanja vitr?": "When is Witr prayed?",
"Nakon jacije": "After Isha",
"Nakon podne": "After Dhuhr",
"Prije sabahskog sunneta kao dio sabaha": "Before the Fajr Sunnah, as part of Fajr",
"Nakon ikindije kao dio ikindije": "After Asr, as part of Asr",
"Šta učimo na prvom rekatu vitra?": "What do we recite in the first rak’ah of Witr?",
"Šta učimo na drugom rekatu prije rukūa?": "What do we recite in the second rak’ah before Ruku’?",
"Nakon kojeg rekata prvi put sjedimo u vitr-namazu?": "After which rak’ah do we sit for the first time in Witr?",
"Šta učimo na prvom sjedenju vitra?": "What do we recite in the first sitting of Witr?",
"Na koji rekat ustajemo poslije prvog sjedenja?": "Which rak’ah do we stand up for after the first sitting?",
"Drugi": "The second",
"Treći": "The third",
"Četvrti": "The fourth",
"Peti": "The fifth",
"Čime počinjemo učenje na trećem rekatu vitra?": "What do we start reciting with in the third rak’ah of Witr?",
"Bismillom": "With Bismillah",
"Salavatima": "With Salawat",
"Šta učimo nakon Bismille na trećem rekatu?": "What do we recite after Bismillah in the third rak’ah?",
"Šta učimo nakon Fatihe na trećem rekatu?": "What do we recite after Al-Fatiha in the third rak’ah?",
"Odmah selam": "Salam straight away",
"Šta činimo nakon sure na trećem rekatu?": "What do we do after the surah in the third rak’ah?",
"Izgovaramo tekbir": "We say a Takbir",
"Sjedamo": "We sit down",
"Šta učimo poslije tog tekbira?": "What do we recite after that Takbir?",
"Na kojem rekatu se uči Kunut-dova?": "In which rak’ah is the Qunut dua recited?",
"Prvom": "The first",
"Drugom": "The second",
"Trećem": "The third",
"Na svakom": "In every rak’ah",
"Šta slijedi nakon Kunut-dove?": "What comes after the Qunut dua?",
"Novo učenje Fatihe": "Reciting Al-Fatiha again",
"Prvo sjedenje": "The first sitting",
"Koliko sedždi činimo na trećem rekatu?": "How many Sajdahs do we make in the third rak’ah?",
"Jednu": "One",
"Dvije": "Two",
"Četiri": "Four",
"Šta slijedi nakon druge sedžde trećeg rekata?": "What comes after the second Sajdah of the third rak’ah?",
"Posljednje sjedenje": "The final sitting",
"Ponovno Kunut-dova": "The Qunut dua again",
"Šta učimo na posljednjem sjedenju vitra?": "What do we recite in the final sitting of Witr?",
"Ettehijjatu → salavati → dova": "At-Tahiyyat → Salawat → dua",
"Čime završavamo vitr-namaz?": "How do we end the Witr Salah?",
"Koji je pravilan redoslijed na 3. rekatu vitra?": "What is the correct order in the 3rd rak’ah of Witr?",
"Bismilla → Fatiha → sura → tekbir → Kunut-dova → rukū": "Bismillah → Al-Fatiha → a surah → Takbir → Qunut dua → Ruku’",
"Bismilla → Kunut-dova → Fatiha → selam": "Bismillah → Qunut dua → Al-Fatiha → salam",
"Fatiha → rukū → Kunut-dova → sura": "Al-Fatiha → Ruku’ → Qunut dua → a surah",
"Ettehijjatu → Fatiha → Kunut-dova": "At-Tahiyyat → Al-Fatiha → Qunut dua",
# ---- Movements and recitation
"Kako se zove stajanje u namazu?": "What is standing in Salah called?",
"Kijam": "Qiyam",
"Sedžda": "Sajdah",
"Ka'de": "Qa’dah",
"Kako se zove pregibanje u namazu?": "What is bowing in Salah called?",
"Kako se zove spuštanje čela na tlo?": "What is putting your forehead on the ground called?",
"Kako se zove sjedenje u namazu?": "What is sitting in Salah called?",
"Kiraet": "Qira’ah",
"Šta izgovaramo ulazeći u namaz?": "What do we say when we begin the Salah?",
"Allahu ekber": "Allahu akbar",
"Esselamu alejkum": "As-salamu alaykum",
"Šta učimo na rukūu?": "What do we recite in Ruku’?",
"Subhane rabbijel-azim": "Subhana Rabbiyal-Azim",
"Subhane rabbijel-e'ala": "Subhana Rabbiyal-A’la",
"Šta učimo na sedždi?": "What do we recite in Sajdah?",
"Koliko rukūa ima jedan obični rekat?": "How many Ruku’ are in one normal rak’ah?",
"Koliko sedždi ima jedan rekat?": "How many Sajdahs are in one rak’ah?",
"Šta dolazi nakon učenja Kur'ana na kijamu?": "What comes after reciting the Qur’an in Qiyam?",
"Tesbih poslije namaza": "The tasbih after Salah",
"Šta činimo nakon rukūa?": "What do we do after Ruku’?",
"Ispravljamo se": "We stand up straight",
"Sjedimo na posljednjem sjedenju": "We sit for the final sitting",
"Šta dolazi nakon ispravljanja sa rukūa?": "What comes after standing up straight from Ruku’?",
"Novi rekat bez sedžde": "A new rak’ah without Sajdah",
"Šta se nalazi između prve i druge sedžde?": "What is between the first and second Sajdah?",
"Kratko sjedenje": "A short sitting",
"Šta slijedi nakon kratkog sjedenja između sedždi?": "What comes after the short sitting between the Sajdahs?",
"Druga sedžda": "The second Sajdah",
"Početni tekbir": "The opening Takbir",
"Gdje učimo Fatihu?": "Where do we recite Al-Fatiha?",
"Na kijamu": "In Qiyam (standing)",
"Na rukūu": "In Ruku’",
"Na sedždi": "In Sajdah",
"Poslije selama kao dio rekata": "After salam, as part of the rak’ah",
"Gdje učimo Ettehijjatu?": "Where do we recite At-Tahiyyat?",
"Na sjedenju": "In the sitting",
"Stojeći prije Fatihe": "Standing, before Al-Fatiha",
"Gdje učimo salavate u završnom dijelu namaza?": "Where do we recite the Salawat in the last part of Salah?",
"Na posljednjem sjedenju": "In the final sitting",
"Na prvoj sedždi": "In the first Sajdah",
"Na početku prvog rekata": "At the start of the first rak’ah",
"Čime završavamo namaz?": "How do we end the Salah?",
"Koji je pravilan dio redoslijeda jednog rekata?": "Which is a correct part of the order of one rak’ah?",
"Kijam → rukū → ispravljanje → sedžda": "Qiyam → Ruku’ → standing up straight → Sajdah",
"Sedžda → kijam → selam → rukū": "Sajdah → Qiyam → salam → Ruku’",
"Rukū → selam → Fatiha → sedžda": "Ruku’ → salam → Al-Fatiha → Sajdah",
"Sjedenje → selam → rukū → kijam": "Sitting → salam → Ruku’ → Qiyam",
"Šta činimo nakon druge sedžde prvog rekata dvorekatnog namaza?": "What do we do after the second Sajdah of the first rak’ah of a two-rak’ah Salah?",
"Učimo tesbih poslije namaza": "We say the tasbih after Salah",
# ---- Tasbih and dua
"Kada učimo tesbih poslije namaza?": "When do we say the tasbih after Salah?",
"Nakon završetka namaza": "After the Salah is finished",
"Umjesto Fatihe": "Instead of Al-Fatiha",
"Na rukūu umjesto propisanog zikra": "In Ruku’, instead of its proper dhikr",
"Prije početnog tekbira kao dio rekata": "Before the opening Takbir, as part of the rak’ah",
"Čime prvo završimo sam namaz prije zikra?": "How do we first end the Salah itself, before the dhikr?",
"Šta možemo učiti nakon završenog namaza?": "What can we recite after the Salah is finished?",
"Zikr i dovu": "Dhikr and dua",
"Novi ezan za isti namaz": "A new Adhan for the same Salah",
"Fatihu kao novi rekat": "Al-Fatiha as a new rak’ah",
"Ikamet za isti završeni namaz": "An Iqamah for the same finished Salah",
"Kojim riječima slavimo Allaha u tesbihu?": "With which words do we glorify Allah in the tasbih?",
"Subhanallah": "Subhanallah",
"Semi'allahu limen hamideh": "Sami’Allahu liman hamidah",
"Koje riječi znače zahvalu Allahu?": "Which words mean thanking Allah?",
"Elhamdulillah": "Alhamdulillah",
"Euzu billahi": "A’udhu billahi",
"Kojim riječima veličamo Allaha?": "With which words do we declare Allah’s greatness?",
"Rabbigfirli": "Rabbighfirli",
"Koliko puta se u uobičajenom tesbihu nakon namaza kaže Subhanallah?": "How many times do we say Subhanallah in the usual tasbih after Salah?",
"Koliko puta se kaže Elhamdulillah?": "How many times do we say Alhamdulillah?",
"Koliko puta se kaže Allahu ekber u tesbihu?": "How many times do we say Allahu akbar in the tasbih?",
"Šta znači „Subhanallah“ u osnovnom smislu?": "What does “Subhanallah” basically mean?",
"Slavljen neka je Allah": "Glory be to Allah",
"Molim oprost": "I ask for forgiveness",
"Mir vama": "Peace be upon you",
"Allah mi je dovoljan": "Allah is enough for me",
"Šta znači „Elhamdulillah“?": "What does “Alhamdulillah” mean?",
"Hvala Allahu": "All praise and thanks are for Allah",
"Allah je najveći": "Allah is the Greatest",
"Slavljen Allah": "Glory to Allah",
"Šta znači „Allahu ekber“?": "What does “Allahu akbar” mean?",
"Šta je dova?": "What is a dua?",
"Obraćanje i molba Allahu": "Talking to Allah and asking Him",
"Vrsta rukūa": "A kind of Ruku’",
"Naziv za prvi rekat": "A name for the first rak’ah",
"Naziv za abdest": "A name for Wudu (ablution)",
"Možemo li poslije namaza moliti Allaha za dobro?": "Can we ask Allah for good things after Salah?",
"Samo jednom godišnje": "Only once a year",
"Možemo li doviti za svoje roditelje?": "Can we make dua for our parents?",
"Samo poslije sabaha": "Only after Fajr",
"Samo u džamiji": "Only in the mosque (masjid)",
"Možemo li doviti za oprost grijeha?": "Can we make dua for our sins to be forgiven?",
"Samo na Bajram": "Only on Eid",
"Samo prije namaza": "Only before Salah",
"Možemo li u dovi moliti za znanje i uputu?": "Can we ask for knowledge and guidance in our dua?",
"Samo za znanje": "Only for knowledge",
"Samo za materijalne stvari": "Only for material things",
"Šta treba pratiti dovu?": "What should go together with a dua?",
"Iskreno obraćanje Allahu": "Turning to Allah sincerely",
"Igra i razgovor": "Playing and chatting",
"Namjerno ometanje drugih": "Disturbing others on purpose",
"Nepažnja kao cilj": "Not paying attention on purpose",
}

UI = [
    ('<title>Akademija namaza</title>', '<title>Salah Academy</title>'),
    ('<h1>AKADEMIJA NAMAZA</h1><div class="sub">Uči • Vježbaj • Osvoji nivoe</div><div class="sub"><b>Pripremio Abdo ef. Rekić</b></div>',
     '<h1>SALAH ACADEMY</h1><div class="sub">Learn • Practise • Win levels</div>'),
    ('<h2>🎓 Tvoj put kroz akademiju</h2><p>Akademija ima 8 nivoa. Za prolaz na sljedeći nivo potrebno je najmanje <b>70%</b> tačnih odgovora. Pitanja i ponuđeni odgovori se miješaju pri svakom pokušaju.</p>',
     '<h2>🎓 Your path through the Academy</h2><p>The Academy has 8 levels about Salah (prayer). To pass to the next level you need at least <b>70%</b> correct answers. The questions and answers are shuffled on every try.</p>'),
    ('>Nazad u Akademiju</button>', '>Back to the Academy</button>'),
    ('<div>NIVO ${i+1}</div>', '<div>LEVEL ${i+1}</div>'),
    ("'20 pitanja • otključano':'🔒 Zaključano'", "'20 questions • unlocked':'🔒 Locked'"),
    ('`Nivo ${current+1} • ${sections[current]}`', '`Level ${current+1} • ${sections[current]}`'),
    ('`Tačno: ${correct}`', '`Correct: ${correct}`'),
    ("'✅ Tačno!'", "'✅ Correct!'"),
    ("'❌ Nije tačno.'", "'❌ Not correct.'"),
    ("'🎉 Nivo položen!':'📚 Pokušaj ponovo'", "'🎉 Level passed!':'📚 Try again'"),
    ('`Osvojio/la si <b>', '`You got <b>'),
    ("'Otključan je sljedeći nivo!':'Završio/la si Akademiju namaza! 🏆'):'Za prolaz je potrebno najmanje 70%.'",
     "'The next level is unlocked!':'You finished the Salah Academy! 🏆'):'You need at least 70% to pass.'"),
]

out = src
for bs, en in UI:
    n = out.count(bs)
    assert n >= 1, bs
    out = out.replace(bs, en)

k = out.index('const Q=') + len('const Q=')
Q, end = json.JSONDecoder().raw_decode(out[k:])
assert len(Q) == 158
assert json.dumps(Q, ensure_ascii=False) == out[k:k + end]
def tr(t):
    if t.isdigit():
        return t
    en = M[t]
    assert '"' not in en and "'" not in en and '\\' not in en, en
    return en
new = []
for x in Q:
    y = {"section": SECTIONS[x["section"]], "q": tr(x["q"]), "options": [tr(o) for o in x["options"]], "answer": x["answer"]}
    assert list(y) == list(x)
    assert len(set(y["options"])) == len(y["options"]), y
    new.append(y)
out = out[:k] + json.dumps(new, ensure_ascii=False) + out[k + end:]

sk = out.index('const sections=') + len('const sections=')
secs, send = json.JSONDecoder().raw_decode(out[sk:])
assert json.dumps(secs, ensure_ascii=False) == out[sk:sk + send]
out = out[:sk] + json.dumps([SECTIONS[s] for s in secs], ensure_ascii=False) + out[sk + send:]

open(os.path.join(ROOT, 'work', G + '.en.html'), 'w', encoding='utf-8').write(out)
print('ok')
