T = [
    ('<title>Božiji kitabi</title>', '<title>Allah\'s Books</title>'),
    ('<h1>PRONAĐI RIJEČ – BOŽIJI KITABI</h1>', '<h1>WORD SEARCH – ALLAH\'S BOOKS (KUTUB)</h1>'),
    ('<div>Kitabi, poslanici i objava</div>', '<div>Books, messengers and revelation</div>'),
    ('Zadatak: <b', 'Task: <b'), ('Bodovi: <b', 'Points: <b'),
    ('Dodirni prvo slovo, pa posljednje slovo riječi.', 'Tap the first letter, then the last letter of the word.'),
    ('💡 Pomoć −2', '💡 Hint −2'), ('↻ Nova igra', '↻ New game'),
    ('Pripremio Abdo ef. Rekić', 'Prepared by Abdo ef. Rekić'),
    ('["KURAN","Allahova knjiga objavljena Muhammedu, a.s."]', '["QURAN","Allah\'s book revealed to Muhammad (SAW)."]'),
    ('["TEVRAT","Allahova knjiga objavljena Musau, a.s."]', '["TAWRAT","Allah\'s book revealed to Musa (AS) – the Torah."]'),
    ('["ZEBUR","Allahova knjiga objavljena Davudu, a.s."]', '["ZABUR","Allah\'s book revealed to Dawud (AS) – the Psalms."]'),
    ('["INDZIL","Allahova knjiga objavljena Isau, a.s."]', '["INJIL","Allah\'s book revealed to Isa (AS) – the Gospel."]'),
    ('["SUHUFI","Manji Allahovi kitabi nazivaju se ovako."]', '["SUHUF","This is the name for Allah\'s smaller books (scrolls)."]'),
    ('["MUHAMMED","Posljednji Allahov poslanik kojem je objavljen Kur\'an."]', '["MUHAMMAD","The last messenger of Allah, to whom the Quran was revealed."]'),
    ('["MUSA","Poslanik kojem je objavljen Tevrat."]', '["MUSA","The messenger to whom the Tawrat was revealed."]'),
    ('["DAVUD","Poslanik kojem je objavljen Zebur."]', '["DAWUD","The messenger to whom the Zabur was revealed."]'),
    ('["ISA","Poslanik kojem je objavljen Indžil."]', '["ISA","The messenger to whom the Injil was revealed."]'),
    ('["OBJAVA","Allahova poruka koju je dostavljao poslanicima."]', '["REVELATION","Allah\'s message that was delivered to the messengers (wahy)."]'),
    ('"Bravo! Završio/la si svih 10 zadataka."', '"Well done! You finished all 10 tasks."'),
    ('"Ukupno bodova: "', '"Total points: "'),
    ('"Sada dodirni posljednje slovo riječi."', '"Now tap the last letter of the word."'),
    ('"✓ Tačno! +10 bodova"', '"✓ Correct! +10 points"'),
    ('"Pokušaj ponovo. −3 boda"', '"Try again. −3 points"'),
    ('"Riječ ima "+A.length+" slova i počinje slovom „"+A.charAt(0)+"“."', '"The word has "+A.length+" letters and starts with “"+A.charAt(0)+"”."'),
]
