"""Build work/ilmihal-memori.en.html from work/ilmihal-memori.bs.html.
Run from project root:  python3 tools/tr/ilmihal-memori_build.py && python3 tools/skel.py build ilmihal-memori
The lessons array is rebuilt from M (one entry per unique Bosnian string, so repeats stay identical).
Qur'an transliteration + meaning from AlQuran.cloud (en.transliteration, en.sahih).
Surah lesson titles keep the prefix "Sura " because the code checks /^Sura / to open the ayah-ordering game."""
import json, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
G = 'ilmihal-memori'
src = open(os.path.join(ROOT, 'work', G + '.bs.html'), encoding='utf-8').read()

M = {
    # titles
    "Memori gusul": "Memory: Ghusl (full bath)",
    "Memori tejemum": "Memory: Tayammum (dry ablution)",
    "Namaski ruknovi": "Pillars of Salah (arkan)",
    "Pet dnevnih namaza": "The five daily prayers (Salah)",
    "Hidžretski mjeseci 1": "Hijri months 1",
    "Hidžretski mjeseci 2": "Hijri months 2",
    "Mubarek-dani": "Blessed days",
    "Islamski šarti": "Pillars of Islam",
    "Zikr poslije namaza": "Dhikr after Salah",
    "Sura El-Ihlas": "Sura Al-Ikhlas",
    "Sura El-Felek": "Sura Al-Falaq",
    "Sura En-Nas": "Sura An-Nas",
    "Sura El-Leheb": "Sura Al-Lahab (Al-Masad)",
    "Sura En-Nasr": "Sura An-Nasr",
    "Imanski šarti": "Pillars of Iman (faith)",
    "Allahu Rabbi": "Allahu Rabbi",
    "Subhaneke": "Subhanaka",
    "Sura El-Fatiha": "Sura Al-Fatiha",
    "Ezan": "Adhan (call to prayer)",
    "Dinski šarti – 33": "The 33 conditions of the religion (din)",
    "Salavati": "Salawat",
    "Dova poslije salavata": "Dua after the Salawat",
    "Ajetul-Kursijja": "Ayat al-Kursi",
    "Pripreme za namaz": "Getting ready for Salah",
    "Et-Tehijjatu": "At-Tahiyyat",
    "Ikamet": "Iqamah",
    "Namaska vremena": "Prayer times",
    "Hasbi Rabbi": "Hasbi Rabbi",
    "Sabah-namaz": "Fajr prayer",
    "Islamska pravila ponašanja": "Islamic manners",
    "Nova hidžretska godina": "Islamic (Hijri) New Year",
    "Prikladne riječi u raznim situacijama": "The right words for different moments",
    "Islamska pravila prilikom jela i pića": "Islamic manners for eating and drinking",
    # Ghusl
    "Gargara": "Gargling (gharghara)",
    "Isprati usta i grlo": "Rinse the mouth and throat",
    "Istinšak": "Istinshaq",
    "Nos dobro isprati": "Rinse the nose well",
    "Gasli vudžud": "Ghasl al-wujud",
    "Cijelo tijelo oprati da nigdje suho ne ostane": "Wash the whole body so that no spot stays dry",
    "Gusulski šarti": "Fard acts of Ghusl",
    "Tri obavezne radnje gusula": "The three required acts of Ghusl",
    "Prije gusula": "Before Ghusl",
    "Proučiti Euzubillu i Bismillu i zanijetiti": "Say A’udhu billah and Bismillah and make the intention (niyyah)",
    "Redoslijed pranja tijela": "Order of washing the body",
    "Glava, desna pa lijeva strana": "Head, then the right side, then the left side",
    # Tayammum
    "Tejemum": "Tayammum",
    "Simbolično čišćenje zemljom ili zemljinom tvari": "Symbolic cleansing with earth or something from the earth",
    "Početak tejemuma": "Starting Tayammum",
    "Zanijetiti i proučiti Euzubillu i Bismillu": "Make the intention and say A’udhu billah and Bismillah",
    "Prvi dodir zemlje": "First touch of the earth",
    "Potrati lice": "Wipe the face",
    "Drugi dodir zemlje": "Second touch of the earth",
    "Potrati desnu i lijevu ruku do iznad lakata": "Wipe the right and left arm up to above the elbows",
    "Nema vode": "No water",
    "Tejemum može zamijeniti abdest": "Tayammum can replace Wudu (ablution)",
    "Tejemumski šarti": "Fard acts of Tayammum",
    "Nijet, lice i ruke": "Intention, face and arms",
    # Pillars of Salah
    "Iftitahi-tekbir": "Takbir al-Iftitah",
    "Početni tekbir": "The opening takbir (Allahu akbar)",
    "Kijam": "Qiyam",
    "Stajanje u namazu": "Standing in Salah",
    "Kiraet": "Qira’ah",
    "Učenje Kur'ana u namazu": "Reciting the Qur’an in Salah",
    "Ruku'": "Ruku’",
    "Pregibanje u namazu": "Bowing in Salah",
    "Sedžda": "Sajdah",
    "Spuštanje lica na tlo": "Putting the face down on the ground",
    "Kadei-ehire": "Qa’dah al-akhirah",
    "Sjedenje na kraju namaza": "Sitting at the end of Salah",
    # Five daily prayers
    "Sabah": "Fajr",
    "Od zore do pred izlazak Sunca": "From dawn until just before sunrise",
    "Podne": "Dhuhr",
    "Kad Sunce odmakne sa sredine neba": "When the sun has moved past the middle of the sky",
    "Ikindija": "Asr",
    "Kad sunce nagne zspadu": "When the sun leans towards the west",
    "Akšam": "Maghrib",
    "Kad Sunce zađe": "When the sun sets",
    "Jacija": "Isha",
    "Kad potpuno nestane Sunčeve svjetlosti": "When the sunlight has completely disappeared",
    "Sabah, podne, ikindija, akšam i jacija": "Fajr, Dhuhr, Asr, Maghrib and Isha",
    # Hijri months
    "Muharrem": "Muharram",
    "1. mjesec": "1st month",
    "Safer": "Safar",
    "2. mjesec": "2nd month",
    "Rebiul-evvel": "Rabi’ al-Awwal",
    "3. mjesec": "3rd month",
    "Rebiul-ahir": "Rabi’ al-Akhir",
    "4. mjesec": "4th month",
    "Džumadel-ula": "Jumada al-Ula",
    "5. mjesec": "5th month",
    "Džumadel-uhra": "Jumada al-Akhirah",
    "6. mjesec": "6th month",
    "Redžeb": "Rajab",
    "7. mjesec": "7th month",
    "Ša'ban": "Sha’ban",
    "8. mjesec": "8th month",
    "Ramazan": "Ramadan",
    "9. mjesec": "9th month",
    "Ševval": "Shawwal",
    "10. mjesec": "10th month",
    "Zul-kade": "Dhul-Qa’dah",
    "11. mjesec": "11th month",
    "Zul-hidže": "Dhul-Hijjah",
    "12. mjesec": "12th month",
    # Blessed days
    "1. muharrem": "1 Muharram",
    "Mevlud": "Mawlid (the Prophet’s birthday)",
    "12. rebiul-evvel": "12 Rabi’ al-Awwal",
    "Ramazanski bajram": "Eid al-Fitr (Ramadan Eid)",
    "1, 2. i 3. ševval": "1, 2 and 3 Shawwal",
    "Kurban-bajram": "Eid al-Adha (Qurbani Eid)",
    "10, 11, 12. i 13. zul-hidže": "10, 11, 12 and 13 Dhul-Hijjah",
    # Pillars of Islam
    "Kelimei-šehadet": "Shahadah",
    "Svjedočenje vjere": "Declaring your faith",
    "Namaz": "Salah (prayer)",
    "Klanjati pet dnevnih namaza": "Praying the five daily prayers",
    "Ramazanski post": "Fasting in Ramadan (sawm)",
    "Postiti mjesec ramazan": "Fasting the month of Ramadan",
    "Zekat": "Zakah",
    "Davati propisani dio imovine": "Giving the required share of your wealth",
    "Hadž": "Hajj",
    "Hodočastiti Kabu ako smo u mogućnosti": "Pilgrimage to the Ka’bah if we are able",
    # Dhikr
    "Zikr": "Dhikr",
    "Sjećanje na Allaha i Njegovo spominjanje": "Remembering Allah and mentioning Him",
    "Poslije posljednjeg selama": "After the last salam",
    "Učimo zikr poslije namaza": "We say the dhikr after Salah",
    "Subhanallah": "Subhanallah",
    "Slava Allahu": "Glory be to Allah",
    "El-hamdu lillah": "Alhamdulillah",
    "Hvala Allahu": "All praise and thanks be to Allah",
    "Allahu ekber": "Allahu akbar",
    "Allah je najveći": "Allah is the Greatest",
    "Salavati, Ajetul-Kursija i tesbih": "Salawat, Ayat al-Kursi and tasbih",
    # Al-Ikhlas (112)
    "Kul huvallahu ehad": "Qul huwal laahu ahad",
    "Reci: On je Allah – Jedan!": "Say, “He is Allah, [who is] One,",
    "Allahus-samed": "Allah hus-samad",
    "Allah je utočište svakom!": "Allah, the Eternal Refuge.",
    "Lem jelid ve lem juled": "Lam yalid wa lam yoolad",
    "Nije rodio i rođen nije": "He neither begets nor is born,",
    "Ve lem jekun lehu kufuven ehad": "Wa lam yakul-lahu kufuwan ahad",
    "I niko Mu ravan nije": "Nor is there to Him any equivalent.”",
    # Al-Falaq (113)
    "Kul e'uzu birabbil-felek": "Qul a'uzoo bi rabbil-falaq",
    "Reci: Utječem se Gospodaru svitanja": "Say, “I seek refuge in the Lord of daybreak",
    "Min šerri ma halek": "Min sharri ma khalaq",
    "Od zla onoga što On stvara": "From the evil of that which He created",
    "Ve min šerri gasikin iza vekab": "Wa min sharri ghasiqin iza waqab",
    "I od zla mrkle noći kada razastre tmine": "And from the evil of darkness when it settles",
    "Ve min šerrin-neffasati fil-'ukad": "Wa min sharrin-naffaa-thaati fil 'uqad",
    "I od zla smutljivca kada smutnju sije": "And from the evil of the blowers in knots",
    "Ve min šerri hasidin iza hased": "Wa min sharri haasidin iza hasad",
    "I od zla zavidljivca kada zavist ne krije": "And from the evil of an envier when he envies.”",
    # An-Nas (114)
    "Kul e'uzu birabbin-nas": "Qul a'uzu birabbin naas",
    "Reci: Tražim zaštitu Gospodara ljudi": "Say, “I seek refuge in the Lord of mankind,",
    "Melikin-nas": "Malikin naas",
    "Vladara ljudi": "The Sovereign of mankind.",
    "Ilahin-nas": "Ilaahin naas",
    "Boga ljudi": "The God of mankind,",
    "Min šerril-vesvasil-hannas": "Min sharril waswaasil khannaas",
    "Od zla šejtana napasnika": "From the evil of the retreating whisperer –",
    "Ellezi juvesvisu fi sudurin-nas": "Al lazee yuwaswisu fee sudoorin naas",
    "Koji zle misli unosi u srca ljudi": "Who whispers [evil] into the breasts of mankind –",
    "Minel-džinneti ven-nas": "Minal jinnati wan naas",
    "Od džina i od ljudi": "From among the jinn and mankind.”",
    # Al-Masad (111)
    "Tebbet jeda ebi lehebin ve tebb": "Tabbat yadaa abee Lahabinw-wa tabb",
    "Neka propadne Ebu Leheb, i propao je!": "May the hands of Abu Lahab be ruined, and ruined is he.",
    "Ma agna 'anhu maluhu ve ma keseb": "Maa aghna 'anhu maaluhu wa ma kasab",
    "Neće mu koristiti njegovo blago niti ono što je stekao": "His wealth will not avail him or that which he gained.",
    "Sejasla naren zate leheb": "Sayaslaa naaran zaata lahab",
    "Ući će u vatru rasplamsalu": "He will [enter to] burn in a Fire of [blazing] flame",
    "Vemre'etuhu hammaletel-hatab": "Wamra-atuhu hammaalatal-hatab",
    "I žena njegova koja drvlje nosi": "And his wife [as well] – the carrier of firewood.",
    "Fi džidiha hablun min mesed": "Fee jeediha hablum mim-masad",
    "O vratu njenu bit će uže od ličine": "Around her neck is a rope of [twisted] fiber.",
    # An-Nasr (110)
    "Iza džae nasrullahi vel-feth": "Iza jaa-a nasrullahi walfath",
    "Kada Allahova pomoć i pobjeda dođu": "When the victory of Allah has come and the conquest,",
    "Ve re'ejten-nase jedhulune fi dinillahi efvadža": "Wa ra-aitan naasa yadkhuloona fee deenil laahi afwajah",
    "I vidiš ljude kako u skupinama u Allahovu vjeru ulaze": "And you see the people entering into the religion of Allah in multitudes,",
    "Fesebbih bihamdi rabbike vestagfirh": "Fasabbih bihamdi rabbika wastaghfir",
    "Veličaj Gospodara svoga hvaleći Ga i moli Ga da ti oprosti": "Then exalt [Him] with praise of your Lord and ask forgiveness of Him.",
    "Innehu kane tevvaba": "Innahu kaana tawwaaba",
    "On je uvijek pokajanje primao": "Indeed, He is ever Accepting of repentance.",
    # Pillars of Iman
    "Amentu billahi": "Amantu billahi",
    "Vjerujem u Allaha": "I believe in Allah",
    "Ve melaiketihi": "Wa mala’ikatihi",
    "Vjerujem u Allahove meleke": "I believe in Allah’s angels (mala’ika)",
    "Ve kutubihi": "Wa kutubihi",
    "Vjerujem u Allahove knjige": "I believe in Allah’s books",
    "Ve rusulihi": "Wa rusulihi",
    "Vjerujem u Allahove poslanike": "I believe in Allah’s messengers",
    "Vel-jevmil-ahiri": "Wal-yawmil-akhiri",
    "Vjerujem u Sudnji dan": "I believe in the Last Day (Day of Judgement)",
    "Ve bil-kaderi hajrihi ve šerrihi minallahi te'ala": "Wal-qadari khayrihi wa sharrihi minallahi ta’ala",
    "Vjerujem da sve što se događa biva Allahovom odredbom": "I believe that everything that happens is by Allah’s decree (qadar)",
    # Allahu Rabbi
    "Allah je moj Gospodar": "Allah is my Lord",
    "Muhammedun nebijji": "Muhammadun nabiyyi",
    "Muhammed je moj poslanik": "Muhammad is my prophet",
    "El-Islamu dini": "Al-Islamu dini",
    "Islam je moja vjera": "Islam is my religion",
    "El-Kur'anu kitabi": "Al-Qur’anu kitabi",
    "Kur'an je moja knjiga": "The Qur’an is my book",
    "El-Ka'betu kibleti": "Al-Ka’batu qiblati",
    "Kaba je moja kibla": "The Ka’bah is my qiblah",
    "El-mu'minune ihveti": "Al-mu’minuna ikhwati",
    "Vjernici su moja braća": "The believers are my brothers and sisters",
    # Subhanaka
    "Subhanekellahumme": "Subhanakallahumma",
    "Slava Tebi, Allahu": "Glory be to You, O Allah",
    "Ve bi hamdike": "Wa bihamdika",
    "Tebi pripada hvala": "All praise belongs to You",
    "Ve tebarekesmuke": "Wa tabarakasmuka",
    "Blagoslovljeno je Tvoje ime": "Blessed is Your name",
    "Ve te'ala džedduke": "Wa ta’ala jadduka",
    "Uzvišena je Tvoja veličina": "Exalted is Your majesty",
    "Ve la ilahe gajruke": "Wa la ilaha ghayruka",
    "Nema drugog boga osim Tebe": "There is no god but You",
    # Al-Fatiha (1)
    "Bismillahir-Rahmanir-Rahim": "Bismillaahir Rahmaanir Raheem",
    "U ime Allaha, Milostivog, Samilosnog": "In the name of Allah, the Entirely Merciful, the Especially Merciful.",
    "El-hamdu lillahi rabbil-'alemin": "Alhamdu lillaahi Rabbil 'aalameen",
    "Hvala Allahu, Gospodaru svjetova": "[All] praise is [due] to Allah, Lord of the worlds –",
    "Er-Rahmanir-Rahim": "Ar-Rahmaanir-Raheem",
    "Milostivom, Samilosnom": "The Entirely Merciful, the Especially Merciful,",
    "Maliki jevmid-din": "Maaliki Yawmid-Deen",
    "Vladaru Sudnjeg dana": "Sovereign of the Day of Recompense.",
    "Ijjake na'budu ve ijjake neste'in": "Iyyaaka na'budu wa iyyaaka nasta'een",
    "Samo Tebe obožavamo i samo od Tebe pomoć tražimo": "It is You we worship and You we ask for help.",
    "Ihdinas-siratal-mustekim": "Ihdinas-Siraatal-Mustaqeem",
    "Uputi nas na Pravi put": "Guide us to the straight path –",
    "Siratal-lezine en'amte alejhim gajril-magdubi alejhim ve led-dallin": "Siraatal-lazeena an'amta 'alaihim ghayril-maghdoobi 'alaihim wa lad-daaalleen",
    "Put onih kojima si milost Svoju darovao, a ne onih koji su protiv sebe srdžbu izazvali, niti onih koji su zalutali": "The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.",
    # Adhan
    "Ešhedu en la ilahe illellah": "Ashhadu an la ilaha illallah",
    "Svjedočim da nema drugog boga osim Allaha": "I bear witness that there is no god but Allah",
    "Ešhedu enne Muhammeden resulullah": "Ashhadu anna Muhammadan rasulullah",
    "Svjedočim da je Muhammed Allahov poslanik": "I bear witness that Muhammad is the Messenger of Allah",
    "Hajje ales-salah": "Hayya ’alas-salah",
    "Dođite na namaz": "Come to prayer",
    "Hajje alel-felah": "Hayya ’alal-falah",
    "Dođite na spas": "Come to success",
    "La ilahe illellah": "La ilaha illallah",
    "Nema drugog boga osim Allaha": "There is no god but Allah",
    # 33 conditions
    "Dinski šarti": "Conditions of the religion (din)",
    "Ukupno 33 šarta": "33 conditions in total",
    "6": "6",
    "5": "5",
    "Abdeski šarti": "Fard acts of Wudu",
    "4": "4",
    "3 tejemumska": "3 for Tayammum",
    "3 gusulska": "3 for Ghusl",
    "Namaski šarti": "Conditions of Salah",
    "12": "12",
    "6 + 5 + 4 + 3 + 3 + 12": "6 + 5 + 4 + 3 + 3 + 12",
    "33 dinska šarta": "33 conditions of the religion",
    # Salawat
    "Allahumme salli ala Muhammedin ve ala ali Muhammed": "Allahumma salli ’ala Muhammadin wa ’ala ali Muhammad",
    "Allahu, podari milost Muhammedu i porodici Muhammedovoj": "O Allah, send Your mercy upon Muhammad and the family of Muhammad",
    "Kema sallejte ala Ibrahime ve ala ali Ibrahim": "Kama sallayta ’ala Ibrahima wa ’ala ali Ibrahim",
    "Kao što si podario milost Ibrahimu i porodici Ibrahimovoj": "As You sent mercy upon Ibrahim and the family of Ibrahim",
    "Inneke hamidun medžid": "Innaka Hamidun Majid",
    "Ti si, zaista, Hvaljen i Slavljen": "Truly, You are Praiseworthy and Glorious",
    "Allahumme barik ala Muhammedin ve ala ali Muhammed": "Allahumma barik ’ala Muhammadin wa ’ala ali Muhammad",
    "Allahu, podari blagoslov Muhammedu i porodici Muhammedovoj": "O Allah, send Your blessings upon Muhammad and the family of Muhammad",
    "Kema barekte ala Ibrahime ve ala ali Ibrahim": "Kama barakta ’ala Ibrahima wa ’ala ali Ibrahim",
    "Kao što si podario blagoslov Ibrahimu i porodici Ibrahimovoj": "As You sent blessings upon Ibrahim and the family of Ibrahim",
    # Dua after Salawat
    "Rabbena atina fid-dunja haseneten": "Rabbana atina fid-dunya hasanatan",
    "Gospodaru naš, podari nam dobro na ovom svijetu": "Our Lord, give us good in this world",
    "Ve fil-ahireti haseneten": "Wa fil-akhirati hasanatan",
    "I dobro na budućem svijetu": "And good in the Hereafter",
    "Ve kina azaben-nar": "Wa qina ’adhaban-nar",
    "I sačuvaj nas patnje u Vatri": "And protect us from the punishment of the Fire",
    "Rabbena-gfir li": "Rabbanaghfir li",
    "Gospodaru naš, oprosti meni": "Our Lord, forgive me",
    "Ve li validejje": "Wa li walidayya",
    "I mojim roditeljima": "And my parents",
    "Ve lil-mu'minine jevme jekumul-hisab": "Wa lil-mu’minina yawma yaqumul-hisab",
    "I vjernicima na Dan kada se bude polagao račun": "And the believers on the Day the account is taken",
    # Ayat al-Kursi (2:255)
    "Allahu la ilahe illa huvel-hajjul-kajjum": "Allahu laaa ilaaha illaa Huwal Haiyul Qaiyoom",
    "Allah je – nema boga osim Njega – Živi i Vječni": "Allah – there is no deity except Him, the Ever-Living, the Sustainer of [all] existence.",
    "La te'huzuhu sinetun ve la nevm": "Laa taakhuzuhoo sinatunw wa laa nawm",
    "Ne obuzima Ga ni drijemež ni san": "Neither drowsiness overtakes Him nor sleep.",
    "Lehu ma fis-semavati ve ma fil-erd": "Lahoo maa fissamaawaati wa maa fil ard",
    "Njegovo je ono što je na nebesima i ono što je na Zemlji": "To Him belongs whatever is in the heavens and whatever is on the earth.",
    "Men zellezi ješfe'u indehu illa bi iznih": "Man zal lazee yashfa'u indahooo illaa bi-iznih",
    "Ko se može pred Njim zauzimati bez Njegovog dopuštenja?": "Who is it that can intercede with Him except by His permission?",
    "Ja'lemu ma bejne ejdihim ve ma halfehum": "Ya'lamu maa baina aydeehim wa maa khalfahum",
    "On zna šta je bilo prije njih i šta će biti poslije njih": "He knows what is [presently] before them and what will be after them,",
    "Ve la juhitune bi šej'in min ilmihi illa bima ša'": "Wa laa yuheetoona bishai'im min 'ilmihee illaa bimaa shaaa'",
    "A od Njegovog znanja obuhvataju samo onoliko koliko On želi": "and they encompass not a thing of His knowledge except for what He wills.",
    "Vesi'a kursijjuhus-semavati vel-erd": "Wasi'a Kursiyyuhus samaawaati wal arda",
    "Njegov Kursij obuhvata i nebesa i Zemlju": "His Kursi extends over the heavens and the earth,",
    "Ve la je'uduhu hifzuhuma": "Wa laa ya'ooduho hifzuhumaa",
    "Njemu ne dojadi održavanje njihovo": "and their preservation tires Him not.",
    "Ve huvel-alijjul-azim": "Wa Huwal Aliyyul 'Azeem",
    "On je Svevišnji, Veličanstveni": "And He is the Most High, the Most Great.",
    # Getting ready for Salah
    "Čisto tijelo, odijelo i mjesto": "Clean body, clothes and place",
    "1.uvjet za namaz": "1st condition of Salah",
    "Abdest": "Wudu (ablution)",
    "Obredno čišćenje prije namaza": "Ritual washing before Salah",
    "Gusul": "Ghusl",
    "Kupanje cijelog tijela kada je propisano": "Washing the whole body when it is required",
    "Simbolično čišćenje kada se voda ne može koristiti": "Symbolic cleansing when water cannot be used",
    "Propisno odijevanje": "Proper dress (covering the body)",
    "3.uvjet za namaz": "3rd condition of Salah",
    "4.uvjet za namaz": "4th condition of Salah",
    "Na vrijeme klanjati": "Praying on time",
    "5.uvjet za namaz": "5th condition of Salah",
    "Okrenuti se prema Kibli": "Facing the Qiblah",
    "Nijet učiniti": "Making the intention (niyyah)",
    "6.uvjet za namaz": "6th condition of Salah",
    # At-Tahiyyat
    "Et-tehijjatu lillahi ves-salavatu vet-tajjibatu": "At-tahiyyatu lillahi was-salawatu wat-tayyibatu",
    "Najljepši pozdravi, salavati i dobra djela pripadaju Allahu": "The best greetings, prayers and good deeds belong to Allah",
    "Es-selamu alejke ejjuhen-nebijju ve rahmetullahi ve berekatuhu": "As-salamu ’alayka ayyuhan-nabiyyu wa rahmatullahi wa barakatuhu",
    "Neka su na tebe mir, Allahova milost i blagoslov, o Vjerovjesniče": "Peace be upon you, O Prophet, and Allah’s mercy and blessings",
    "Es-selamu alejna ve ala ibadillahis-salihin": "As-salamu ’alayna wa ’ala ’ibadillahis-salihin",
    "Neka je mir na nas i na Allahove dobre robove": "Peace be upon us and upon Allah’s righteous servants",
    "Ve ešhedu enne Muhammeden abduhu ve resuluhu": "Wa ashhadu anna Muhammadan ’abduhu wa rasuluhu",
    "I svjedočim da je Muhammed Njegov rob i poslanik": "And I bear witness that Muhammad is His servant and Messenger",
    # Iqamah
    "Kad kametis-salah": "Qad qamatis-salah",
    "Namaz upravo počinje": "The prayer is about to begin",
    # Prayer times
    "Od zore do izlaska Sunca": "From dawn until sunrise",
    "Kad sunce pređe polovinu neba do ikindije": "When the sun passes the middle of the sky, until Asr",
    "Kad Sunce nagne zapadu do pred zalazak Sunca": "When the sun leans west, until just before sunset",
    "Kad Sunce zađe pa do jacije": "When the sun sets, until Isha",
    "Kad noć potpuno padne": "When night has fully fallen",
    # Hasbi Rabbi
    "Hasbi Rabbi džellallah": "Hasbi Rabbi jallallah",
    "Dovoljan mi je moj Gospodar, Uzvišeni Allah": "My Lord is enough for me – Allah, the Exalted",
    "Ma fi kalbi gajrullah": "Ma fi qalbi ghayrullah",
    "U mome srcu nema nikoga osim Allaha": "In my heart there is no one but Allah",
    "Nur Muhammed sallallah": "Nur Muhammad sallallah",
    "Muhammed je svjetlo, neka je Allahov blagoslov na njega": "Muhammad is a light – may Allah bless him",
    # Fajr prayer
    "Sabahski sunnet": "Fajr Sunnah",
    "2 rekata suneta": "2 rak’ahs of Sunnah",
    "Sabahski farz": "Fajr fard",
    "2 rekata farza": "2 rak’ahs of fard",
    "Prvo se klanja": "Prayed first",
    "Poslije sunneta": "After the Sunnah",
    "Ukupno sabah-namaz": "Fajr prayer in total",
    "4 rekata": "4 rak’ahs",
    # Manners
    "Selam": "Salam",
    "Islamski pozdrav": "The Islamic greeting",
    "Es-selamu alejkum": "As-salamu ’alaykum",
    "Neka je mir na vas": "Peace be upon you",
    "Ve alejkumus-selam": "Wa ’alaykumus-salam",
    "I na vas neka je mir": "And upon you be peace",
    "Roditelji": "Parents",
    "Poštujemo ih i slušamo u dobru": "We respect them and obey them in what is good",
    "Stariji": "Older people",
    "Prema njima se odnosimo s poštovanjem": "We treat them with respect",
    "Mlađi": "Younger people",
    "Prema njima smo blagi i pažljivi": "We are gentle and caring with them",
    # Hijri New Year
    "Hidžra": "Hijrah",
    "Preseljenje Muhammeda, a.s., iz Mekke u Medinu": "The migration of Muhammad (SAW) from Makkah to Madinah",
    "Hidžretski kalendar": "Hijri calendar",
    "Počinje Hidžrom": "Begins with the Hijrah",
    "Prvi hidžretski mjesec": "First Hijri month",
    "Hidžretska godina": "Hijri year",
    "Ima 12 mjeseci": "Has 12 months",
    # Right words
    "Bismillāh": "Bismillah",
    "U ime Allaha – kada nešto radimo.": "In the name of Allah – when we start doing something.",
    "Inšallāh": "InshaAllah",
    "Ako Bog da – kada se nadamo nečemu.": "If Allah wills – when we hope for something.",
    "Māšallāh": "MashaAllah",
    "Što hoće Allah – kada se divimo.": "What Allah wills – when we admire something.",
    "Subhanallāh": "SubhanAllah",
    "Slava Allahu – kada smo oduševljeni i kada se čudimo.": "Glory be to Allah – when we are amazed or surprised.",
    "El-hamdu lillāh": "Alhamdulillah",
    "Hvala Allahu – u svakoj prilici.": "All praise and thanks be to Allah – at every moment.",
    "Jerhamukellāh": "Yarhamukallah",
    "Allah ti se smilovao – kada čujemo da je neko kihnuo.": "May Allah have mercy on you – when we hear someone sneeze.",
    "Ja Allāh": "Ya Allah",
    "O Allahu – kada smo u bolu i nevolji.": "O Allah – when we are in pain or trouble.",
    "Estagfirullāh": "Astaghfirullah",
    "Oprosti mi, Bože – kada se kajemo za loše djelo.": "Forgive me, O Allah – when we are sorry for a bad deed.",
    "Ne'uzubillāhi": "Na’udhu billah",
    "Tražimo zaštitu od Allaha – kada ukazujemo na nešto ružno.": "We seek refuge in Allah – when we point out something bad.",
    # Eating and drinking
    "Hrana": "Food",
    "Jesti zdravu i halal – dozvoljenu hranu.": "Eat healthy and halal (permitted) food.",
    "Prije jela": "Before eating",
    "Oprati ruke.": "Wash your hands.",
    "Prije početka jela": "Before you start eating",
    "Proučiti Euzubillu i Bismillu.": "Say A’udhu billah and Bismillah.",
    "Kako jedemo?": "How do we eat?",
    "Desnom rukom.": "With the right hand.",
    "S kim jedemo?": "Who do we eat with?",
    "Zajedno sa porodicom.": "Together with the family.",
    "Pravilo za hranu": "A rule for food",
    "Ne jesti vrelu hranu i ne puhati u jelo.": "Don’t eat food that is too hot and don’t blow on it.",
    "Nakon jela": "When we finish eating",
    "Zahvaliti Allahu riječima: El-hamdu lillāh – hvala Allahu.": "Thank Allah by saying: Alhamdulillah – praise be to Allah.",
    "Poslije jela": "After the meal",
    "Pospremiti sofru.": "Tidy up the table (sofra).",
    "Na kraju": "At the very end",
    "Nakon jela oprati zube.": "Brush your teeth after eating.",
}

m = re.search(r'const lessons=(\[.*?\]);\n', src)
lessons = json.loads(m.group(1))
missing = []
def tr(s):
    if s not in M:
        missing.append(s)
        return s
    return M[s]
for l in lessons:
    l['title'] = tr(l['title'])
    l['pairs'] = [[tr(a), tr(b)] for a, b in l['pairs']]
if missing:
    raise SystemExit('missing: ' + '\n'.join(missing))
out = src[:m.start(1)] + json.dumps(lessons, ensure_ascii=False) + src[m.end(1):]

UI = [
    ('<title>VELIKI MEMORI – ILMIHAL</title>', '<title>BIG MEMORY GAME – ILMIHAL</title>'),
    ('<h1>VELIKI MEMORI – ILMIHAL</h1>', '<h1>BIG MEMORY GAME – ILMIHAL</h1>'),
    ('<div class="sub">Izaberi lekciju i pronađi sve parove</div>', '<div class="sub">Choose a lesson and find all the pairs</div>'),
    ('<div class="sub"><b>Pripremio Abdo ef. Rekić</b></div>', ''),
    ('← Lekcije', '← Lessons'),
    ('<h2>Složi ajete pravilnim redoslijedom</h2>', '<h2>Put the ayahs in the right order</h2>'),
    ('<p>Dodirni ajete redom od prvog do posljednjeg.</p>', '<p>Tap the ayahs in order, from the first to the last.</p>'),
    ('>Ponovo</button>', '>Try again</button>'),
    ('<footer>Za Android • iPhone • računar</footer>', '<footer>For Android • iPhone • computer</footer>'),
    ("' parova)'", "' pairs)'"),
    ("'Parovi: '", "'Pairs: '"),
    ("' • Pokušaji: '", "' • Attempts: '"),
    ("'🎉 Bravo! Pronašao/la si sve parove!'", "'🎉 Well done! You found all the pairs!'"),
    ("'🌟 Odlično! Ajeti su složeni pravilnim redoslijedom.'", "'🌟 Excellent! The ayahs are in the right order.'"),
    ("'Pokušaj ponovo – izaberi sljedeći ajet po redu.'", "'Try again – choose the next ayah in order.'"),
]
for a, b in UI:
    assert out.count(a) == 1, a
    out = out.replace(a, b)
open(os.path.join(ROOT, 'work', G + '.en.html'), 'w', encoding='utf-8').write(out)
print('ok')
