"""Build work/islamski-milijunas-nivo-a2.en.html from work/islamski-milijunas-nivo-a2.bs.html.
Run from project root:  python3 tools/tr/islamski-milijunas-nivo-a2_build.py && python3 tools/skel.py build islamski-milijunas-nivo-a2
The 30-question array is rebuilt from M (one entry per unique Bosnian string, so answers always equal their option)."""
import json, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
G = 'islamski-milijunas-nivo-a2'
src = open(os.path.join(ROOT, 'work', G + '.bs.html'), encoding='utf-8').read()

M = {
    "Šta znači izraz „Hasbi Rabbi“?": "What does the phrase “Hasbi Rabbi” mean?",
    "Meni je dovoljan moj Gospodar": "My Lord is enough for me",
    "Muhammed je Allahov poslanik": "Muhammad is Allah’s Messenger",
    "U mom srcu je svjetlo": "There is light in my heart",
    "Allah je najveći": "Allah is the Greatest",
    "Ko je posljednji Allahov poslanik?": "Who is Allah’s last messenger?",
    "Musa, alejhis-selam": "Musa (AS)",
    "Isa, alejhis-selam": "Isa (AS)",
    "Muhammed, alejhis-selam": "Muhammad (SAW)",
    "Ibrahim, alejhis-selam": "Ibrahim (AS)",
    "Čime potvrđujemo svoju pripadnost islamu?": "How do we confirm that we belong to Islam?",
    "Učenjem ezana": "By calling the Adhan",
    "Izgovaranjem kelimei-šehadeta": "By saying the Shahadah",
    "Nazivanjem selama": "By giving salam",
    "Oblačenjem čiste odjeće": "By putting on clean clothes",
    "Kako glasi islamski pozdrav?": "What is the Islamic greeting?",
    "Es-selamu alejkum": "As-salamu ’alaykum",
    "Ve alejkumus-selam": "Wa ’alaykumus-salam",
    "Allahu ekber": "Allahu akbar",
    "Elhamdulillah": "Alhamdulillah",
    "Kojoj strani islam daje prednost?": "Which side does Islam give priority to?",
    "Lijevoj strani": "The left side",
    "Objema stranama podjednako": "Both sides equally",
    "Desnoj strani": "The right side",
    "Nijednoj strani": "Neither side",
    "Kako glasi dova za povećanje znanja?": "What is the dua for more knowledge?",
    "Rabbi jessir": "Rabbi yassir",
    "Subhanallah": "Subhanallah",
    "Rabbi zidni ilma": "Rabbi zidni ’ilma",
    "Kako se zove naša vjera?": "What is our religion called?",
    "Islam": "Islam",
    "Kršćanstvo": "Christianity",
    "Judaizam": "Judaism",
    "Budizam": "Buddhism",
    "Koja je naša sveta knjiga?": "What is our holy book?",
    "Ilmihal": "The Ilmihal (basic Islamic textbook)",
    "Sveska": "A notebook",
    "Udžbenik": "A schoolbook",
    "Kur’an": "The Qur’an",
    "Kada učimo Subhaneke?": "When do we recite Subhanaka?",
    "Poslije svakog namaza": "After every Salah",
    "Posebno na početku svakog namaza": "Especially at the start of every Salah",
    "Samo poslije selama": "Only after the salam",
    "Samo pred namaz": "Only just before Salah",
    "Kako se zove prva sura u Kur’anu?": "What is the first surah in the Qur’an called?",
    "El-Ihlas": "Al-Ikhlas",
    "El-Fatiha": "Al-Fatiha",
    "En-Nas": "An-Nas",
    "El-Kevser": "Al-Kawthar",
    "Koji je četvrti namaski šart?": "What is the fourth condition of Salah (prayer)?",
    "Propisno se obući": "Dressing properly",
    "Namaz klanjati na vrijeme": "Praying Salah on time",
    "Uzeti abdest": "Making Wudu (ablution)",
    "Okrenuti se prema Kibli": "Facing the Qiblah",
    "Koliko ima namaskih vremena, odnosno dnevnih namaza?": "How many prayer times, or daily prayers, are there?",
    "Tri": "Three",
    "Četiri": "Four",
    "Šest": "Six",
    "Pet": "Five",
    "Koji je prvi dnevni namaz?": "Which is the first daily prayer?",
    "Podne": "Dhuhr",
    "Ikindija": "Asr",
    "Sabah": "Fajr",
    "Akšam": "Maghrib",
    "Ko oglašava početak namaskog vremena?": "Who announces the start of a prayer time?",
    "Imam učenjem Kur'ana": "The imam, by reciting the Qur’an",
    "Mujezin učenjem ezana": "The muezzin (mu’adhdhin), by calling the Adhan",
    "Džemat učenjem dove": "The congregation, by making dua",
    "Hatib učenjem hutbe": "The khatib, by giving the khutbah",
    "Koji je peti namaski šart?": "What is the fifth condition of Salah?",
    "Nijet učiniti": "Making the intention (niyyah)",
    "Okrenuti se prema Kibli – Kabi": "Facing the Qiblah – the Ka’bah",
    "Šta je Kibla?": "What is the Qiblah?",
    "Smjer u kojem se nalazi Kaba": "The direction of the Ka’bah",
    "Mjesto za uzimanje abdesta": "The place where we make Wudu",
    "Džamijski harem": "The mosque courtyard",
    "Poziv za namaz": "The call to prayer",
    "Gdje se nalazi Kaba?": "Where is the Ka’bah?",
    "U Medini": "In Madinah",
    "U Jerusalemu": "In Jerusalem",
    "U Meki": "In Makkah",
    "U Damasku": "In Damascus",
    "Šta se nalazi u jednom uglu Kabe?": "What is in one corner of the Ka’bah?",
    "Mimbera": "The minbar (pulpit)",
    "Mihrab": "The mihrab (prayer niche)",
    "Izvor Zemzem": "The Zamzam spring",
    "Crni kamen – Hadžerul-esved": "The Black Stone – al-Hajar al-Aswad",
    "Koja je sura posljednja sura u Kur'anu?": "Which surah is the last surah in the Qur’an?",
    "El-Felek": "Al-Falaq",
    "Kako počinje sura En-Nas?": "How does Surah An-Nas begin?",
    "Allahus-Samed": "Allahus-Samad",
    "Kul e'uzu birabbin-nas": "Qul a’udhu birabbin-nas",
    "Kul huvallahu ehad": "Qul huwallahu ahad",
    "Min šerri ma halek": "Min sharri ma khalaq",
    "Šta su namaski šarti?": "What are the conditions (sharts) of Salah?",
    "Uvjeti koje trebamo ispuniti da bi nam namaz bio ispravan": "Things we must do so that our Salah is valid",
    "Dobrovoljni dijelovi namaza": "Optional parts of Salah",
    "Dove poslije namaza": "Duas after Salah",
    "Vrste namaza": "Kinds of Salah",
    "Koliko ukupno ima namaskih šarta?": "How many conditions of Salah are there in total?",
    "6": "6",
    "10": "10",
    "12": "12",
    "14": "14",
    "Koji je prvi namaski rukn?": "What is the first pillar (rukn) of Salah?",
    "Kijam": "Qiyam",
    "Ruku'": "Ruku’",
    "Sedžda": "Sajdah",
    "Iftitahi-tekbir – početni tekbir": "Takbir al-Iftitah – the opening takbir",
    "Šta znači kijam?": "What does qiyam mean?",
    "Učenje Kur'ana": "Reciting the Qur’an",
    "Pregibanje": "Bowing",
    "Stajanje u namazu": "Standing in Salah",
    "Sjedenje": "Sitting",
    "Šta je kiraet?": "What is qira’ah?",
    "Učenje Kur'ana u namazu": "Reciting the Qur’an in Salah",
    "Spuštanje lica na tlo": "Putting the face down on the ground",
    "Sjedenje na kraju namaza": "Sitting at the end of Salah",
    "Šta je ezan?": "What is the Adhan?",
    "Dova poslije namaza": "A dua after Salah",
    "Oglašavanje početka namaskog vremena": "Announcing the start of a prayer time",
    "Učenje Kur'ana prije namaza": "Reciting the Qur’an before Salah",
    "Pozdrav poslije namaza": "A greeting after Salah",
    "Ko uči ezan?": "Who calls the Adhan?",
    "Mujezin": "The muezzin (mu’adhdhin)",
    "Hatib": "The khatib",
    "Svaki klanjač istovremeno": "Everyone praying, all at once",
    "Samo imam": "Only the imam",
    "Koji je treći namaski šart?": "What is the third condition of Salah?",
    "Propisno odijevanje": "Proper dress (covering the body)",
    "Na vrijeme klanjati": "Praying on time",
    "Šta je abdest?": "What is Wudu (ablution)?",
    "Kupanje cijelog tijela": "Washing the whole body",
    "Vjersko pranje određenih dijelova tijela": "Religious washing of certain parts of the body",
    "Pranje samo ruku": "Washing only the hands",
    "Pranje odjeće": "Washing clothes",
    "Koliko ima abdeskih šarta – farza?": "How many fard acts (sharts) of Wudu are there?",
}

m = re.search(r'const base=(\[.*?\]); let', src)
base = json.loads(m.group(1))
missing = []
def tr(s):
    if s not in M:
        missing.append(s)
        return s
    return M[s]
for x in base:
    x['q'] = tr(x['q'])
    x['opts'] = [tr(o) for o in x['opts']]
    x['ans'] = tr(x['ans'])
    assert x['ans'] in x['opts']
if missing:
    raise SystemExit('missing: ' + '\n'.join(missing))
out = src[:m.start(1)] + json.dumps(base, ensure_ascii=False) + src[m.end(1):]

UI = [
    ('<title>Islamski milijunaš – Nivo A2</title>', '<title>Islamic Millionaire – Level A2</title>'),
    ('<h1>ISLAMSKI MILIJUNAŠ</h1><div class="sub">NIVO A2 • Pripremio Abdo ef. Rekić</div>',
     '<h1>ISLAMIC MILLIONAIRE</h1><div class="sub">LEVEL A2</div>'),
    ('<h2>30 pitanja</h2>', '<h2>30 questions</h2>'),
    ('<p>Prvih <b>10 pitanja</b> je iz baze Nivo A1, a narednih <b>20 pitanja</b> iz baze Nivo A2.</p>',
     '<p>The first <b>10 questions</b> come from the Level A1 bank, and the next <b>20 questions</b> from the Level A2 bank.</p>'),
    ('<p>Odgovori se pri svakom pokretanju izmiješaju.</p>', '<p>The answers are shuffled every time you play.</p>'),
    ('>POČNI KVIZ</button>', '>START QUIZ</button>'),
    ('id="score">Bodovi: 0</span>', 'id="score">Points: 0</span>'),
    ('<h2>ZAVRŠENO!</h2>', '<h2>FINISHED!</h2>'),
    ('>IGRAJ PONOVO</button>', '>PLAY AGAIN</button>'),
    ('<div class="small">Android • iPhone • radi u mobilnom pregledniku</div>', '<div class="small">Android • iPhone • works in your phone’s browser</div>'),
    ('`Pitanje ${i+1}/30`', '`Question ${i+1}/30`'),
    ('`Bodovi: ${points}`', '`Points: ${points}`'),
    ("'NIVO A1 • ponavljanje':'NIVO A2'", "'LEVEL A1 • review':'LEVEL A2'"),
    ("'✓ Tačno!'", "'✓ Correct!'"),
    ("'✗ Tačan odgovor: '", "'✗ Correct answer: '"),
    ('`Rezultat: ${points} / 30`', '`Score: ${points} / 30`'),
]
for a, b in UI:
    assert out.count(a) == 1, a
    out = out.replace(a, b)
open(os.path.join(ROOT, 'work', G + '.en.html'), 'w', encoding='utf-8').write(out)
print('ok')
