# English question bank for lov-na-blago-a1, same order / option order as the original BANK.
# Each entry: (question, [4 options]). The correct index is taken from the original.
H = 'Muhammad, ‘alayhis-salam'
B = [
("What does the phrase “Hasbi Rabbi” mean?", ["My Lord is enough for me", "Muhammad is Allah’s messenger", "There is light in my heart", "Allah is the Greatest"]),
("Who is enough for a believer?", ["A friend", "A teacher", "A parent", "Allah, the Most High"]),
("According to the nasheed (ilahi), who is in our heart?", ["Only our family", "Only our friends", "Only Allah", "Only our teachers"]),
("What is the second line of the nasheed Hasbi Rabbi?", ["Nur Muhammad sallallah", "La ilaha illallah", "Hasbi Rabbi jallallah", "Ma fi qalbi ghayrullah"]),
("What is the third line of the nasheed Hasbi Rabbi?", ["La ilaha illallah", "Hasbi Rabbi jallallah", "Nur Muhammad sallallah", "Ma fi qalbi ghayrullah"]),
("What is the last line of the nasheed Hasbi Rabbi?", ["Hasbi Rabbi jallallah", "La ilaha illallah", "Ma fi qalbi ghayrullah", "Nur Muhammad sallallah"]),
("What does “La ilaha illallah” mean?", ["There is no god except Allah", "Allah is Merciful", "Muhammad is a light", "Allah is our Creator"]),
("According to the nasheed Hasbi Rabbi, who is our light?", ["The Sun", "The Moon", H, "A teacher"]),
("Who does a Muslim rely on?", ["Only on himself", "On his friends", "On other people", "Only on Allah (SWT)"]),
("What does a Muslim carry out?", ["Allah’s commands", "All of his own wishes", "His friends’ orders", "Other people’s customs"]),
("What does a Muslim stay away from?", ["Learning", "Good deeds", "What Allah has forbidden", "Salah (prayer)"]),
("Who is our role model in how we behave?", ["Any famous person", "Kids our own age", "Rich people", H]),
("In what is " + H + ", our role model?", ["Only in how he dressed", "In how he behaved", "Only in how he spoke", "In getting rich"]),
("What should a Muslim do with Allah’s commands?", ["Carry them out", "Forget them", "Put them off", "Avoid them"]),
("Which message matches the nasheed “Hasbi Rabbi”?", ["A person should rely only on their own strength", "The most important thing is to get rich", "A Muslim believes in Allah and follows His commands", "A person does not need a role model"]),
("Who is Allah’s last messenger?", ["Musa, ‘alayhis-salam", "Isa, ‘alayhis-salam", H, "Ibrahim, ‘alayhis-salam"]),
("Where was " + H + ", born?", ["In Makkah", "In Madinah", "In Jerusalem", "In Taif"]),
("On which Hijri date was " + H + ", born?", ["1 Muharram", "27 Rajab", "15 Sha‘ban", "12 Rabi‘ al-Awwal"]),
("In which year was " + H + ", born?", ["In 610", "In 571", "In 622", "In 632"]),
("On which date of the Gregorian calendar was " + H + ", born?", ["20 April", "1 January", "10 May", "12 June"]),
("What was the name of the father of " + H + "?", ["Abu Talib", "Abdul-Muttalib", "Abdullah", "Hamza"]),
("What was the name of the mother of " + H + "?", ["Khadijah", "Aminah", "Fatimah", "Halimah"]),
("Who did " + H + ", stay with after his parents died?", ["With his friends", "With neighbours", "With a teacher", "With his grandfather and his uncle"]),
("What was the name of the grandfather of " + H + "?", ["Abdul-Muttalib", "Abu Talib", "Abdullah", "Abbas"]),
("What was the name of the uncle of " + H + ", who raised him?", ["Abu Bakr", "Umar", "Abu Talib", "Uthman"]),
("At what age did Allah, the Most High, begin sending the Revelation (wahy) to " + H + "?", ["At twenty", "At forty", "At thirty", "At fifty"]),
("What do we say when we mention the name Muhammad?", ["Alhamdulillah", "‘Alayhis-salam", "Salam", "Allahu akbar"]),
("What does the phrase “‘alayhis-salam” mean?", ["May Allah have mercy on him", "Allah is the Greatest", "May Allah’s peace be upon him", "Praise be to Allah"]),
("Who should be our role model in how we behave?", ["The richest person", "The most famous athlete", "The best singer", H]),
("How is " + H + ", related to Abdul-Muttalib?", ["Abdul-Muttalib was his father", "Abdul-Muttalib was his grandfather", "Abdul-Muttalib was his uncle", "Abdul-Muttalib was his friend"]),
("How is " + H + ", related to Abu Talib?", ["Abu Talib was his grandfather", "Abu Talib was his brother", "Abu Talib was his uncle", "Abu Talib was his son"]),
("How do we confirm that we belong to Islam?", ["By calling the Adhan", "By saying the Kalimah Shahadah (declaration of faith)", "By giving salam", "By wearing clean clothes"]),
("How many parts does the Kalimah Shahadah have?", ["Three", "Four", "One", "Two"]),
("What do we bear witness to in the first part of the Kalimah Shahadah?", ["That Muhammad is the last messenger", "That angels exist", "That there is no god except Allah", "That fasting is obligatory"]),
("What do we bear witness to in the second part of the Kalimah Shahadah?", ["That Muhammad is Allah’s servant and messenger", "That Musa, ‘alayhis-salam, is the last messenger", "That we believe in the holy books (kutub)", "That we believe in the angels"]),
("How does the Kalimah Shahadah begin?", ["Alhamdulillahi rabbil-‘alamin", "Ash-hadu an la ilaha illallah", "Bismillahir-Rahmanir-Rahim", "Subhana rabbiyal-‘azim"]),
("What is salam?", ["A special dua after Salah", "The name of one of the prayers", "The call to prayer", "The greeting Muslims use to greet each other"]),
("What is the Islamic greeting?", ["As-salamu alaykum", "Wa alaykumus-salam", "Allahu akbar", "Alhamdulillah"]),
("How do we reply to salam?", ["As-salamu alaykum", "Alaykumus-salam", "MashaAllah", "SubhanAllah"]),
("Which words are nice to add when giving salam?", ["Allahu akbar kabira", "Alhamdulillahi rabbil-‘alamin", "Wa rahmatullahi wa barakatuhu", "Astaghfirullah"]),
("What does the Islamic greeting – salam – mean?", ["May Allah’s peace and blessings be upon you", "Have a safe trip", "I wish you a nice day", "Welcome to my home"]),
("Who do we give salam to?", ["Only to our parents", "Only to our teachers", "Only to our friends", "To our parents, relatives, friends and Muslims we know"]),
("When do we give salam at home?", ["Only when leaving", "When entering and leaving the home", "Only in the morning", "Only in the evening"]),
("When else do we give salam?", ["When we join a group of people or leave it", "Only when we enter the mosque", "Only after eating", "Only before sleeping"]),
("Which side does Islam give preference to?", ["The left side", "Both sides equally", "The right side", "Neither side"]),
("Which hand should we eat with?", ["The left hand", "Both hands", "It does not matter which hand", "The right hand"]),
("Which sleeve do we put on first?", ["The right sleeve", "The left sleeve", "Both sleeves at the same time", "There is no rule"]),
("What is the right way to put on and take off shoes?", ["Put on the left shoe first, take off the right shoe first", "Put on the right shoe first, take off the left shoe first", "Always put on and take off the left shoe first", "The order does not matter"]),
("Which side is it recommended to sleep on?", ["On the stomach", "On the left side", "On the right side", "On the back"]),
("Which dua do we say before starting a task?", ["The dua for travelling", "Rabbi yassir", "The dua after eating", "The dua for rain"]),
("What do we ask Allah for with the words “Rabbi yassir”?", ["To give us lots of wealth", "To give us a long life", "To make things easy for us", "To make us famous"]),
("How does the dua for a blessed (khayr) beginning start?", ["Rabbi zidni ‘ilma", "Bismillahi", "Alhamdulillahi", "Rabbi yassir wa la tu‘assir"]),
("What does “wa la tu‘assir” mean?", ["And do not make it hard", "Increase my knowledge", "Forgive my sins", "Protect me on the way"]),
("What does “Rabbi tammim bil-khayr” mean?", ["My Lord, increase my knowledge", "My Lord, complete my work with good", "My Lord, give me good health", "My Lord, forgive my parents"]),
("What do we ask Allah for with the dua for a blessed beginning?", ["Ease, blessing and success in good deeds", "Only money and riches", "Winning every game", "Never having to work"]),
("Who gives people knowledge?", ["Only books", "Only school", "Allah", "Only parents"]),
("What is the dua for more knowledge?", ["Rabbi yassir", "SubhanAllah", "Alhamdulillah", "Rabbi zidni ‘ilma"]),
("What does “Rabbi zidni ‘ilma” mean?", ["My Lord, increase me in knowledge", "My Lord, make my way easy", "My Lord, give me food", "My Lord, heal me"]),
("In which surah of the Qur’an is the dua “Rabbi zidni ‘ilma”?", ["Al-Fatiha", "Ta-Ha", "Al-Ikhlas", "An-Nas"]),
("What is the ayah number of the dua “Rabbi zidni ‘ilma”?", ["Ayah 14", "Ayah 40", "Ayah 114", "Ayah 120"]),
("When should we say the dua for knowledge?", ["Only before sleeping", "Only before eating", "Only before a journey", "Before we start studying and doing homework"]),
("What is the name of our religion?", ["Islam", "Christianity", "Judaism", "Buddhism"]),
("What are we by religion?", ["Only students", "Muslim boys and girls", "Travellers", "Poets"]),
("Who do Muslims believe in?", ["Only in people", "In the sun and the stars", "In Allah", "In statues"]),
("What should Muslims say?", ["The truth", "Lies", "Bad words", "Things that hurt others"]),
("What kind of deeds should Muslims do?", ["Bad deeds", "Good deeds", "Only easy deeds", "Useless deeds"]),
("What does Islam ask of believers?", ["Laziness", "Unfairness", "Sacrifice, learning and hard work", "Arrogance"]),
("What does Islam lead us to?", ["Sin", "Quarrels", "Failure", "Happiness and success"]),
("Who is our prophet?", ["Yunus (AS)", "Nuh (AS)", "Muhammad (AS)", "Jibril (AS)"]),
("What is our holy book?", ["The Ilmihal (religion textbook)", "A notebook", "A schoolbook", "The Qur’an"]),
("What is our religion?", ["Islam", "The Qur’an", "Dua", "Salah"]),
("What do we say before Bismillah?", ["Takbir", "A‘udhu billah", "Salawat", "Al-Fatiha"]),
("What do the words of A‘udhu billah mean?", ["Praise be to Allah, Lord of the worlds", "Allah is the Greatest", "I ask Allah for forgiveness", "I seek Allah’s protection from the accursed Shaytan"]),
("With which names of Allah does Bismillah end?", ["The Most Merciful, the Most Compassionate", "The Mighty and the Wise", "The First and the Last", "The Creator and the Provider"]),
("How do we begin good and blessed (khayr) tasks?", ["By calling the Adhan", "By saying the Takbir", "By saying A‘udhu billah and Bismillah", "By giving salam"]),
("What do we ask for by saying A‘udhu billah and Bismillah?", ["That Allah gives us lots of wealth", "That Allah protects us and gives us His mercy", "That we always win at games", "That we are never tired"]),
("When should we say A‘udhu billah and Bismillah?", ["Only in the morning", "Only before sleeping", "Only when we read the Qur’an", "On many different occasions"]),
("When, among other times, do we say A‘udhu billah and Bismillah?", ["In the morning and in the evening", "Only on Fridays", "Only in the mosque", "Only during Ramadan"]),
("What should we say when we start a ride or drive?", ["Only the dua after eating", "Only salawat", "A‘udhu billah and Bismillah", "We don’t need to say anything"]),
("What is Allah’s most beautiful creation?", ["A plant", "A human being", "A mountain", "A river"]),
("How should we live on Earth?", ["Without any rules", "Responsibly, obeying Allah, the Most High", "Thinking only about playing", "Far away from other people"]),
("Why were jinn and humans created?", ["Only to play", "To collect riches", "To travel the world", "To worship Allah"]),
("About how many neurons are there in the human brain?", ["About 100 billion", "About 100 thousand", "About 100 million", "About one million"]),
("Who did Mirza come to the maktab with on his first day?", ["With his friends", "Alone", "With his parents", "With his teacher"]),
("Who did the students meet at the maktab?", ["Their muallim and muallima (teachers)", "A doctor and a nurse", "A driver and a police officer", "A shopkeeper and a customer"]),
("What do children learn about at the maktab?", ["Only about sports", "About Islamic belief, duties and good manners", "Only about maths", "Only about writing"]),
("What made Mirza happy at the maktab?", ["The end of the lesson", "Getting a toy", "Going back home", "Meeting his friends"]),
("When do we say Subhanaka?", ["After every Salah", "Especially at the beginning of every Salah", "Only after the salam", "Only just before Salah"]),
("Which words does Subhanaka begin with?", ["Al-hamdu lillahi", "Bismillahir-Rahmanir-Rahim", "Subhanakallahumma", "Iyyaka na‘budu"]),
("Which words come after “Subhanakallahumma”?", ["Wa tabarakasmuka", "Wa la ilaha ghayruka", "Wa ta‘ala jadduka", "Wa bihamdika"]),
("What does the phrase “Subhanakallahumma” mean?", ["Glory be to You, O Allah", "Guide us to the straight path", "You alone we worship", "You alone we ask for help"]),
("What does “wa bihamdika” mean?", ["Great is Your name", "And all praise is Yours", "There is no god but You", "You are the Master of the Day of Judgement"]),
("Which part of Subhanaka means: “Blessed is Your name”?", ["Wa bihamdika", "Wa ta‘ala jadduka", "Wa tabarakasmuka", "Wa la ilaha ghayruka"]),
("What does “wa ta‘ala jadduka” mean?", ["And all praise is Yours", "Blessed is Your name", "Glory be to You, O Allah", "Your majesty is beyond reach"]),
("Which words does Subhanaka end with?", ["Wa la ilaha ghayruka", "Amin", "Ihdinas-siratal-mustaqim", "Maliki yawmid-din"]),
("What does “wa la ilaha ghayruka” mean?", ["We praise You, O Allah", "There is no god but You", "Guide us to the straight path", "You alone we ask for help"]),
("What comes after the words “wa bihamdika”?", ["Wa ta‘ala jadduka", "Wa la ilaha ghayruka", "Wa tabarakasmuka", "Subhanakallahumma"]),
("Which part comes right before “wa la ilaha ghayruka”?", ["Wa bihamdika", "Wa tabarakasmuka", "Subhanakallahumma", "Wa ta‘ala jadduka"]),
("When is it recommended to say Subhanaka?", ["At the beginning of every Salah", "Only once in your life", "After every rak‘ah", "Only on Fridays"]),
("Which sentence belongs to Subhanaka?", ["Iyyaka na‘budu", "Wa tabarakasmuka", "Ihdinas-siratal-mustaqim", "Maliki yawmid-din"]),
("Which sentence does NOT belong to Subhanaka?", ["Wa bihamdika", "Wa ta‘ala jadduka", "Ar-Rahmanir-Rahim", "Wa la ilaha ghayruka"]),
("Which meaning is part of the translation of Subhanaka?", ["Guide us to the straight path", "You alone we worship", "Master of the Day of Judgement", "Your majesty is beyond reach"]),
("What does Subhanaka say about Allah’s name?", ["That it is blessed", "That it should be mentioned", "That only the angels know it", "That it is said only on Fridays"]),
("What do we confirm at the end of Subhanaka?", ["That Al-Fatiha is the first surah", "That there is no god except Allah", "That the Salah is finished", "That we seek protection from Shaytan"]),
("What is the correct order of the first parts of Subhanaka?", ["Wa bihamdika – Subhanakallahumma", "Wa tabarakasmuka – Wa bihamdika", "Subhanakallahumma – Wa bihamdika", "Wa ta‘ala jadduka – Wa tabarakasmuka"]),
("In the order of the Qur’an, which surah is Al-Fatiha?", ["The first", "The second", "The seventh", "The last"]),
("What is the name of the first surah in the Qur’an?", ["Al-Ikhlas", "Al-Fatiha", "An-Nas", "Al-Kawthar"]),
("With which words do we seek Allah’s protection from the accursed Shaytan?", ["Al-hamdu lillahi Rabbil-‘alamin", "Bismillahir-Rahmanir-Rahim", "A‘udhu billahi minash-shaytanir-rajim", "Iyyaka na‘budu wa iyyaka nasta‘in"]),
("What does “A‘udhu billahi minash-shaytanir-rajim” mean?", ["In the name of Allah, the Most Merciful, the Most Compassionate", "You alone we worship", "Guide us to the straight path", "I seek Allah’s protection from the accursed Shaytan"]),
("What are the words of Bismillah?", ["Bismillahir-Rahmanir-Rahim", "Al-hamdu lillahi Rabbil-‘alamin", "Maliki yawmid-din", "Ihdinas-siratal-mustaqim"]),
("What does Bismillah mean?", ["Praise be to Allah, Lord of the worlds", "In the name of Allah, the Most Merciful, the Most Compassionate", "Guide us to the straight path", "You alone we worship"]),
("Which words start Al-Fatiha after Bismillah?", ["Ar-Rahmanir-Rahim", "Maliki yawmid-din", "Al-hamdu lillahi Rabbil-‘alamin", "Iyyaka na‘budu wa iyyaka nasta‘in"]),
("What does “Al-hamdu lillahi Rabbil-‘alamin” mean?", ["Master of the Day of Judgement", "Guide us to the straight path", "You alone we worship", "All praise is for Allah, Lord of the worlds"]),
("Which of Allah’s attributes do we mention with the words “Ar-Rahmanir-Rahim”?", ["The Most Merciful, the Most Compassionate", "The Strong and the Mighty", "The First and the Last", "The Creator and the Provider"]),
("What does “Maliki yawmid-din” mean?", ["Lord of the worlds", "Master of the Day of Judgement", "The Most Merciful, the Most Compassionate", "The One who guides to the straight path"]),
("Which words mean: “You alone we worship and You alone we ask for help”?", ["Ar-Rahmanir-Rahim", "Maliki yawmid-din", "Iyyaka na‘budu wa iyyaka nasta‘in", "Siratal-ladhina an‘amta ‘alayhim"]),
("In Al-Fatiha, who do we ask for help?", ["People", "The angels", "The prophets", "Allah"]),
("What do we ask for with the words “Ihdinas-siratal-mustaqim”?", ["For Allah to guide us to the straight path", "To give us riches", "To make us famous", "To make things"]),
("Which part of Al-Fatiha means “Guide us to the straight path”?", ["Maliki yawmid-din", "Ihdinas-siratal-mustaqim", "Ar-Rahmanir-Rahim", "Wa la ilaha ghayruka"]),
("Whose path do we ask Allah to guide us to?", ["The path of the richest people", "The path of all rulers", "The path of those whom Allah has blessed", "The path of those who went astray"]),
("What does “Siratal-ladhina an‘amta ‘alayhim” mean?", ["The path of those who went astray", "The path of those who earned Allah’s anger", "Master of the Day of Judgement", "The path of those whom You have blessed"]),
("At the end of Al-Fatiha, whose path do we NOT want to follow?", ["The path of those who earned Allah’s anger and those who went astray", "The path of good people", "The path of Allah’s prophets", "The path of grateful believers"]),
("Which word do we say when we finish reciting Al-Fatiha?", ["SubhanAllah", "Amin", "Alhamdulillah", "Allahu akbar"]),
("What does the word “Amin” mean?", ["Allah is the Greatest", "Glory be to Allah", "O Allah, answer our dua", "I seek protection from Shaytan"]),
("Why is Al-Fatiha especially important?", ["It is recited only on Fridays", "It is the longest surah of the Qur’an", "It is recited only on Eid", "It is the best dua and we recite it in Salah"]),
("How is Al-Fatiha described in the picture?", ["As the best dua", "As the longest surah", "As the last surah", "As a dua that is not recited in Salah"]),
("What is recommended to say on every occasion?", ["Wa la ilaha ghayruka", "Al-hamdu lillah – praise be to Allah", "Ihdinas-siratal-mustaqim", "Maliki yawmid-din"]),
("Which sentence comes after “Al-hamdu lillahi Rabbil-‘alamin”?", ["Maliki yawmid-din", "Iyyaka na‘budu", "Ar-Rahmanir-Rahim", "Ihdinas-siratal-mustaqim"]),
("Which sentence comes right after “Maliki yawmid-din”?", ["Ar-Rahmanir-Rahim", "Ihdinas-siratal-mustaqim", "Siratal-ladhina an‘amta ‘alayhim", "Iyyaka na‘budu wa iyyaka nasta‘in"]),
("Which sentence comes after “Iyyaka na‘budu wa iyyaka nasta‘in”?", ["Ihdinas-siratal-mustaqim", "Maliki yawmid-din", "Ar-Rahmanir-Rahim", "Wa ta‘ala jadduka"]),
("What do we say about Allah in Al-Fatiha?", ["That He is the Lord of only one people", "That He is the Lord of the worlds", "That He created only humans", "That we ask others for help"]),
("Which sentence does NOT belong to Surah Al-Fatiha?", ["Ar-Rahmanir-Rahim", "Maliki yawmid-din", "Wa tabarakasmuka", "Ihdinas-siratal-mustaqim"]),
("Which part of Al-Fatiha talks about the Day of Judgement?", ["Ar-Rahmanir-Rahim", "Al-hamdu lillahi Rabbil-‘alamin", "Iyyaka na‘budu wa iyyaka nasta‘in", "Maliki yawmid-din"]),
("What do the words “Iyyaka na‘budu” teach us?", ["That we worship only Allah", "That we worship people", "That we ask statues for help", "That Salah is not obligatory"]),
("What is the main request in Surah Al-Fatiha?", ["A request for great riches", "A request that Allah guides us to the straight path", "A request never to work", "A request for a long life without tests"]),
("What does the word “din” mean?", ["Salah", "Religion", "Cleanliness", "Fasting"]),
("What does the word “shart” mean?", ["Condition", "Reward", "Dua", "Duty"]),
("What are the conditions of the religion (shurut ad-din)?", ["Only the conditions for Salah", "Rules of good manners", "Conditions and actions every adult must fulfil for complete faith", "Only the pillars of Iman"]),
("How many conditions of the religion are there in total?", ["25", "30", "32", "33"]),
("How many pillars of Iman (faith) are there?", ["5", "6", "4", "3"]),
("How many pillars of Islam are there?", ["5", "6", "12", "4"]),
("How many fard parts of Wudu (ablution) are there?", ["3", "5", "6", "4"]),
("How many fard parts of Tayammum are there?", ["4", "6", "3", "5"]),
("How many fard parts of Ghusl are there?", ["3", "4", "5", "6"]),
("How many conditions of Salah (prayer) are there?", ["10", "12", "6", "5"]),
("Which group of the conditions of the religion has the most conditions?", ["Iman", "Islam", "Salah", "Wudu"]),
("Which of these groups has six conditions?", ["Ghusl", "Tayammum", "Islam", "Iman"]),
("Which group has five conditions?", ["The pillars of Islam", "The pillars of Iman", "The fard parts of Ghusl", "The fard parts of Tayammum"]),
("Which group has four conditions?", ["Salah", "Wudu", "Iman", "Islam"]),
("Which two groups have three conditions each?", ["Iman and Islam", "Wudu and Salah", "Tayammum and Ghusl", "Islam and Ghusl"]),
("How many do the pillars of Iman and of Islam have together?", ["9", "10", "12", "11"]),
("How many do the fard parts of Wudu and of Ghusl have together?", ["7", "6", "8", "9"]),
("How many do the fard parts of Tayammum and of Ghusl have together?", ["5", "6", "7", "8"]),
("How many do the conditions of Salah and the pillars of Islam have together?", ["15", "16", "17", "18"]),
("How many more conditions of Salah are there than pillars of Iman?", ["4", "5", "7", "6"]),
("What is ihsan?", ["The highest level of awareness of Allah, the Most High", "A type of Salah", "A type of fasting", "One of the fard parts of Wudu"]),
("How is ihsan explained?", ["That we mention Allah only after Salah", "To worship Allah as if we see Him, because even if we do not see Him, He sees us", "That we study only at night", "That we talk only about good deeds"]),
("Who always sees us, even though we do not see Him?", ["An angel", "A teacher", "Allah, the Most High", "Our parents"]),
("What does believing in ihsan motivate us to do?", ["Only to study", "Only to fast", "Only to help others", "To keep fulfilling the conditions of the religion"]),
("Who must fulfil the conditions of the religion?", ["Every adult", "Only children", "Only imams", "Only elderly people"]),
("What is fulfilling the conditions of the religion needed for?", ["For travelling", "For complete faith", "For schooling", "For trade"]),
("Which set of numbers matches the pillars of Iman, the pillars of Islam and the fard parts of Wudu?", ["6, 5, 4", "5, 6, 3", "6, 4, 5", "12, 6, 4"]),
("Which set gives the numbers for all six groups of the conditions of the religion from the lesson?", ["5, 6, 4, 4, 3, 11", "6, 5, 4, 3, 3, 12", "6, 5, 5, 3, 4, 10", "6, 4, 4, 3, 3, 12"]),
]
