T = [
    ('<title>Pronađi riječ – Meleki</title>', '<title>Word Search – Angels</title>'),
    ('<h1>PRONAĐI RIJEČ – MELEKI</h1>', '<h1>WORD SEARCH – ANGELS</h1>'),
    ('Pročitaj opis i pronađi odgovor među slovima.', 'Read the clue and find the answer among the letters.'),
    ('Zadatak: <span', 'Task: <span'), ('Bodovi: <span', 'Points: <span'),
    ('<small>KO JE / ŠTA JE TO?</small>', '<small>WHO / WHAT IS IT?</small>'),
    ('💡 Pomoć<', '💡 Hint<'), ('↻ Nova igra', '↻ New game'),
    (' <div class="footer">Pripremio Abdo ef. Rekić</div>\n', ''),
    ('["DZIBRIL","Prenosio je Allahove objave poslanicima."]', '["JIBRIL","He brought Allah’s revelation to the messengers."]'),
    ('["MIKAIL","Melek zadužen za kišu i opskrbu, Allahovom naredbom."]', '["MIKAIL","The angel in charge of rain and provision, by Allah’s command."]'),
    ('["ISRAFIL","Melek koji će puhnuti u Sur."]', '["ISRAFIL","The angel who will blow the Trumpet (Sur)."]'),
    ('["MELEKULMEVT","Melek smrti, zadužen za uzimanje duša po Allahovoj naredbi."]', '["MALAKULMAWT","The Angel of Death, in charge of taking souls by Allah’s command."]'),
    ('["MUNKIR","Jedan od meleka koji ispituju čovjeka u kaburu."]', '["MUNKAR","One of the angels who question a person in the grave (qabr)."]'),
    ('["NEKIR","Jedan od meleka koji ispituju čovjeka u kaburu."]', '["NAKIR","One of the angels who question a person in the grave (qabr)."]'),
    ('["MALIK","Čuvar Džehennema koji se imenom spominje u Kur\'anu."]', '["MALIK","The guardian of Jahannam, who is mentioned by name in the Qur’an."]'),
    ('["KIRAMENKATIBIN","Meleki koji zapisuju čovjekova djela."]', '["KATIBIN","The angels who write down a person’s deeds: Kiraman ...?"]'),
    ('["MELEKI","Allahova stvorenja koja Mu se ne protive i izvršavaju ono što im naredi."]', '["ANGELS","Allah’s creations who never disobey Him and do whatever He commands them."]'),
    ('["NUR","Prema hadisu, meleki su stvoreni od ovoga."]', '["LIGHT","According to a hadith, angels were created from this (nur)."]'),
    ('["SUR","U njega će Israfil puhnuti po Allahovoj naredbi."]', '["TRUMPET","Israfil will blow into it by Allah’s command."]'),
    ('["OBJAVA","Džibril ju je donosio Allahovim poslanicima."]', '["REVELATION","Jibril brought it to Allah’s messengers (wahy)."]'),
    ('["DJELA","Kiramen-katibin ih zapisuju čovjeku."]', '["DEEDS","The Kiraman Katibin write these down for each person."]'),
    ('["KABUR","Mjesto u kojem Munkir i Nekir ispituju umrlog."]', '["GRAVE","The place where Munkar and Nakir question the one who has died."]'),
    ('["ALLAH","Meleki su Njegovi pokorni robovi i izvršavaju Njegove naredbe."]', '["ALLAH","The angels are His obedient servants and carry out His commands."]'),
    ('"Bravo! Završio/la si igru."', '"Well done! You finished the game."'),
    ('"Ukupno bodova: "', '"Total points: "'),
    ('"Povuci prstom preko slova."', '"Drag your finger across the letters."'),
    ('>Povuci prstom preko slova.<', '>Drag your finger across the letters.<'),
    ('"✓ Tačno! +10"', '"✓ Correct! +10"'),
    ('"Pokušaj ponovo. −3"', '"Try again. −3"'),
    ('`Pomoć: riječ ima ${answer.length} slova. Prvo slovo je „${answer[0]}“.`', '`Hint: the word has ${answer.length} letters. The first letter is “${answer[0]}”.`'),
]
