T = [
    ('<title>Memori kviz – Allahova, dž.š., svojstva (sifati)</title>', '<title>Memory Quiz – Attributes of Allah (SWT) (sifat)</title>'),
    ('<h1>MEMORI KVIZ</h1>', '<h1>MEMORY QUIZ</h1>'),
    ('Allahova, dž.š., svojstva – SIFATI</div>', 'Attributes of Allah (SWT) – SIFAT</div>'),
    ('<div class="by">Pripremio: Abdo ef. Rekić</div>\n', ''),
    ('<div class="badge">Parovi:', '<div class="badge">Pairs:'),
    ('<div class="badge">Pokušaji:', '<div class="badge">Attempts:'),
    ('<div class="badge">Bodovi:', '<div class="badge">Points:'),
    ('Pronađi naziv sifata i njegovo značenje.', 'Find the name of each attribute (sifah) and its meaning.'),
    ('🔄 Nova igra', '🔄 New game'),
    ('Dodirni dvije kartice. Ako naziv sifata odgovara značenju, par ostaje otvoren.',
     'Tap two cards. If the name of the attribute matches its meaning, the pair stays open.'),
    ('["VUDŽUD","Allah postoji."]', '["WUJUD","Allah exists."]'),
    ('["KIDEM","Allah je oduvijek."]', '["QIDAM","Allah has always existed, with no beginning."]'),
    ('["BEKA","Allah je zauvijek."]', '["BAQA","Allah will exist forever, with no end."]'),
    ('["VAHDANIJJET","Allah je jedan."]', '["WAHDANIYYAH","Allah is One."]'),
    ('["MUHALEFETUN LIL-HAVADIS","Allah nije sličan ničemu što je stvoreno."]',
     '["MUKHALAFATUN LIL-HAWADITH","Allah is not like anything that has been created."]'),
    ('["KIJAMUN BI NEFSIHI","Allah sam po Sebi opstoji i ni o kome nije ovisan."]',
     '["QIYAMUN BI NAFSIHI","Allah exists by Himself and does not depend on anyone."]'),
    ('["HAJAT","Allah živi."]', '["HAYAT","Allah is Living."]'),
    ('["ILM","Allah sve zna."]', '["’ILM","Allah knows everything."]'),
    ('["SEM\'","Allah sve čuje."]', '["SAM’","Allah hears everything."]'),
    ('["BESAR","Allah sve vidi."]', '["BASAR","Allah sees everything."]'),
    ('["IRADET","Allah sve Svojom voljom čini."]', '["IRADAH","Allah does everything by His own will."]'),
    ('["KUDRET","Allah je svemoćan."]', '["QUDRAH","Allah is All-Powerful."]'),
    ('["KELAM","Allah govori Svojim govorom."]', '["KALAM","Allah speaks with His own speech."]'),
    ('["TEKVIN","Allah sve stvara, održava i rastvara."]', '["TAKWIN","Allah creates everything, sustains it and brings it to an end."]'),
    ('"Bravo! Pronašao/la si par. +10 bodova"', '"Well done! You found a pair. +10 points"'),
    ('`Mašallah! Završio/la si kviz sa ${score} bodova u ${tries} pokušaja!`', '`MashaAllah! You finished the quiz with ${score} points in ${tries} attempts!`'),
    ('"Nije par — pokušaj ponovo. −2 boda"', '"Not a pair — try again. −2 points"'),
]
