DELETE = [
    '<div class="mobile-credit">Pripremio Abdo ef. Rekić</div>',
    '<div class="credit">Pripremio Abdo ef. Rekić</div>',
]
T = [
    ('<title>Oslobodi papagaja!</title>', '<title>Free the Parrot!</title>'),
    ('<h1>OSLOBODI<br>PAPAGAJA!</h1>', '<h1>FREE<br>THE PARROT!</h1>'),
    ('Riješi sve memori prepreke i pomozi papagaju da bude slobodan!',
     'Solve all the memory obstacles and help the parrot go free!'),
    ('<p>Pronađi odgovarajuće parove.</p>', '<p>Find the matching pairs.</p>'),
    ('Pronađi prvi par.', 'Find the first pair.'),
    ('KAVEZ SE OTVARA<br>KORAK PO KORAK!', 'THE CAGE OPENS<br>STEP BY STEP!'),
    ('🔒 1. Mubarek-noći', '🔒 1. Blessed nights'),
    ('🔒 2. Vrste nafila-namaza', '🔒 2. Types of nafl (voluntary) prayers'),
    ('🔒 3. Pregled klanjanja', '🔒 3. How to pray'),
    ('title="Zvuk"', 'title="Sound"'),
    ('title="Ponovo"', 'title="Restart"'),
    ('<h1>Papagaj je slobodan!</h1>', '<h1>The parrot is free!</h1>'),
    ('<p>Mašallah! Riješene su sve tri memori prepreke.</p>', '<p>MashaAllah! You solved all three memory obstacles.</p>'),
    ('>Igraj ponovo<', '>Play again<'),
    ("'Tačan par!'", "'Correct pair!'"),
    # level 1
    ("'1. PREPREKA — VAŽNOST I ZNAČAJ MUBAREK-NOĆI'", "'OBSTACLE 1 — THE IMPORTANCE OF THE BLESSED NIGHTS'"),
    ("['LEJLETUL-KADR','27. noć ramazana']", "['LAYLAT AL-QADR','27th night of Ramadan']"),
    ("['LEJLETUL-MI‘RADŽ','27. noć redžeba']", "['LAYLAT AL-MI‘RAJ','27th night of Rajab']"),
    ("['LEJLETUL-BERAT','15. noć mjeseca ša‘bana']", "['LAYLAT AL-BARA’AH','15th night of the month of Sha‘ban']"),
    ("['LEJLETUR-REGAIB','Obilježava se uoči prvog petka u redžebu']",
     "['LAYLAT AR-RAGHA’IB','Marked on the eve of the first Friday of Rajab']"),
    ("['LEJLETU TERVIJJE','8. noć zul-hidždžeta']", "['LAYLAT AT-TARWIYAH','8th night of Dhul-Hijjah']"),
    ("['NAMAZ','Naređen na Miradžu']", "['SALAH (PRAYER)','Made obligatory on the night of the Mi‘raj']"),
    # level 2
    ("'2. PREPREKA — VRSTE NAFILA-NAMAZA'", "'OBSTACLE 2 — TYPES OF NAFL (VOLUNTARY) PRAYERS'"),
    ("['DUHA-NAMAZ','Vrijeme mu je od 45 minuta nakon izlaska Sunca do pred podne']",
     "['DUHA PRAYER','Its time is from 45 minutes after sunrise until just before noon']"),
    ("['SALATUL-LEJL','Noćni namaz']", "['SALAT AL-LAYL','The night prayer']"),
    ("['TEHIJJETUL-MESDŽID','Klanja se pri ulasku u džamiju']",
     "['TAHIYYAT AL-MASJID','Prayed when entering the mosque']"),
    ("['ISTIHARA-NAMAZ','Klanja se kada se dvoumimo u važnoj odluci']",
     "['ISTIKHARA PRAYER','Prayed when we cannot decide about something important']"),
    ("['SALATUL-HADŽE','Namaz za želju ili potrebu']", "['SALAT AL-HAJAH','Prayer for a wish or a need']"),
    ("['SALATUT-TEVBA','Namaz za pokajanje']", "['SALAT AT-TAWBAH','Prayer of repentance']"),
    ("['NAMAZ NAKON PUTOVANJA','Po povratku je lijepo klanjati dva rekata']",
     "['PRAYER AFTER A JOURNEY','When you return, it is good to pray two rak‘ahs']"),
    ("['SALATUL-ISTISKA','Namaz za kišu']", "['SALAT AL-ISTISQA','Prayer for rain']"),
    ("['SALATUL-KUSUF VEL-HUSUF','Namaz prilikom pomračenja Sunca i Mjeseca']",
     "['SALAT AL-KUSUF WAL-KHUSUF','Prayer during an eclipse of the Sun or the Moon']"),
    # level 3
    ("'3. PREPREKA — PREGLED KLANJANJA PET DNEVNIH NAMAZA'", "'OBSTACLE 3 — HOW TO PRAY THE FIVE DAILY PRAYERS'"),
    ("['PRVI REKAT','Subhaneke, Euzubilla, Bismilla, Fatiha i jedna sura']",
     "['FIRST RAK‘AH','Subhanaka, A‘udhu billah, Bismillah, Al-Fatiha and one surah']"),
    ("['DRUGI REKAT','Bismilla, Fatiha i jedna sura']", "['SECOND RAK‘AH','Bismillah, Al-Fatiha and one surah']"),
    ("['PRVO SJEDENJE','Et-Tehijjatu do Salavata']", "['FIRST SITTING','At-Tahiyyat up to the Salawat']"),
    ("['TREĆI I ČETVRTI REKAT FARZA','Bismilla i Fatiha']",
     "['THIRD AND FOURTH RAK‘AH OF THE FARD','Bismillah and Al-Fatiha']"),
    ("['PRVI REKAT BAJRAMA','Subhaneke, 3 tekbira, Bismilla, Fatiha i sura']",
     "['FIRST RAK‘AH OF THE EID PRAYER','Subhanaka, 3 takbirs, Bismillah, Al-Fatiha and a surah']"),
    ("['POSLJEDNJE SJEDENJE','Et-Tehijjatu, Salavati, dove i predaja selama']",
     "['LAST SITTING','At-Tahiyyat, Salawat, duas and ending with salam']"),
    ("['TREĆI REKAT VITRA','Bismilla, Fatiha, sura, tekbir i Kunut-dova']",
     "['THIRD RAK‘AH OF WITR','Bismillah, Al-Fatiha, a surah, takbir and the Qunut dua']"),
]
