# pomozimo-maci-abdest: table mode.
T = [
    ('<title>Pomozimo maci da uzme abdest</title>', '<title>Let’s Help the Kitty Make Wudu</title>'),
    ('aria-label="Zvuk"', 'aria-label="Sound"'),
    ('<span class="collectedLabel">SAKUPLJENO:</span></div><div id="hud">BODOVI',
     '<span class="collectedLabel">COLLECTED:</span></div><div id="hud">POINTS'),
    ('<div class="progress" id="progress">Korak 0 / 13</div>', '<div class="progress" id="progress">Step 0 / 13</div>'),
    ('▶ ZAPOČNI IGRU', '▶ START GAME'),
    ("{text:'Euza, bismilla i nijet'", "{text:'A’udhu, Bismillah and niyyah'"),
    ("{text:'Šake 3x'", "{text:'Hands 3x'"),
    ("{text:'Usta 3x'", "{text:'Mouth 3x'"),
    ("{text:'Nos 3x'", "{text:'Nose 3x'"),
    ("{text:'Lice 3x'", "{text:'Face 3x'"),
    ("{text:'Desnu ruku do iza laktova 3x'", "{text:'Right arm past the elbow 3x'"),
    ("{text:'Lijevu ruku do iza laktova 3x'", "{text:'Left arm past the elbow 3x'"),
    ("{text:'Mesh'", "{text:'Masah (wipe the head)'"),
    ("{text:'Uši'", "{text:'Ears'"),
    ("{text:'Vrat'", "{text:'Neck'"),
    ("{text:'Desnu nogu do članaka'", "{text:'Right foot up to the ankle'"),
    ("{text:'Lijevu nogu do članaka'", "{text:'Left foot up to the ankle'"),
    ("{text:'Kelimei-šehadet'", "{text:'Shahadah'"),
    ("prog.textContent='Korak '+next+' / 13'", "prog.textContent='Step '+next+' / 13'"),
    ("msg.innerHTML='🎉 Bravo! Maca je pravilno uzela abdest!<br>Osvojeno: '+score+' bodova 🐾'",
     "msg.innerHTML='🎉 Well done! The kitty made Wudu the right way!<br>You earned: '+score+' points 🐾'"),
    ("start.textContent='↻ IGRAJ PONOVO'", "start.textContent='↻ PLAY AGAIN'"),
    ("collected.innerHTML='<span class=\"collectedLabel\">SAKUPLJENO:</span>'",
     "collected.innerHTML='<span class=\"collectedLabel\">COLLECTED:</span>'"),
    ("prog.textContent='Korak 0 / 13'", "prog.textContent='Step 0 / 13'"),
]
