T = [
    ('<title>Sifati – Pronađi riječ</title>', '<title>Sifat – Word Search</title>'),
    ('<h1>PRONAĐI RIJEČ – SIFATI</h1>', '<h1>WORD SEARCH – SIFAT</h1>'),
    ('<div>Allahova svojstva</div>', '<div>Attributes of Allah (sifat)</div>'),
    ('<span>Zadatak <b', '<span>Task <b'), ('Bodovi: <b', 'Points: <b'),
    ('💡 Pomoć −2', '💡 Hint −2'), ('↻ Nova igra', '↻ New game'),
    ('<div class="foot">Pripremio Abdo ef. Rekić</div>', ''),
    ('["VUDZUD","Allah postoji."]', '["WUJUD","Allah exists."]'),
    ('["KIDEM","Allah je oduvijek; Njegovom postojanju nema početka."]', '["QIDAM","Allah has always existed; His existence has no beginning."]'),
    ('["BEKA","Allah je zauvijek; Njegovom postojanju nema kraja."]', '["BAQA","Allah exists forever; His existence has no end."]'),
    ('["MUHALEFETUNLILHAVADISI","Allah nije ničemu sličan."]', '["MUKHALAFATUNLILHAWADITH","Allah is not like anything (He created)."]'),
    ('["KIJAMUNBINEFSIHI","Allah sam po Sebi opstoji."]', '["QIYAMUNBINAFSIHI","Allah exists by Himself and needs nothing."]'),
    ('["VAHDANIJJET","Allah je Jedan."]', '["WAHDANIYYAH","Allah is One."]'),
    ('["SIFATUZZATIJJE","Naziv za šest svojstava: Vudžud, Kidem, Beka, Muhalefetun lil-havadisi, Kijamun bi nefsihi i Vahdanijjet."]',
     '["SIFATUDHDHATIYYAH","The name for these six attributes: Wujud, Qidam, Baqa, Mukhalafatun lil-hawadith, Qiyamun bi nafsihi and Wahdaniyyah."]'),
    ('["HAJAT","Allah živi Svojim vječnim životom."]', '["HAYAT","Allah is Living, with His eternal life."]'),
    ('["ILM","Allah sve zna."]', '["ILM","Allah knows everything."]'),
    ('["SEM","Allah sve čuje."]', '["SAM","Allah hears everything."]'),
    ('["BESAR","Allah sve vidi."]', '["BASAR","Allah sees everything."]'),
    ('["IRADET","Allah sve Svojom voljom čini."]', '["IRADAH","Allah does everything by His will."]'),
    ('["KUDRET","Allah je Svemoćan."]', '["QUDRAH","Allah is All-Powerful."]'),
    ('["KELAM","Allah govori Svojim božanskim govorom."]', '["KALAM","Allah speaks with His divine speech."]'),
    ('["TEKVIN","Allah sve stvara, održava i rastvara."]', '["TAKWIN","Allah creates everything, sustains it and brings it to an end."]'),
    ('["SIFATUSSUBUTIJJE","Naziv za svojstva: Hajat, Ilm, Sem\', Besar, Iradet, Kudret, Kelam i Tekvin."]',
     '["SIFATUTHTHUBUTIYYAH","The name for these attributes: Hayat, Ilm, Sam’, Basar, Iradah, Qudrah, Kalam and Takwin."]'),
    ('"Bravo! Završio/la si igru."', '"Well done! You finished the game."'),
    ('"Ukupno bodova: "', '"Total points: "'),
    ('"Dodirni prvo slovo, pa posljednje slovo riječi."', '"Tap the first letter, then the last letter of the word."'),
    ('>Dodirni prvo slovo, pa posljednje slovo riječi.<', '>Tap the first letter, then the last letter of the word.<'),
    ('"Sada dodirni posljednje slovo riječi."', '"Now tap the last letter of the word."'),
    ('"✓ Tačno! +10"', '"✓ Correct! +10"'),
    ('"Pokušaj ponovo. −3"', '"Try again. −3"'),
    ('"Riječ ima "+answer.length+" slova. Počinje slovom „"+answer.charAt(0)+"“."', '"The word has "+answer.length+" letters. It starts with “"+answer.charAt(0)+"”."'),
]
