# English translations of the quiz BANK in sta-radi-masa, questions 164-326 and 462-502
# (questions 327-461 repeat earlier questions word for word and reuse these translations).
Q = {
164: ("What is the sacred area around the Ka’bah called?", ["Al-Masjid al-Aqsa", "Al-Haram ash-Sharif", "Rawdah", "Mina"]),
165: ("What do Muslims do around the Ka’bah during Hajj?", ["They only call the Adhan", "They only sit and rest", "They pray, recite the Qur’an and do tawaf", "They only pray Fajr"]),
166: ("In which direction is the Qiblah from Bosnia?", ["East", "South", "Northwest", "Southeast"]),
167: ("What should we do if we don’t know which direction the Qiblah is?", ["Try to find out, then face the direction we think is the Qiblah", "Not pray Salah", "Always face east", "Face the nearest window"]),
168: ("What is it not allowed to face on purpose when praying?", ["A wall", "Figures, or a picture or photo of a person or an animal", "A door", "A window"]),
169: ("Which device can we use to find the direction of the Qiblah?", ["A thermometer", "A calculator", "A compass or a GPS device", "A weighing scale"]),
170: ("What on a mobile phone can show us the exact direction of the Qiblah?", ["The camera", "The photo gallery", "The calculator", "A Qiblah-finder app"]),
171: ("With a Qiblah clock, what shows the direction of the Qiblah?", ["The direction opposite the shadow of the object we look at", "The direction of the shadow itself", "Always the direction of sunrise", "Always the direction of north"]),
172: ("On which side of a tree are the branches and leaves fuller?", ["On the north side", "On the south side", "On the east side", "On the west side"]),
173: ("On which side of a tree is the bark rougher and covered with moss?", ["On the south side", "On the east side", "On the north side", "On the west side"]),
174: ("On which side of a tree stump, stone or bush can we find an anthill?", ["On the north side", "On the west side", "On the east side", "On the south side"]),
175: ("Which surah is the last surah in the Qur’an?", ["An-Nas", "Al-Falaq", "Al-Ikhlas", "Al-Kawthar"]),
176: ("How does Surah An-Nas begin?", ["Allahus-Samad", "Qul a’udhu birabbin-nas", "Qul huwallahu ahad", "Min sharri ma khalaq"]),
177: ("What does “Qul a’udhu birabbin-nas” mean?", ["Say: Allah is One", "Say: Praise be to Allah", "Say: I seek refuge in the Lord of daybreak", "Say: I seek refuge in the Lord of mankind"]),
178: ("What is the second ayah of Surah An-Nas?", ["Malikin-nas", "Ilahin-nas", "Minal-jinnati wan-nas", "Min sharril-waswasil-khannas"]),
179: ("What does “Malikin-nas” mean?", ["The Lord of mankind", "The King of mankind", "The Protector of mankind", "The Creator of the heavens"]),
180: ("What is the third ayah of Surah An-Nas?", ["Malikin-nas", "Minal-jinnati wan-nas", "Ilahin-nas", "Fi sudurin-nas"]),
181: ("What does “Ilahin-nas” mean?", ["The Lord of mankind", "The King of mankind", "The Protector of mankind", "The God of mankind"]),
182: ("In Surah An-Nas, from whose evil do we seek Allah’s protection?", ["From the evil of Shaytan – the whisperer", "From the cold", "From animals", "From travelling"]),
183: ("Where does Shaytan put evil thoughts?", ["Into people’s houses", "Into people’s hearts", "Into their clothes", "Into their books"]),
184: ("How does Surah An-Nas end?", ["Wa min sharri hasidin idha hasad", "Allahus-Samad", "Minal-jinnati wan-nas", "Lam yalid wa lam yulad"]),
185: ("Who can the evil thoughts mentioned at the end of Surah An-Nas come from?", ["Only from people", "Only from the jinn", "Only from Shaytan", "From the jinn and from people"]),
186: ("What does “A’udhu billahi minash-shaytanir-rajim” mean?", ["I seek Allah’s protection from the accursed Shaytan", "In the name of Allah, the Most Gracious, the Most Merciful", "Praise be to Allah, Lord of the worlds", "Allah is One"]),
187: ("What are the conditions of Salah (shurut)?", ["Requirements we must meet for our Salah to be valid", "Voluntary parts of Salah", "Duas after Salah", "Kinds of Salah"]),
188: ("How many conditions of Salah are there in total?", ["6", "10", "12", "14"]),
189: ("How are the conditions of Salah divided?", ["Into four conditions and eight pillars", "Into six conditions of Salah and six pillars of Salah", "Into five conditions and seven pillars", "Into three conditions and nine pillars"]),
190: ("What do we call the six conditions before praying Salah?", ["The pillars of Salah", "The fard acts of Wudu", "The Sunnah acts of Salah", "The preconditions of Salah, or getting ready for Salah"]),
191: ("How many preconditions – ways of getting ready for Salah – are there?", ["6", "5", "7", "12"]),
192: ("How many pillars (arkan) of Salah are there?", ["4", "6", "8", "12"]),
193: ("What is the first precondition of Salah?", ["Facing the Qiblah", "Making the intention", "That the body, the clothes and the place of prayer are clean", "Praying on time"]),
194: ("What is the second precondition of Salah?", ["Being properly dressed", "Facing the Qiblah", "Making the intention", "Making Wudu or, when needed, taking a Ghusl or making Tayammum"]),
195: ("What is the third precondition of Salah?", ["Being properly dressed", "Praying on time", "Making the intention", "Making Wudu"]),
196: ("What is the fourth precondition of Salah?", ["Facing the Qiblah", "Praying on time", "Making the intention", "Being properly dressed"]),
197: ("What is the fifth precondition of Salah?", ["Making Wudu", "Being properly dressed", "Facing the Qiblah", "Making the intention"]),
198: ("What is the sixth precondition of Salah?", ["Praying on time", "Making Wudu", "Facing the Qiblah", "Making the intention – deciding to pray the Salah"]),
199: ("What does making the intention for Salah mean?", ["Deciding to pray the Salah", "Making Wudu", "Facing the Qiblah", "Calling the Adhan"]),
200: ("What can we do if, when needed, we cannot make Wudu?", ["Skip the Salah", "Make Tayammum", "Only wash our hands", "Pray without any preparation"]),
201: ("What do we call the six conditions during Salah?", ["The preconditions of Salah", "Sunnah acts", "The pillars of Salah, or the main parts of Salah", "Duas"]),
202: ("What is the first pillar of Salah?", ["Qiyam", "Ruku’", "Sajdah", "Takbirat al-iftitah – the opening takbir"]),
203: ("What is the takbirat al-iftitah?", ["The opening takbir", "Standing in Salah", "Bowing in Salah", "Sitting at the end of Salah"]),
204: ("What is the second pillar of Salah?", ["Qira’ah", "Qiyam", "Sajdah", "Ruku’"]),
205: ("What does qiyam mean?", ["Reciting the Qur’an", "Bowing", "Standing in Salah", "Sitting"]),
206: ("What is the third pillar of Salah?", ["Ruku’", "Sajdah", "Qiyam", "Qira’ah"]),
207: ("What is qira’ah?", ["Reciting the Qur’an in Salah", "Standing in Salah", "Putting the face down to the ground", "Sitting at the end of Salah"]),
208: ("What is the fourth pillar of Salah?", ["Sajdah", "Ruku’", "Qiyam", "Qira’ah"]),
209: ("What is ruku’?", ["Sitting at the end of Salah", "Reciting the Qur’an", "Bowing in Salah", "The opening takbir"]),
210: ("What is the fifth pillar of Salah?", ["Qiyam", "Qira’ah", "Ruku’", "Sajdah"]),
211: ("What is sajdah?", ["Putting the face down to the ground", "Standing in Salah", "Bowing in Salah", "The opening takbir"]),
212: ("What is the sixth pillar of Salah?", ["Qiyam", "Qa’dah akhirah", "Qira’ah", "Sajdah"]),
213: ("What does qa’dah akhirah mean?", ["The opening takbir", "Bowing in Salah", "Sitting at the end of Salah", "Reciting the Qur’an"]),
214: ("What is the correct order of the first three pillars of Salah?", ["Qiyam, ruku’, sajdah", "Qira’ah, qiyam, ruku’", "Sajdah, qiyam, qira’ah", "Takbirat al-iftitah, qiyam, qira’ah"]),
215: ("What is the correct order of the last three pillars of Salah?", ["Ruku’, sajdah, qa’dah akhirah", "Sajdah, ruku’, qiyam", "Qira’ah, sajdah, ruku’", "Qiyam, ruku’, sajdah"]),
216: ("When is a Salah not valid?", ["If it is prayed in the mosque", "Without meeting all the conditions of Salah", "If the Qur’an is recited", "If it is prayed on time"]),
217: ("What is the sixth condition of Salah?", ["Facing the Qiblah", "Making the intention – deciding to pray the Salah", "Making Wudu", "Dressing properly"]),
218: ("What is niyyah (intention)?", ["A conscious decision in the heart about why we do something", "Calling the Adhan", "Facing the Qiblah", "Making Wudu"]),
219: ("What should we be aware of before Salah?", ["How long the Salah lasts", "Who is next to us", "Which Salah we want to pray", "Who called the Adhan"]),
220: ("What did Muhammad, alayhis-salam, say about deeds and intentions?", ["Deeds are judged by wealth", "Deeds are judged by knowledge", "Deeds are judged by time", "Deeds are judged by intentions, and every person gets what he intended"]),
221: ("How can we strengthen and confirm the intention by saying it?", ["We can strengthen the decision in our heart by saying the words of the intention", "By calling the Adhan", "By saying the Iqamah", "By turning towards the Qiblah"]),
222: ("Does every Salah have its own intention?", ["Only Fajr has its own intention", "Yes, every Salah has its own intention", "Only the fard prayers have an intention", "No, all prayers have the same intention"]),
223: ("Who should we think of when saying the intention?", ["The other people praying", "The muezzin", "Allah, the Most High", "Our chores"]),
224: ("Which Companion of the Prophet dreamed of a man in green clothes?", ["Bilal", "Abdullah", "Umar", "Uthman"]),
225: ("In the dream, what did Abdullah want to buy from the man?", ["A green suit", "A book", "A bell", "A sword"]),
226: ("What did Abdullah want to use the bell for?", ["To announce the prayer time and call people to prayer in the mosque", "To call people to lunch", "To start the lesson", "To wake up the children"]),
227: ("What did the man in the dream suggest to Abdullah instead of a bell?", ["To light a lamp", "To beat a drum", "To raise a flag", "To teach him something more beautiful – the Adhan"]),
228: ("Who did Abdullah tell about his dream?", ["Muhammad, alayhis-salam", "Only his family", "Abu Bakr", "His friend"]),
229: ("What did Muhammad, alayhis-salam, say about Abdullah’s dream?", ["To forget it", "That the dream was true", "Not to tell anyone about it", "To go back to sleep"]),
230: ("Who was Abdullah supposed to go to and teach the words of the Adhan?", ["Umar", "Ali", "Bilal", "Uthman"]),
231: ("Why was Bilal chosen to call the Adhan?", ["Because he was the oldest", "Because he lived near the mosque", "Because he heard about the dream first", "Because he had a beautiful voice"]),
232: ("When does Allah, the Most High, give special mercy?", ["When the muezzin calls the Adhan", "When it is raining", "When people travel", "When children study"]),
233: ("What should we do when we hear the Adhan?", ["Talk loudly", "Stop what we are doing and get ready for Salah", "Keep working without stopping", "Leave the mosque"]),
234: ("What do we repeat after the muezzin while he calls the Adhan?", ["Only the takbir", "Only the shahadah", "The words of the Adhan", "Only the last sentence"]),
235: ("What do we say when the muezzin calls “Hayya ‘alas-salah” and “Hayya ‘alal-falah”?", ["Subhanallah", "Alhamdulillah", "Allahu akbar", "La hawla wa la quwwata illa billahil-‘aliyyil-‘azim"]),
236: ("When do we say the dua after the Adhan?", ["When the muezzin finishes calling the Adhan", "Before the Adhan starts", "In the middle of the Adhan", "After the Salah is finished"]),
237: ("With which words does the dua after the Adhan begin?", ["Rabbana atina", "Allahumma Rabba hadhihid-da’watit-tammah", "Subhanaka Allahumma", "A’udhu billahi minash-shaytanir-rajim"]),
238: ("In the dua after the Adhan, who do we ask a special rank in Jannah for?", ["For the muezzin", "For all people", "For Muhammad, alayhis-salam", "For those praying behind the imam"]),
239: ("After the Adhan, what do we ask Allah to give Muhammad, alayhis-salam?", ["Only a long life", "Great riches", "Many followers", "A special rank in Jannah and every good"]),
240: ("How does the translation of the dua after the Adhan end?", ["“You see everything and know everything!”", "“Truly, You never break a promise!”", "“You are the Most Gracious, the Most Merciful!”", "“You are the Lord of all people!”"]),
241: ("What is the Adhan?", ["A dua after Salah", "The announcement that a prayer time has begun", "Reciting the Qur’an before Salah", "A greeting after Salah"]),
242: ("Who calls the Adhan?", ["The muezzin", "The khatib", "Everyone praying at the same time", "Only the imam"]),
243: ("How do we behave when we hear the Adhan?", ["We keep talking", "We say some other dua", "We stop all talking and work, listen, and repeat the words of the Adhan quietly", "We start praying right away"]),
244: ("With which words does the Adhan begin?", ["La ilaha illallah", "Hayya ‘alas-salah", "Ash-hadu an la ilaha illallah", "Allahu akbar"]),
245: ("What does “Allahu akbar” mean?", ["Allah is the Greatest", "Only Allah is God", "Come to prayer", "Come to success"]),
246: ("What does “Ash-hadu an la ilaha illallah” mean?", ["Muhammad is Allah’s Messenger", "I bear witness that only Allah is God", "Allah is the Greatest", "Come to success"]),
247: ("What does “Ash-hadu anna Muhammadan rasulullah” mean?", ["Come to prayer", "Only Allah is God", "I bear witness that Muhammad is Allah’s Messenger", "Prayer is better than sleep"]),
248: ("What does “Hayya ‘alas-salah” mean?", ["Come to success", "Allah is the Greatest", "The prayer is starting now", "Come to prayer"]),
249: ("What does “Hayya ‘alal-falah” mean?", ["Come to success", "Come to prayer", "The prayer is starting now", "Allah is the Greatest"]),
250: ("With which words does the Adhan end?", ["Allahu akbar", "La ilaha illallah", "Hayya ‘alal-falah", "Ash-hadu an la ilaha illallah"]),
251: ("What is added especially in the Fajr Adhan?", ["Qad qamatis-salah", "Hayya ‘alas-salah", "As-salatu khayrun minan-nawm", "Subhanallah"]),
252: ("How many times is “As-salatu khayrun minan-nawm” added in the Fajr Adhan?", ["Once", "Three times", "Four times", "Twice"]),
253: ("What does “As-salatu khayrun minan-nawm” mean?", ["Prayer is better than sleep", "The prayer is starting now", "Come to success", "Allah is the Greatest"]),
254: ("Who says the Iqamah before praying a fard Salah?", ["Only children", "Men", "Only the imam", "Only the khatib"]),
255: ("When is the Iqamah said?", ["After the Salah is finished", "Before the Adhan", "Before praying a fard Salah", "Only after Fajr"]),
256: ("Who says the Iqamah when we pray in congregation (jama’ah)?", ["Everyone praying", "The imam", "The khatib", "The muezzin"]),
257: ("How fast do we say the Iqamah compared to the Adhan?", ["A little faster than the Adhan", "Much slower than the Adhan", "At exactly the same speed", "The Iqamah is not said out loud"]),
258: ("Which words are added in the Iqamah that are not in the Adhan?", ["As-salatu khayrun minan-nawm", "Qad qamatis-salah", "Subhana rabbiyal-‘azim", "Sami’allahu liman hamidah"]),
259: ("What does “Qad qamatis-salah” mean?", ["Come to prayer", "Prayer is better than sleep", "The prayer is starting now", "Come to success"]),
260: ("What is the main difference between the Adhan and the Iqamah?", ["The Adhan is called only for Fajr", "The Iqamah is said after Salah", "The Adhan is called before Salah", "In the Iqamah the words “Qad qamatis-salah” are added"]),
261: ("What is the third condition of Salah?", ["Making Wudu", "Dressing properly", "Praying on time", "Facing the Qiblah"]),
262: ("What do we protect with our clothes?", ["Only our body from the cold", "Only our health", "Our body and our modesty", "Only our body from dirt"]),
263: ("What should our clothes always be like?", ["Expensive and new", "Only white", "Colourful and loose", "Nice, clean and tidy"]),
264: ("What kind of clothes should we not wear?", ["Clean and tidy", "Short, tight and see-through", "Nice and comfortable", "Modest and clean"]),
265: ("When must we especially dress properly?", ["When we pray Salah", "When we sleep", "When we travel", "When we play"]),
266: ("Who do we stand before when we pray Salah?", ["Before the imam", "Before people", "Before our Lord", "Before our parents"]),
267: ("What must girls and women cover in Salah?", ["Only the hair", "Only the legs", "Only the arms and legs", "The whole body except the face, hands and feet"]),
268: ("How should men be dressed?", ["Modestly", "Only in white", "Only in long clothes", "Only in new clothes"]),
269: ("What part of the body must men cover at the very least?", ["From the shoulders to the feet", "From the waist to below the knees", "Only the knees", "From the neck to the ankles"]),
270: ("What kind of clothes must not be worn in Salah?", ["Clean", "Tidy", "Comfortable", "See-through"]),
271: ("Which of these must clothes for Salah also not be?", ["Dirty (impure)", "Clean", "Nice", "Tidy"]),
272: ("Which clothes are not suitable for Salah?", ["Comfortable", "Tight", "Clean", "Tidy"]),
273: ("What should clothes for Salah not have?", ["Buttons", "Sleeves", "A picture", "Pockets"]),
274: ("What is the second condition of Salah?", ["Wudu", "Intention", "Facing the Qiblah", "Clean clothes"]),
275: ("What is Wudu?", ["Washing the whole body", "Washing certain parts of the body for worship", "Washing only the hands", "Washing clothes"]),
276: ("Why do we make Wudu?", ["Only to be clean", "Only before sleeping", "To pray Salah, recite the Qur’an and do other acts of worship", "Only before eating"]),
277: ("How do we begin making Wudu?", ["Only with the intention", "Only with the Bismillah", "By washing the hands", "With the A’udhu billah, the Bismillah and the intention"]),
278: ("What kind of water do we use for Wudu?", ["Clean water", "Only salty water", "Juice", "Perfumed water"]),
279: ("What do we wash first when making Wudu?", ["The face", "The hands, up to above the wrists", "The feet", "The ears"]),
280: ("How many times at the start do we wash our hands up to above the wrists?", ["Once", "Twice", "Three times", "Four times"]),
281: ("Which hand do we use to rinse the mouth?", ["The left", "Both at the same time", "It doesn’t matter", "The right"]),
282: ("How many times do we rinse the mouth?", ["Three times", "Once", "Twice", "Five times"]),
283: ("What can we clean our teeth with when making Wudu?", ["Only water", "A toothbrush or a miswak", "A towel", "Soap"]),
284: ("How many times do we rinse the nose?", ["Once", "Twice", "Three times", "Four times"]),
285: ("How many times do we wash the face in the usual way of making Wudu?", ["Once", "Twice", "Four times", "Three times"]),
286: ("Which arm do we wash first up to above the elbow?", ["The right", "The left", "Both together", "It doesn’t matter"]),
287: ("How many times do we wash the right arm up to above the elbow?", ["Once", "Three times", "Twice", "Four times"]),
288: ("What do we wash after the right arm?", ["The feet", "The face", "The left arm, up to above the elbow", "The ears"]),
289: ("What does masah mean?", ["Washing the feet", "Rinsing the nose", "Washing the face", "Wiping at least a quarter of the head with a wet hand"]),
290: ("At least how much of the head do we wipe with a wet hand?", ["At least a quarter of the head", "Half of the head", "The whole head, always", "Only the forehead"]),
291: ("What do we wipe after the masah of the head?", ["The neck", "The ears, inside and outside", "The feet", "The face"]),
292: ("How is the neck wiped?", ["Three times with the palms", "With a wet cloth", "Once with the backs of the fingers", "It is neither washed nor wiped"]),
293: ("What is it nice to say after making Wudu?", ["The Kalimat ash-Shahadah", "The Adhan", "The Iqamah", "Only Al-Fatihah"]),
294: ("What are the required acts of Wudu called?", ["The pillars of Salah", "The conditions or fard acts of Wudu", "The pillars of Islam", "The pillars of Iman (faith)"]),
295: ("How many conditions – fard acts – of Wudu are there?", ["Three", "Five", "Four", "Six"]),
296: ("What happens if we don’t do the fard acts of Wudu?", ["The Wudu is still complete", "Only the reward is smaller", "We only need to say a dua", "The Wudu is not valid"]),
297: ("What is the first fard act of Wudu?", ["Washing the face once", "Washing the feet", "Wiping the head", "Washing the hands"]),
298: ("What is the second fard act of Wudu?", ["Rinsing the mouth", "Washing the right and left arms up to above the elbows, once each", "Rinsing the nose", "Wiping the ears"]),
299: ("What is the third fard act of Wudu?", ["Washing the face three times", "Washing the feet", "Wiping at least a quarter of the head with a wet hand – masah", "Washing the ears"]),
300: ("What is the fourth fard act of Wudu?", ["Washing the hands up to the wrists", "Rinsing the nose", "Wiping the neck", "Washing the right and left feet up to above the ankles, once each"]),
301: ("Which of these breaks Wudu?", ["Sleeping, or losing consciousness even for a moment", "Reciting the Qur’an", "Washing the hands", "Sitting"]),
302: ("Does blood or another fluid flowing out of the body break Wudu?", ["No, never", "Yes", "Only during Salah", "Only at night"]),
303: ("What happens to Wudu if a person vomits from the stomach?", ["We don’t have to redo the Wudu", "Nothing changes", "The Wudu is broken", "Only the Salah is broken"]),
304: ("Which of these breaks Wudu?", ["Talking quietly", "Walking", "Drinking water", "Going to the toilet"]),
305: ("Which of these breaks Wudu during Salah?", ["Laughing out loud in Salah", "Reciting the Qur’an", "Standing", "Sajdah"]),
306: ("How many prayers can we pray with one Wudu?", ["Only one", "Several prayers, as long as nothing happens that breaks the Wudu", "Two at most", "Only the fard of one prayer"]),
307: ("Which ayah of the Qur’an talks about the fard acts of Wudu?", ["Al-Fatihah, 1", "Al-Ikhlas, 1", "Al-Baqarah, 255", "Al-Ma’idah, 6"]),
308: ("Who were Hasan and Husayn (RA)?", ["The sons of Ali and Fatimah (RA) and grandsons of Muhammad, alayhis-salam", "Messengers of Allah", "Muezzins", "Teachers at a madrasa"]),
309: ("What did Hasan and Husayn notice about a man who was making Wudu?", ["That he had not called the Adhan", "That he was not doing it correctly", "That he had not prayed Salah", "That he had no water"]),
310: ("How did Hasan and Husayn teach the man the correct way to make Wudu?", ["They scolded him in front of everyone", "They said nothing to him", "They asked him to judge which of the two of them made Wudu more beautifully, correctly and quickly", "They sent him to another man"]),
311: ("What did the man say to Hasan and Husayn after watching them make Wudu?", ["That they had to redo their Wudu", "That only one of them had made Wudu correctly", "That he did not understand them", "“Dear children, may Allah reward you, you have taught me how to make Wudu.”"]),
312: ("What is the first condition of Salah?", ["Making Wudu", "Facing the Qiblah", "Clean body, clothes and place of prayer", "Intention"]),
313: ("When should we pay special attention to cleanliness?", ["When we travel", "When we sleep", "When we eat", "When we pray"]),
314: ("What did Muhammad, alayhis-salam, say about cleanliness?", ["“Cleanliness is part of Salah.”", "“Cleanliness is half of faith (iman).”", "“Cleanliness is only a recommendation.”", "“Cleanliness is only for Salah.”"]),
315: ("Who recorded the hadith “Cleanliness is half of faith”?", ["Muslim", "Tirmidhi", "Abu Dawud", "Nasa’i"]),
316: ("How do we keep our body clean?", ["Only by bathing", "Only by washing our hands", "With personal hygiene", "Only by making Wudu"]),
317: ("Which of these helps keep the body clean?", ["Bathing regularly", "Wearing the same clothes", "Not washing our hands", "Rarely brushing our teeth"]),
318: ("How should we try to keep our clothes?", ["Always new", "Expensive", "Colourful", "Tidy and clean"]),
319: ("What should we especially keep our clothes safe from?", ["From rain and snow", "From alcohol, blood, urine, dog saliva and similar impurities", "From dust on the street", "From moths"]),
320: ("What has Allah, the Most Merciful, made a place for prayer?", ["Only mosques", "Only the home", "The whole Earth", "Only masjids"]),
321: ("What should a place for Salah be like?", ["Big and roomy", "Decorated", "Well lit", "Clean and tidy"]),
322: ("How do we make sure the place where we pray is clean?", ["Only by laying down a prayer mat", "By removing all visible and invisible impurities", "Only by washing the floor", "By burning incense"]),
323: ("What can we use to be more sure the place where we pray is clean?", ["A prayer mat (sajjadah)", "A pillow", "A chair", "A hand towel"]),
324: ("What is a sajjadah?", ["Clothes for Salah", "A cap for Salah", "A special mat for Salah", "A jug for Wudu"]),
325: ("What must not be at the place where we pray?", ["A prayer mat", "Clean clothes", "A clean floor", "Pictures, figures of living beings or anything that distracts the person praying"]),
326: ("Which three kinds of cleanliness does the first condition of Salah include?", ["Clean hands, face and feet", "Clean body, clothes and place of prayer", "Clean house, mosque and yard", "Clean water, food and dishes"]),
462: ("What are the pillars of Iman (faith)?", ["Six basic truths of faith", "The five daily prayers", "The rules of Wudu", "Islamic holidays"]),
463: ("How many pillars of Iman are there?", ["Four", "Five", "Six", "Seven"]),
464: ("What does iman mean?", ["Salah", "Islamic belief", "Fasting", "Dua"]),
465: ("What do we often say, believing it firmly?", ["The takbir", "The Adhan", "Salam", "The pillars of Iman"]),
466: ("What is the first pillar of Iman?", ["Amantu billahi", "Wa mala’ikatihi", "Wa kutubihi", "Wa rusulihi"]),
467: ("What does “Amantu billahi” mean?", ["I believe in the angels", "I believe in Allah", "I believe in the Day of Judgement", "I believe in Allah’s books"]),
468: ("Which basis of belief is listed first?", ["Belief in the angels", "Belief in the messengers", "Belief in Allah", "Belief in the Day of Judgement"]),
469: ("What is the second pillar of Iman?", ["Wa kutubihi", "Wa rusulihi", "Wal-yawmil-akhiri", "Wa mala’ikatihi"]),
470: ("What does “Wa mala’ikatihi” mean?", ["And Allah’s angels", "And Allah’s books", "And Allah’s messengers", "And the Day of Judgement"]),
471: ("Who do we believe in with the second pillar of Iman?", ["In the messengers", "In Allah’s angels", "In the books", "In the Day of Judgement"]),
472: ("What is the third pillar of Iman?", ["Wa mala’ikatihi", "Wa rusulihi", "Wa kutubihi", "Wal-yawmil-akhiri"]),
473: ("What does “Wa kutubihi” mean?", ["Belief in Allah", "Belief in the angels", "Belief in the messengers", "Belief in Allah’s books – revelations"]),
474: ("Which pillar of Iman is about Allah’s books – revelations?", ["The third", "The first", "The fifth", "The sixth"]),
475: ("What is the fourth pillar of Iman?", ["Wa kutubihi", "Wa rusulihi", "Wa mala’ikatihi", "Wal-yawmil-akhiri"]),
476: ("What does “Wa rusulihi” mean?", ["And Allah’s books", "And the Day of Judgement", "And Allah’s messengers", "And Allah’s angels"]),
477: ("Which pillar of Iman, in order, is about Allah’s messengers?", ["The second", "The third", "The fifth", "The fourth"]),
478: ("What is the fifth pillar of Iman?", ["Wal-yawmil-akhiri", "Wa rusulihi", "Wa kutubihi", "Wa mala’ikatihi"]),
479: ("What does “Wal-yawmil-akhiri” mean?", ["I believe in the angels", "And the Day of Judgement", "I believe in the books", "I believe in the messengers"]),
480: ("Which pillar of Iman is about the Day of Judgement?", ["The third", "The fourth", "The fifth", "The sixth"]),
481: ("What do we believe in with the fifth pillar of Iman?", ["In Allah’s books", "In the angels", "In the messengers", "In the Day of Judgement"]),
482: ("What is the last pillar of Iman?", ["Belief that everything happens by Allah’s will and decree", "Belief in the angels", "Belief in Allah’s books", "Belief in the messengers"]),
483: ("How does the sixth pillar of Iman begin?", ["Wa rusulihi", "Wa bil-qadari", "Wa kutubihi", "Wal-yawmil-akhiri"]),
484: ("What does the sixth pillar of Iman teach us?", ["To believe only in the angels", "To believe only in the revelations", "That everything happens by Allah’s will and decree", "To believe only in the messengers"]),
485: ("Which pillar is “Wa bil-qadari khayrihi wa sharrihi minallahi ta’ala”?", ["The third", "The fourth", "The fifth", "The sixth"]),
486: ("What comes after belief in Allah’s books?", ["Belief in the Day of Judgement", "Belief in Allah’s messengers", "Belief in the angels", "Belief in qadar (divine decree)"]),
487: ("What comes right before belief in the Day of Judgement?", ["Belief in qadar (divine decree)", "Belief in the angels", "Belief in Allah’s messengers", "Belief in Allah"]),
488: ("What comes after belief in the Day of Judgement?", ["Belief in the angels", "Belief in the books", "Belief in the messengers", "Belief that everything happens by Allah’s will and decree"]),
489: ("Which list correctly names all six pillars of Iman?", ["Allah, angels, books, messengers, the Day of Judgement, Allah’s will and decree", "Allah, books, angels, the Day of Judgement, messengers, Salah", "Angels, Allah, messengers, books, fasting, qadar", "Allah, angels, Salah, fasting, Zakah, Hajj"]),
490: ("Which statement best describes the pillars of Iman?", ["They are rules only for praying Salah", "They are the six basic truths of Islamic belief", "They are conditions only for Wudu", "They are the five Islamic duties"]),
491: ("How does Surah Al-Ikhlas begin?", ["Qul huwallahu ahad", "Alhamdu lillahi", "Inna a’tayna", "Qul a’udhu bi rabbin-nas"]),
492: ("What does “Qul huwallahu ahad” mean?", ["Allah knows everything", "Allah sees everything", "Say: “He is Allah – the One!”", "Allah forgives sins"]),
493: ("Which ayah comes after “Qul huwallahu ahad”?", ["Lam yalid wa lam yulad", "Wa lam yakun lahu kufuwan ahad", "Bismillahir-Rahmanir-Rahim", "Allahus-Samad"]),
494: ("How is “Allahus-Samad” translated?", ["Allah is the refuge of everyone", "Allah is the Most Gracious", "Allah is the Creator", "Allah hears everything"]),
495: ("What comes after “Allahus-Samad”?", ["Qul huwallahu ahad", "Lam yalid wa lam yulad", "Wa lam yakun lahu kufuwan ahad", "Bismillahir-Rahmanir-Rahim"]),
496: ("What does “Lam yalid wa lam yulad” mean?", ["Allah is the refuge of everyone", "He is Allah – the One", "He neither begets nor was He begotten", "And there is none equal to Him"]),
497: ("What is the last ayah of Surah Al-Ikhlas?", ["Allahus-Samad", "Qul huwallahu ahad", "Lam yalid wa lam yulad", "Wa lam yakun lahu kufuwan ahad"]),
498: ("What does “Wa lam yakun lahu kufuwan ahad” mean?", ["And there is none equal to Him", "Allah is the refuge of everyone", "He is Allah – the One", "He neither begets nor was He begotten"]),
499: ("How many ayahs does Surah Al-Ikhlas have?", ["Three", "Four", "Five", "Six"]),
500: ("What does “Bismillahir-Rahmanir-Rahim” mean?", ["Allah is One", "Allah is the refuge of everyone", "I seek protection from Shaytan", "In the name of Allah, the Most Gracious, the Most Merciful"]),
501: ("According to the hadith, how much is Surah Al-Ikhlas worth?", ["As much as a third of the Qur’an", "As much as half of the Qur’an", "As much as the whole Qur’an", "As much as a quarter of the Qur’an"]),
502: ("Who narrates the hadith mentioned in the lesson about the value of Surah Al-Ikhlas?", ["Only Tirmidhi", "Bukhari and Muslim", "Only Abu Dawud", "Only Nasa’i"]),
}
