# English translations of the quiz BANK in sta-radi-masa, questions 0-163 (same order of options as the original).
Q = {
0: ("What does the phrase “Hasbi Rabbi” mean?", ["My Lord is enough for me", "Muhammad is Allah’s Messenger", "There is light in my heart", "Allah is the Greatest"]),
1: ("Who is enough for a believer?", ["A friend", "A teacher", "A parent", "Allah, the Most High"]),
2: ("According to the ilahi (nasheed), who is in our heart?", ["Only our family", "Only our friends", "Only Allah", "Only our teachers"]),
3: ("What is the second line of the ilahi Hasbi Rabbi?", ["Nur Muhammad sallallah", "La ilaha illallah", "Hasbi Rabbi jallallah", "Ma fi qalbi ghayrullah"]),
4: ("What is the third line of the ilahi Hasbi Rabbi?", ["La ilaha illallah", "Hasbi Rabbi jallallah", "Nur Muhammad sallallah", "Ma fi qalbi ghayrullah"]),
5: ("What is the last line of the ilahi Hasbi Rabbi?", ["Hasbi Rabbi jallallah", "La ilaha illallah", "Ma fi qalbi ghayrullah", "Nur Muhammad sallallah"]),
6: ("What does “La ilaha illallah” mean?", ["There is no god but Allah", "Allah is Merciful", "Muhammad is a light", "Allah is our Creator"]),
7: ("According to the words of the ilahi Hasbi Rabbi, who is our light?", ["The Sun", "The Moon", "Muhammad, alayhis-salam", "A teacher"]),
8: ("Who does a Muslim rely on?", ["Only on himself", "On his friends", "On other people", "Only on Allah, jalla sha’nuhu"]),
9: ("What does a Muslim carry out?", ["Allah’s commands", "All of his own wishes", "His friends’ orders", "Other people’s customs"]),
10: ("What does a Muslim stay away from?", ["Learning", "Good deeds", "What Allah has forbidden", "Salah"]),
11: ("Who is our role model in how we behave?", ["Any famous person", "Kids our own age", "Rich people", "Muhammad, alayhis-salam"]),
12: ("In what is Muhammad, alayhis-salam, our role model?", ["Only in how he dressed", "In behaviour", "Only in how he spoke", "In getting rich"]),
13: ("What should a Muslim do with Allah’s commands?", ["Carry them out", "Forget them", "Put them off", "Avoid them"]),
14: ("Which message matches the ilahi “Hasbi Rabbi”?", ["A person should rely only on his own strength", "The most important thing is to become rich", "A Muslim believes in Allah and follows His commands", "A person does not need a role model"]),
15: ("Who is the last Messenger of Allah?", ["Musa, alayhis-salam", "Isa, alayhis-salam", "Muhammad, alayhis-salam", "Ibrahim, alayhis-salam"]),
16: ("Where was Muhammad, alayhis-salam, born?", ["In Makkah", "In Madinah", "In Jerusalem", "In Ta’if"]),
17: ("On which Hijri date was Muhammad, alayhis-salam, born?", ["1 Muharram", "27 Rajab", "15 Sha’ban", "12 Rabi’ al-Awwal"]),
18: ("In which year was Muhammad, alayhis-salam, born?", ["In 610", "In 571", "In 622", "In 632"]),
19: ("On which date of the Gregorian calendar was Muhammad, alayhis-salam, born?", ["April 20", "January 1", "May 10", "June 12"]),
20: ("What was the name of the father of Muhammad, alayhis-salam?", ["Abu Talib", "Abdul-Muttalib", "Abdullah", "Hamzah"]),
21: ("What was the name of the mother of Muhammad, alayhis-salam?", ["Khadijah", "Aminah", "Fatimah", "Halimah"]),
22: ("Who did Muhammad, alayhis-salam, stay with after his parents died?", ["With his friends", "With neighbours", "With a teacher", "With his grandfather and his uncle"]),
23: ("What was the name of the grandfather of Muhammad, alayhis-salam?", ["Abdul-Muttalib", "Abu Talib", "Abdullah", "Abbas"]),
24: ("What was the name of the uncle of Muhammad, alayhis-salam, who raised him?", ["Abu Bakr", "Umar", "Abu Talib", "Uthman"]),
25: ("At what age did Allah, the Most High, begin sending the Revelation to Muhammad, alayhis-salam?", ["At twenty", "At forty", "At thirty", "At fifty"]),
26: ("What do we say when we mention the name Muhammad?", ["Alhamdulillah", "Alayhis-salam", "Salam", "Allahu akbar"]),
27: ("What does the phrase “alayhis-salam” mean?", ["May Allah have mercy on him", "Allah is the Greatest", "May Allah’s peace be upon him", "Thanks be to Allah"]),
28: ("Who should be our role model in how we behave?", ["The richest person", "The most famous athlete", "The best singer", "Muhammad, alayhis-salam"]),
29: ("How is Muhammad, alayhis-salam, related to Abdul-Muttalib?", ["Abdul-Muttalib was his father", "Abdul-Muttalib was his grandfather", "Abdul-Muttalib was his uncle", "Abdul-Muttalib was his friend"]),
30: ("How is Muhammad, alayhis-salam, related to Abu Talib?", ["Abu Talib was his grandfather", "Abu Talib was his brother", "Abu Talib was his uncle", "Abu Talib was his son"]),
31: ("How do we confirm that we belong to Islam?", ["By calling the Adhan", "By saying the Kalimat ash-Shahadah", "By giving salam", "By wearing clean clothes"]),
32: ("How many parts does the Kalimat ash-Shahadah have?", ["Three", "Four", "One", "Two"]),
33: ("What do we bear witness to in the first part of the Kalimat ash-Shahadah?", ["That Muhammad is the last prophet", "That angels exist", "That there is no god but Allah", "That fasting is obligatory"]),
34: ("What do we bear witness to in the second part of the Kalimat ash-Shahadah?", ["That Muhammad is Allah’s servant and Messenger", "That Musa, alayhis-salam, is the last prophet", "That we believe in the holy books", "That we believe in the angels"]),
35: ("How does the Kalimat ash-Shahadah begin?", ["Alhamdulillahi rabbil-‘alamin", "Ash-hadu an la ilaha illallah", "Bismillahir-Rahmanir-Rahim", "Subhana rabbiyal-‘azim"]),
36: ("What is salam?", ["A special kind of dua after Salah", "The name of one of the prayers", "The call to prayer", "The greeting Muslims give one another"]),
37: ("What is the Islamic greeting?", ["As-salamu alaykum", "Wa alaykumus-salam", "Allahu akbar", "Alhamdulillah"]),
38: ("How do we reply to salam?", ["As-salamu alaykum", "Alaykumus-salam", "MashaAllah", "Subhanallah"]),
39: ("Which words is it nice to add when giving salam?", ["Allahu akbar kabira", "Alhamdulillahi rabbil-‘alamin", "Wa rahmatullahi wa barakatuhu", "Astaghfirullah"]),
40: ("What does the Islamic greeting – salam – mean?", ["May Allah’s peace and blessings be upon you", "Have a safe trip", "I wish you a nice day", "Welcome to my home"]),
41: ("Who do we give salam to?", ["Only to our parents", "Only to our teachers", "Only to our friends", "To our parents, relatives, friends and the Muslims we know"]),
42: ("When do we give salam at home?", ["Only when leaving", "When coming into and going out of the house", "Only in the morning", "Only in the evening"]),
43: ("When else do we give salam?", ["When we join a group of people or leave it", "Only when we enter the mosque", "Only after eating", "Only before sleeping"]),
44: ("Which side does Islam give preference to?", ["The left side", "Both sides equally", "The right side", "Neither side"]),
45: ("Which hand should we eat with?", ["The left hand", "Both hands", "It doesn’t matter which hand", "The right hand"]),
46: ("Which sleeve do we put on first?", ["The right sleeve", "The left sleeve", "Both sleeves at the same time", "It is not set"]),
47: ("What is the right way to put on and take off shoes?", ["Put on the left shoe first, and take off the right shoe first", "Put on the right shoe first, and take off the left shoe first", "Always put on and take off the left shoe first", "The order doesn’t matter"]),
48: ("Which side is it recommended to sleep on?", ["On the stomach", "On the left side", "On the right side", "On the back"]),
49: ("Which dua do we say before starting a task?", ["The dua for travelling", "Rabbi yassir", "The dua after eating", "The dua for rain"]),
50: ("With the words “Rabbi yassir”, what do we ask Allah for?", ["To give us lots of wealth", "To give us a long life", "To make things easy for us", "To make us famous"]),
51: ("How does the dua for a blessed start begin?", ["Rabbi zidni ilma", "Bismillahi", "Alhamdulillahi", "Rabbi yassir wa la tu’assir"]),
52: ("What does “wa la tu’assir” mean?", ["And do not make it difficult", "Increase my knowledge", "Forgive my sins", "Protect me on my journey"]),
53: ("What does “Rabbi tammim bil-khayr” mean?", ["My Lord, increase my knowledge", "My Lord, complete my work with good", "My Lord, give me good health", "My Lord, forgive my parents"]),
54: ("What do we ask Allah for with the dua for a blessed start?", ["Ease, blessing and success in good deeds", "Only money and things", "To win every game", "To never have to work"]),
55: ("Who gives knowledge to people?", ["Only books", "Only school", "Allah", "Only parents"]),
56: ("What is the dua for more knowledge?", ["Rabbi yassir", "Subhanallah", "Alhamdulillah", "Rabbi zidni ilma"]),
57: ("What does “Rabbi zidni ilma” mean?", ["My Lord, increase me in knowledge", "My Lord, make my way easy", "My Lord, give me food", "My Lord, heal me"]),
58: ("In which surah of the Qur’an is the dua “Rabbi zidni ilma”?", ["Al-Fatihah", "Ta-Ha", "Al-Ikhlas", "An-Nas"]),
59: ("What is the ayah number of the dua “Rabbi zidni ilma”?", ["Ayah 14", "Ayah 40", "Ayah 114", "Ayah 120"]),
60: ("When should we say the dua for knowledge?", ["Only before sleeping", "Only before eating", "Only before travelling", "Before we start studying and doing homework"]),
61: ("What is our religion called?", ["Islam", "Christianity", "Judaism", "Buddhism"]),
62: ("What are we by religion?", ["Only pupils", "Muslim boys and girls", "Travellers", "Poets"]),
63: ("Who do Muslims believe in?", ["Only in people", "In the sun and the stars", "In Allah", "In statues"]),
64: ("What should Muslims say?", ["The truth", "Lies", "Ugly words", "Things that hurt others"]),
65: ("What kind of deeds should Muslims do?", ["Bad deeds", "Good deeds", "Only easy deeds", "Useless deeds"]),
66: ("What does Islam ask of believers?", ["Laziness", "Injustice", "Sacrifice, learning and work", "Arrogance"]),
67: ("What does Islam lead us to?", ["Sin", "Quarrels", "Failure", "Happiness and success"]),
68: ("Who is our prophet?", ["Yunus (AS)", "Nuh (AS)", "Muhammad (AS)", "Jibril (AS)"]),
69: ("What is our holy book?", ["The Ilmihal (Islamic textbook)", "A notebook", "A schoolbook", "The Qur’an"]),
70: ("What is our religion?", ["Islam", "The Qur’an", "Dua", "Salah"]),
71: ("What do we say before the Bismillah?", ["The takbir", "The A’udhu billah", "The salawat", "Al-Fatihah"]),
72: ("What do the words of the A’udhu billah mean?", ["Praise be to Allah, Lord of the worlds", "Allah is the Greatest", "I ask Allah for forgiveness", "I seek Allah’s protection from the accursed Shaytan"]),
73: ("With which names of Allah does the Bismillah end?", ["The Most Gracious and the Most Merciful", "The Mighty and the Wise", "The First and the Last", "The Creator and the Provider"]),
74: ("How do we begin good and blessed tasks?", ["By calling the Adhan", "By saying the takbir", "By saying the A’udhu billah and the Bismillah", "By giving salam"]),
75: ("What do we ask for by saying the A’udhu billah and the Bismillah?", ["That Allah gives us lots of wealth", "That Allah protects us and gives us His mercy", "That we always win at games", "That we are never tired"]),
76: ("When should we say the A’udhu billah and the Bismillah?", ["Only in the morning", "Only before sleeping", "Only when we recite the Qur’an", "On many different occasions"]),
77: ("Among other times, when do we say the A’udhu billah and the Bismillah?", ["In the morning and in the evening", "Only on Fridays", "Only in the mosque", "Only during Ramadan"]),
78: ("What should we say when we start a drive or ride?", ["Only the dua after eating", "Only the salawat", "The A’udhu billah and the Bismillah", "We don’t need to say anything"]),
79: ("What is Allah’s most beautiful creation?", ["A plant", "The human being", "A mountain", "A river"]),
80: ("How should we live on Earth?", ["Without any rules", "Responsibly and in obedience to Allah, the Most High", "Thinking only about playing", "Far away from other people"]),
81: ("Why were the jinn and people created?", ["Only to play", "To collect riches", "To travel the world", "To worship Allah"]),
82: ("About how many neurons are there in the human brain?", ["About 100 billion", "About 100 thousand", "About 100 million", "About one million"]),
83: ("Who did Mirza come to the maktab with on the first day?", ["With his friends", "Alone", "With his parents", "With his teacher"]),
84: ("Who did the pupils meet at the maktab?", ["Their teachers (mu’allim and mu’allima)", "A doctor and a nurse", "A driver and a police officer", "A shopkeeper and a customer"]),
85: ("What do children learn about at the maktab?", ["Only about sports", "About Islamic belief, duties and good behaviour", "Only about maths", "Only about writing"]),
86: ("What made Mirza happy at the maktab?", ["The end of the lesson", "Getting a toy", "Going back home", "Meeting his friends"]),
87: ("When do we say the Subhanaka?", ["After every Salah", "Especially at the beginning of every Salah", "Only after the salam", "Only before Salah"]),
88: ("With which words does the Subhanaka begin?", ["Al-hamdu lillahi", "Bismillahir-Rahmanir-Rahim", "Subhanakallahumma", "Iyyaka na’budu"]),
89: ("Which words come after “Subhanakallahumma”?", ["Wa tabarakasmuka", "Wa la ilaha ghayruk", "Wa ta’ala jadduka", "Wa bihamdika"]),
90: ("What does the phrase “Subhanakallahumma” mean?", ["Glory be to You, O Allah", "Guide us to the Straight Path", "You alone we worship", "From You we ask for help"]),
91: ("What does “wa bihamdika” mean?", ["Great is Your name", "All praise is Yours", "There is no god other than You", "You are the Master of the Day of Judgement"]),
92: ("Which part of the Subhanaka means: “Blessed is Your name”?", ["Wa bihamdika", "Wa ta’ala jadduka", "Wa tabarakasmuka", "Wa la ilaha ghayruk"]),
93: ("What does “wa ta’ala jadduka” mean?", ["All praise is Yours", "Blessed is Your name", "Glory be to You, O Allah", "Your majesty is beyond reach"]),
94: ("With which words does the Subhanaka end?", ["Wa la ilaha ghayruk", "Amin", "Ihdinas-siratal-mustaqim", "Maliki yawmid-din"]),
95: ("What does “wa la ilaha ghayruk” mean?", ["You, Allah, we praise", "There is no god other than You", "Guide us to the Straight Path", "From You we ask for help"]),
96: ("What comes after the words “wa bihamdika”?", ["Wa ta’ala jadduka", "Wa la ilaha ghayruk", "Wa tabarakasmuka", "Subhanakallahumma"]),
97: ("Which part comes right before “wa la ilaha ghayruk”?", ["Wa bihamdika", "Wa tabarakasmuka", "Subhanakallahumma", "Wa ta’ala jadduka"]),
98: ("When is it recommended to say the Subhanaka?", ["At the beginning of every Salah", "Only once in a lifetime", "After every rak’ah", "Only on Fridays"]),
99: ("Which sentence belongs to the Subhanaka?", ["Iyyaka na’budu", "Wa tabarakasmuka", "Ihdinas-siratal-mustaqim", "Maliki yawmid-din"]),
100: ("Which sentence does not belong to the Subhanaka?", ["Wa bihamdika", "Wa ta’ala jadduka", "Ar-Rahmanir-Rahim", "Wa la ilaha ghayruk"]),
101: ("Which meaning is given in the translation of the Subhanaka?", ["Guide us to the Straight Path", "You alone we worship", "Master of the Day of Judgement", "Your majesty is beyond reach"]),
102: ("What does the Subhanaka say about Allah’s name?", ["That it is blessed", "That it should be mentioned", "That only the angels know it", "That it is said only on Fridays"]),
103: ("What do we confirm at the end of the Subhanaka?", ["That Al-Fatihah is the first surah", "That there is no god other than Allah", "That the Salah is finished", "That we seek protection from Shaytan"]),
104: ("What is the correct order of the first parts of the Subhanaka?", ["Wa bihamdika – Subhanakallahumma", "Wa tabarakasmuka – Wa bihamdika", "Subhanakallahumma – Wa bihamdika", "Wa ta’ala jadduka – Wa tabarakasmuka"]),
105: ("Which surah in the Qur’an, in order, is Al-Fatihah?", ["The first", "The second", "The seventh", "The last"]),
106: ("What is the name of the first surah in the Qur’an?", ["Al-Ikhlas", "Al-Fatihah", "An-Nas", "Al-Kawthar"]),
107: ("With which words do we seek Allah’s protection from the accursed Shaytan?", ["Al-hamdu lillahi Rabbil-‘alamin", "Bismillahir-Rahmanir-Rahim", "A’udhu billahi minash-shaytanir-rajim", "Iyyaka na’budu wa iyyaka nasta’in"]),
108: ("What does “A’udhu billahi minash-shaytanir-rajim” mean?", ["In the name of Allah, the Most Gracious, the Most Merciful", "You alone we worship", "Guide us to the Straight Path", "I seek Allah’s protection from the accursed Shaytan"]),
109: ("What is the Bismillah?", ["Bismillahir-Rahmanir-Rahim", "Al-hamdu lillahi Rabbil-‘alamin", "Maliki yawmid-din", "Ihdinas-siratal-mustaqim"]),
110: ("What does the Bismillah mean?", ["Praise be to Allah, Lord of the worlds", "In the name of Allah, the Most Gracious, the Most Merciful", "Guide us to the Straight Path", "You alone we worship"]),
111: ("With which words does Al-Fatihah begin after the Bismillah?", ["Ar-Rahmanir-Rahim", "Maliki yawmid-din", "Al-hamdu lillahi Rabbil-‘alamin", "Iyyaka na’budu wa iyyaka nasta’in"]),
112: ("What does “Al-hamdu lillahi Rabbil-‘alamin” mean?", ["Master of the Day of Judgement", "Guide us to the Straight Path", "You alone we worship", "We praise You, Allah, Lord of the worlds"]),
113: ("Which of Allah’s attributes do we mention with the words “Ar-Rahmanir-Rahim”?", ["The Most Gracious and the Most Merciful", "The Strong and the Mighty", "The First and the Last", "The Creator and the Provider"]),
114: ("What does “Maliki yawmid-din” mean?", ["Lord of the worlds", "Master of the Day of Judgement", "The Most Gracious and the Most Merciful", "The One who guides to the Straight Path"]),
115: ("Which words mean: “You alone we worship and from You alone we ask for help”?", ["Ar-Rahmanir-Rahim", "Maliki yawmid-din", "Iyyaka na’budu wa iyyaka nasta’in", "Siratal-ladhina an’amta ‘alayhim"]),
116: ("Who do we ask for help in Al-Fatihah?", ["People", "The angels", "The prophets", "Allah"]),
117: ("What do we ask for with the words “Ihdinas-siratal-mustaqim”?", ["For Allah to guide us to the Straight Path", "To give us riches", "To make us famous", "For us to make something"]),
118: ("Which part of Al-Fatihah means “Guide us to the Straight Path”?", ["Maliki yawmid-din", "Ihdinas-siratal-mustaqim", "Ar-Rahmanir-Rahim", "Wa la ilaha ghayruk"]),
119: ("Whose path do we ask Allah to guide us to?", ["The path of the richest people", "The path of all rulers", "The path of those whom Allah has blessed", "The path of those who went astray"]),
120: ("What does “Siratal-ladhina an’amta ‘alayhim” mean?", ["The path of those who went astray", "The path of those who earned anger", "Master of the Day of Judgement", "The path of those whom Allah has blessed with His favour"]),
121: ("According to the end of Al-Fatihah, whose path do we not want to follow?", ["The path of those who earned anger and of those who went astray", "The path of good people", "The path of Allah’s messengers", "The path of grateful believers"]),
122: ("With which word do we finish reciting Al-Fatihah?", ["Subhanallah", "Amin", "Alhamdulillah", "Allahu akbar"]),
123: ("What does the word “Amin” mean?", ["Allah is the Greatest", "Glory be to Allah", "O Allah, answer our dua", "I seek protection from Shaytan"]),
124: ("Why is Al-Fatihah especially important?", ["It is recited only on Fridays", "It is the longest surah of the Qur’an", "It is recited only on Eid", "It is the best dua and we recite it in Salah"]),
125: ("How is Al-Fatihah described in the picture?", ["As the best dua", "As the longest surah", "As the last surah", "As a dua that is not recited in Salah"]),
126: ("What is it recommended to say on every occasion?", ["Wa la ilaha ghayruk", "Al-hamdu lillah – praise be to Allah", "Ihdinas-siratal-mustaqim", "Maliki yawmid-din"]),
127: ("Which sentence comes after “Al-hamdu lillahi Rabbil-‘alamin”?", ["Maliki yawmid-din", "Iyyaka na’budu", "Ar-Rahmanir-Rahim", "Ihdinas-siratal-mustaqim"]),
128: ("Which sentence comes right after “Maliki yawmid-din”?", ["Ar-Rahmanir-Rahim", "Ihdinas-siratal-mustaqim", "Siratal-ladhina an’amta ‘alayhim", "Iyyaka na’budu wa iyyaka nasta’in"]),
129: ("Which sentence comes after “Iyyaka na’budu wa iyyaka nasta’in”?", ["Ihdinas-siratal-mustaqim", "Maliki yawmid-din", "Ar-Rahmanir-Rahim", "Wa ta’ala jadduka"]),
130: ("What do we say about Allah in Al-Fatihah?", ["That He is the Lord of only one people", "That He is the Lord of the worlds", "That He created only people", "That we ask others for help"]),
131: ("Which sentence does not belong to Surah Al-Fatihah?", ["Ar-Rahmanir-Rahim", "Maliki yawmid-din", "Wa tabarakasmuka", "Ihdinas-siratal-mustaqim"]),
132: ("Which part of Al-Fatihah talks about the Day of Judgement?", ["Ar-Rahmanir-Rahim", "Al-hamdu lillahi Rabbil-‘alamin", "Iyyaka na’budu wa iyyaka nasta’in", "Maliki yawmid-din"]),
133: ("What do the words “Iyyaka na’budu” teach us?", ["That we worship only Allah", "That we worship people", "That we ask statues for help", "That Salah is not obligatory"]),
134: ("What is the main request in Surah Al-Fatihah?", ["A request for great riches", "A request that Allah guides us to the Straight Path", "A request that we never have to work", "A request for a long life without any tests"]),
135: ("What is the fourth condition of Salah?", ["Dressing properly", "Praying Salah on time", "Making Wudu", "Facing the Qiblah"]),
136: ("What does the fourth condition of Salah mean?", ["That we pray every Salah at its set time", "That we pray every Salah in the mosque", "That we pray only in the morning", "That we pray only in the evening"]),
137: ("How many prayer times, or daily prayers, are there?", ["Three", "Four", "Six", "Five"]),
138: ("What is the first daily prayer?", ["Dhuhr", "Asr", "Fajr", "Maghrib"]),
139: ("How else is the Fajr prayer described?", ["The morning prayer", "The daytime prayer", "The evening prayer", "The night prayer"]),
140: ("What is the second daily prayer?", ["Fajr", "Dhuhr", "Maghrib", "Isha"]),
141: ("How is the Dhuhr prayer described?", ["The morning prayer", "The night prayer", "The evening prayer", "The daytime prayer"]),
142: ("What is the third daily prayer?", ["Maghrib", "Isha", "Asr", "Fajr"]),
143: ("Which prayer comes after Asr?", ["Maghrib", "Fajr", "Dhuhr", "Isha"]),
144: ("How is the Maghrib prayer described?", ["The morning prayer", "The evening prayer", "The daytime prayer", "The noon prayer"]),
145: ("What is the fifth daily prayer?", ["Dhuhr", "Maghrib", "Asr", "Isha"]),
146: ("How is the Isha prayer described?", ["The daytime prayer", "The morning prayer", "The night prayer", "The evening prayer"]),
147: ("What is the correct order of the five daily prayers?", ["Fajr, Dhuhr, Asr, Maghrib, Isha", "Fajr, Asr, Dhuhr, Isha, Maghrib", "Dhuhr, Fajr, Asr, Maghrib, Isha", "Fajr, Dhuhr, Maghrib, Asr, Isha"]),
148: ("Who announces the start of a prayer time?", ["The imam, by reciting the Qur’an", "The muezzin, by calling the Adhan", "The congregation, by making dua", "The khatib, by giving the khutbah"]),
149: ("Where can we check the exact prayer times?", ["Only on a clock", "In any book", "In the school calendar", "In the yearly Islamic prayer calendar – the Takvim"]),
150: ("When can Salah not be prayed?", ["When it is raining", "When it is cold", "When the Sun is rising", "When it is cloudy"]),
151: ("When else can Salah not be prayed?", ["When the Sun is in the middle of the sky", "After the Dhuhr prayer", "After Maghrib", "Before Isha"]),
152: ("What is another time when Salah cannot be prayed?", ["When the Sun has risen", "When the Sun is setting", "After Isha", "Before noon"]),
153: ("When is it disliked (makruh) to pray?", ["Two hours after sunrise", "Only after Isha", "Only before Fajr", "About 45 minutes after sunrise"]),
154: ("How long before sunset is it disliked to pray, except for that day’s Asr?", ["About 10 minutes", "About 20 minutes", "About 45 minutes", "About 90 minutes"]),
155: ("What is the fifth condition of Salah?", ["Making the intention", "Facing the Qiblah – the Ka’bah", "Making Wudu", "Praying Salah on time"]),
156: ("What is the Qiblah?", ["The direction of the Ka’bah", "The place for making Wudu", "The mosque courtyard", "The call to prayer"]),
157: ("Where is the Ka’bah?", ["In Madinah", "In Jerusalem", "In Makkah", "In Damascus"]),
158: ("In which country is the Ka’bah?", ["Egypt", "Turkey", "Jordan", "Saudi Arabia"]),
159: ("What do Muslims all over the world turn towards when they pray Salah?", ["Towards the Ka’bah", "Towards the nearest mosque", "Towards the sunrise", "Towards Madinah"]),
160: ("What is the Ka’bah?", ["The tallest minaret of a mosque", "The most honoured House of Allah", "A house in Madinah", "A mountain near Makkah"]),
161: ("What shape is the Ka’bah?", ["Round", "Triangular", "Shaped like a cube", "Shaped like a pyramid"]),
162: ("What is in one corner of the Ka’bah?", ["A minbar", "A mihrab", "The Zamzam spring", "The Black Stone – Al-Hajar al-Aswad"]),
163: ("What is the Ka’bah covered with every year?", ["A black cover with ayahs of the Qur’an written on it", "A plain white cloth", "A green cover", "A golden cloth"]),
}
