T = [
    ('<title>Pronađi riječ – Svojstva Allahovih poslanika</title>', '<title>Word Search – Qualities of Allah’s Messengers</title>'),
    ('<h1>PRONAĐI RIJEČ – POSLANICI</h1>', '<h1>WORD SEARCH – MESSENGERS</h1>'),
    ('<div class="sub">Svojstva Allahovih poslanika</div>', '<div class="sub">Qualities of Allah’s messengers</div>'),
    ('Zadatak: <b', 'Task: <b'), ('Bodovi: <b', 'Points: <b'),
    ('💡 Pomoć −2', '💡 Hint −2'), ('↻ Nova igra', '↻ New game'),
    ('<div class="foot">Pripremio Abdo ef. Rekić</div>\n', ''),
    ('["SIDK","Allahovi poslanici uvijek su govorili istinu."]', '["SIDQ","Allah’s messengers always told the truth."]'),
    ('["EMANET","Allahovi poslanici bili su povjerljivi i pouzdani."]', '["AMANAH","Allah’s messengers were trustworthy and reliable."]'),
    ('["TEBLIG","Allahovi poslanici vjerno su prenosili Allahovu objavu ljudima."]', '["TABLIGH","Allah’s messengers faithfully passed on Allah’s revelation to people."]'),
    ('["FETANET","Allahovi poslanici bili su veoma pametni i razboriti."]', '["FATANAH","Allah’s messengers were very intelligent and wise."]'),
    ('["ISMET","Allahovi poslanici bili su sačuvani od grijeha."]', '["ISMAH","Allah’s messengers were protected from sin."]'),
    ('"Bravo! Pronašao/la si svih 5 svojstava Allahovih poslanika."', '"Well done! You found all 5 qualities of Allah’s messengers."'),
    ('"Ukupno bodova: "', '"Total points: "'),
    ('"Dodirni prvo slovo, pa posljednje slovo riječi."', '"Tap the first letter, then the last letter of the word."'),
    ('>Dodirni prvo slovo, pa posljednje slovo riječi.<', '>Tap the first letter, then the last letter of the word.<'),
    ('"Sada dodirni posljednje slovo riječi."', '"Now tap the last letter of the word."'),
    ('"✓ Tačno! +10 bodova"', '"✓ Correct! +10 points"'),
    ('"Pokušaj ponovo. −3 boda"', '"Try again. −3 points"'),
    ('"Riječ ima "+answer.length+" slova i počinje slovom „"+answer.charAt(0)+"“."', '"The word has "+answer.length+" letters and starts with “"+answer.charAt(0)+"”."'),
]
