"""Curriculum for the yearly class plan: every lesson of Ilmihal 1–3 (English title, book page, topics) and the
games that match each topic. Used by tools/plan/build_plan.py."""

# ---------------------------------------------------------------- games (slug, title, topics)
SITE = 'https://ademdeniz.github.io/islamic-games-en/'
GAMES = {
    'learn-surahs-by-heart': ('Learn the Surahs by Heart', {'surah', 'fatiha', 'kursi'}),
    'memori-sure': ('Memory – Let’s Learn the Surahs', {'surah', 'fatiha'}),
    'citaj-kuran': ('Read Along with the Reciter', {'quran'}),
    'pomozimo-maci-abdest': ('Help the Kitty Make Wudu', {'wudu'}),
    'kviz-maca-namaz': ('Preparing for Salah – Help the Kitty', {'salah-conditions', 'wudu', 'ghusl', 'qiblah'}),
    'sastavi-namaz': ('Build the Salah', {'salah-steps', 'five-prayers'}),
    'akademija-namaza-igre': ('Salah Academy – Puzzles', {'salah-steps', 'five-prayers'}),
    'akademija-namaza': ('Salah Academy', {'salah', 'salah-conditions', 'salah-steps'}),
    '5-dnevnih-namaza': ('The 5 Daily Prayers', {'five-prayers', 'salah'}),
    'kviz-namaz': ('Salah Quiz', {'salah', 'salah-conditions', 'salah-steps', 'adhan', 'jumuah'}),
    'memori-imanski-sarti': ('Memory – Pillars of Iman', {'iman'}),
    'kviz-imanski-sarti': ('Pillars of Iman Quiz', {'iman', 'sifat', 'shahadah'}),
    'memori-meleki': ('Memory – Duties of the Angels', {'angels'}),
    'meleki-trazenje-rijeci': ('Word Search – Angels', {'angels'}),
    'boziji-kitabi': ('Word Search – Allah’s Books', {'books'}),
    'svojstva-allahovih-poslanika': ('Word Search – Qualities of the Messengers', {'prophets'}),
    'sifati-trazenje-rijeci': ('Word Search – Attributes of Allah', {'sifat'}),
    'memori-kviz-sifati': ('Memory Quiz – Attributes of Allah', {'sifat', 'allah'}),
    'ramazanski-put': ('The Ramadan Path', {'ramadan', 'fasting', 'eid', 'zakah'}),
    'oslobodi-papagaja': ('Free the Parrot!', {'blessed-nights', 'eid'}),
    'ilmihal-memori': ('Big Memory Game – Ilmihal', {'review-1', 'ghusl', 'tayammum', 'salah-conditions'}),
    'kviz-nivo-a1': ('Quiz – Level A1', {'review-1'}),
    'lov-na-blago-a1': ('Treasure Hunt – Level A1', {'review-1'}),
    'nahrani-ptica-a1': ('Feed the Baby Birds', {'review-1', 'dua'}),
    'otkljucaj-vrata-dzamije': ('Unlock the Mosque Doors', {'review-1'}),
    'islamski-milijunas-nivo-a2': ('Islamic Millionaire – Level A2', {'review-1'}),
    'kviz-ilmihal-1-a3': ('Ilmihal Quiz 1 – Level A3', {'review-1'}),
    'pcelica-skuplja-med': ('The Little Bee Collects Honey', {'review-1'}),
    'islamski-milijunas': ('Islamic Millionaire', {'review-1', 'review-2'}),
    'ilmihal-2-nivo-b1': ('Ilmihal Quiz 2 – Level B1', {'review-2'}),
    'potraga-za-blagom-b1': ('Treasure Hunt – Level B1', {'review-2'}),
    'islamski-escape-room-b1': ('Islamic Escape Room – B1', {'review-2', 'review-3'}),
    'escape-room-b1-sifra': ('Maktab Escape Room – B1', {'review-2', 'review-3'}),
    'ilmihal-2-nivo-b2': ('Ilmihal Quiz 2 – Level B2', {'review-2', 'review-3'}),
    'mektebski-detektiv': ('Maktab Detective', {'review-3', 'prophets', 'seerah', 'akhlaq'}),
    'mektebski-detektiv-igra': ('Maktab Detective – Cases', {'review-3', 'seerah', 'calendar'}),
    'tajna-zivotinja': ('Secret Animal', {'review-1', 'nature'}),
    'zagonetna-zivotinja-a3': ('Mystery Animal', {'review-1', 'nature'}),
    'sta-radi-masa': ('What Is Masha Doing?', {'review-1', 'akhlaq'}),
    # play together (2–4 players, the shared Ilmihal bank) – one a week for each group from November
    'mektebski-fudbal': ('Maktab Football (2 players)', {'together'}),
    'mektebsko-povlacenje-konopa': ('Maktab Tug of War (2 players)', {'together'}),
    'mektebski-milioner': ('Maktab Millionaire for Two', {'together'}),
    'mektebsko-kolo-srece': ('Maktab Wheel of Fortune (2 players)', {'together'}),
    'mektebski-covjece-ne-ljuti-se': ('Maktab Board Game – Don’t Get Angry! (2–4 players)', {'together'}),
    'mektebski-turnir': ('Maktab Tournament (4 players)', {'together'}),
}
TOGETHER = ['mektebski-fudbal', 'mektebsko-povlacenje-konopa', 'mektebski-milioner', 'mektebsko-kolo-srece',
            'mektebski-covjece-ne-ljuti-se', 'mektebski-turnir']

# rotating fallback games when a lesson has no topic match, per book
FALLBACK = {1: ['kviz-nivo-a1', 'nahrani-ptica-a1', 'lov-na-blago-a1', 'otkljucaj-vrata-dzamije', 'pcelica-skuplja-med',
                'tajna-zivotinja', 'sta-radi-masa', 'islamski-milijunas-nivo-a2', 'kviz-ilmihal-1-a3'],
            2: ['ilmihal-2-nivo-b1', 'potraga-za-blagom-b1', 'islamski-escape-room-b1', 'escape-room-b1-sifra', 'islamski-milijunas'],
            3: ['ilmihal-2-nivo-b2', 'mektebski-detektiv', 'mektebski-detektiv-igra', 'islamski-milijunas', 'escape-room-b1-sifra']}

# ---------------------------------------------------------------- lessons: (book page, English title, topics)
# 'built' marks lessons that already have an English lesson page (lessons/<book>/<id>/)
ILMIHAL = {
    1: [
        (8, 'A‘udhu billah and Bismillah', {'dua', 'bismillah'}, 'ilmihal-1/01-audhu-bismillah'),
        (9, 'How we start every good deed', {'dua', 'bismillah'}), (10, 'The human being – Allah’s most beautiful creation', {'allah'}),
        (11, 'I go to the maktab', {'akhlaq'}), (12, 'Du‘a for a good start – Rabbi yassir', {'dua'}), (13, 'Du‘a for knowledge', {'dua'}),
        (14, 'What is our religion called?', {'iman'}), (15, 'Allahu Rabbi', {'allah', 'dua'}), (16, 'Mirza hurries to the maktab', {'akhlaq'}),
        (17, 'The Shahadah', {'shahadah'}), (18, 'The Islamic greeting – salam', {'akhlaq'}), (19, 'Water is the source of life', {'nature', 'wudu'}),
        (20, 'Review', {'review-1'}), (21, 'Let’s not forget', {'review-1'}), (22, 'Subhanaka – with its meaning', {'dua', 'salah-steps'}),
        (23, 'Surah Al-Fatiha', {'surah', 'fatiha'}), (24, 'Allah (SWT)', {'allah', 'sifat'}), (25, 'The Almighty Creator', {'allah', 'sifat'}),
        (26, 'Muhammad (SAW) is our Prophet', {'prophets', 'seerah'}), (27, 'Hasbi Rabbi', {'dua'}), (28, 'The right side comes first', {'akhlaq'}),
        (29, 'Review', {'review-1'}), (30, 'The conditions of the religion (din)', {'iman'}), (31, 'The pillars of Iman', {'iman'}),
        (32, 'Surah Al-Ikhlas', {'surah'}), (33, 'The pillars of Islam', {'shahadah', 'salah'}), (34, 'Salah', {'salah'}),
        (35, 'The conditions of Salah', {'salah-conditions'}), (36, 'Review', {'review-1'}), (37, 'The first condition of Salah', {'salah-conditions', 'ghusl'}),
        (38, 'The second condition of Salah – Wudu', {'wudu', 'salah-conditions'}), (40, 'The rules of Wudu', {'wudu'}),
        (41, 'What breaks Wudu', {'wudu'}), (42, 'Wudu – practice', {'wudu'}), (43, 'Surah An-Nas', {'surah'}),
        (44, 'The third condition of Salah', {'salah-conditions'}), (45, 'The fourth condition of Salah', {'salah-conditions'}),
        (46, 'The Adhan', {'adhan'}), (47, 'The Iqamah', {'adhan'}), (48, 'Du‘a after the Adhan', {'adhan', 'dua'}),
        (49, 'The fifth condition of Salah', {'salah-conditions', 'qiblah'}), (50, 'Finding our way in nature and the direction of the Qiblah', {'qiblah', 'nature'}),
        (51, 'The sixth condition of Salah', {'salah-conditions'}), (52, 'Review', {'review-1'}), (53, 'Let’s not forget', {'review-1'}),
        (54, 'Pillars of Salah: opening takbir, standing and recitation', {'salah-steps'}),
        (55, 'Pillars of Salah: ruku‘, sajdah and the last sitting', {'salah-steps'}), (56, 'Manners of entering and leaving', {'akhlaq'}),
        (57, 'Surah Al-Falaq', {'surah'}), (58, 'The rules of Ghusl', {'ghusl'}), (59, 'The rules of Tayammum', {'tayammum'}),
        (60, 'At-Tahiyyat', {'salah-steps', 'dua'}), (61, 'Salawat', {'dua', 'salah-steps'}), (62, 'Du‘as', {'dua'}),
        (63, 'Review', {'review-1'}), (64, 'Islamic manners', {'akhlaq'}), (65, 'Blessed days for Muslims', {'blessed-nights', 'calendar'}),
        (66, 'The joy of Eid al-Fitr', {'eid', 'ramadan'}), (67, 'The joy of Eid al-Adha', {'eid'}), (68, 'What is good to do on Eid', {'eid'}),
        (69, 'The new Hijri year', {'calendar'}), (70, 'Mawlid – the birth of Muhammad (SAW)', {'seerah'}), (71, 'Dobro nam doš’o (Welcome)', {'seerah'}),
        (72, 'Review', {'review-1'}), (73, 'Let’s not forget', {'review-1'}), (74, 'The five daily prayers', {'five-prayers'}),
        (75, 'Fajr prayer', {'five-prayers', 'salah-steps'}), (76, 'Fajr prayer: the first rak‘ah', {'salah-steps'}),
        (77, 'Fajr prayer: the second rak‘ah', {'salah-steps'}), (78, 'Fajr prayer: the last sitting', {'salah-steps'}),
        (79, 'Surah Al-Masad (Al-Lahab)', {'surah'}), (80, 'Maghrib prayer', {'five-prayers', 'salah-steps'}), (81, 'Ayat al-Kursi', {'kursi', 'surah'}),
        (82, 'Dhikr after Salah', {'dua'}), (83, 'Dhikr – tasbih after Salah', {'dua'}), (84, 'Surah An-Nasr', {'surah'}),
        (85, 'Eid activities for maktab students', {'eid'}), (86, 'Sport and recreation', {'akhlaq'}), (87, 'Review', {'review-1'}),
    ],
    2: [
        (8, 'Prophet Adam (AS)', {'prophets'}, 'ilmihal-2/01-adam'), (10, 'First pillar of Iman – Amantu billahi', {'iman', 'allah'}),
        (11, 'The essential attributes of Allah (sifat dhatiyyah)', {'sifat'}), (12, 'The positive attributes of Allah (sifat thubutiyyah)', {'sifat'}),
        (14, 'Second pillar of Iman – belief in the angels', {'angels', 'iman'}), (16, 'Third pillar of Iman – belief in the books', {'books', 'iman'}),
        (17, 'Fourth pillar of Iman – belief in the messengers', {'prophets', 'iman'}), (19, 'Fifth pillar of Iman – belief in the Last Day', {'iman'}),
        (20, 'Sixth pillar of Iman – belief in qadar', {'iman'}), (21, 'Surah Al-Kafirun with its meaning', {'surah'}),
        (22, 'First pillar of Islam – the Shahadah', {'shahadah'}), (24, 'Second pillar of Islam – Salah', {'salah'}),
        (26, 'What breaks Salah', {'salah'}), (27, 'Sajdat as-sahw (prostration of forgetfulness)', {'salah-steps'}),
        (28, 'How to pray Salah', {'salah-steps'}), (30, 'Praying in congregation (jama‘ah)', {'salah'}), (32, 'Joining the congregation late', {'salah'}),
        (34, 'Third pillar of Islam – fasting', {'fasting', 'ramadan'}), (36, 'Fourth pillar of Islam – Zakah', {'zakah'}),
        (38, 'Fifth pillar of Islam – Hajj', {'hajj'}), (40, 'Review', {'review-2'}), (43, 'A Muslim is tidy', {'akhlaq'}),
        (45, 'Cleanliness and personal hygiene', {'akhlaq', 'wudu'}), (46, 'Our duty to stay healthy', {'akhlaq'}), (47, 'Healthy eating', {'akhlaq'}),
        (49, 'Manners when eating', {'akhlaq', 'dua'}), (50, 'Du‘a after eating with its meaning', {'dua'}),
        (51, 'Love and obedience to parents', {'akhlaq'}), (53, 'Caring for sisters and brothers', {'akhlaq'}), (54, 'Duties to relatives', {'akhlaq'}),
        (56, 'Halal and haram', {'akhlaq'}), (57, 'Salah protects and teaches us', {'salah'}), (58, 'Dhuhr prayer', {'five-prayers', 'salah-steps'}),
        (60, 'Tayammum – symbolic purification', {'tayammum'}), (61, 'Wiping over socks and bandages', {'wudu'}),
        (62, 'Surah Al-Kawthar with its meaning', {'surah'}), (63, 'Review', {'review-2'}), (65, 'Kinds of sins – small sins', {'akhlaq'}),
        (66, 'Major sins', {'akhlaq'}), (67, 'Serious sins', {'akhlaq'}), (68, 'The consequences of sin', {'akhlaq'}),
        (70, 'Tawbah – repentance', {'akhlaq', 'dua'}), (72, 'Honesty and responsibility', {'akhlaq'}), (73, 'Sincerity and compassion', {'akhlaq'}),
        (76, 'Modesty and moderation', {'akhlaq'}), (78, 'Asr prayer', {'five-prayers', 'salah-steps'}), (80, 'The traveller’s prayer', {'salah'}),
        (82, 'The prayer of the sick', {'salah'}), (83, 'Isha prayer', {'five-prayers', 'salah-steps'}), (85, 'The Qunut du‘a with its meaning', {'dua', 'salah-steps'}),
        (86, 'Du‘a in Salah', {'dua', 'salah-steps'}), (87, 'Surah Al-Ma‘un with its meaning', {'surah'}),
        (88, 'Good work habits and gaining knowledge', {'akhlaq'}), (90, 'Review', {'review-2'}), (93, 'The middle way', {'akhlaq'}),
        (94, 'Jumu‘ah prayer – the weekly worship', {'jumuah', 'salah'}), (96, 'The Eid prayer', {'eid', 'salah'}),
        (97, 'Surah Quraysh with its meaning', {'surah'}), (98, 'Tarawih prayer – worship in Ramadan', {'ramadan', 'salah'}),
        (99, 'The importance and power of truth', {'akhlaq'}), (100, 'Cheating, lying and stealing', {'akhlaq'}), (102, 'Behaviour in society', {'akhlaq'}),
        (104, 'Alif-Lam-Mim with its meaning', {'surah'}), (105, 'The blessed nights', {'blessed-nights'}), (107, 'Kinds of nafl prayers', {'salah'}),
        (110, 'Famous scholars of Bosnia and Herzegovina', {'history'}), (113, 'My homeland – Bosnia and Herzegovina', {'history'}),
        (115, 'The Bosnian language', {'history'}), (117, 'Culture and tradition', {'history'}), (119, 'I am a Bosniak', {'history'}),
        (121, 'Laqad ja’akum (At-Tawbah 128–129) with its meaning', {'surah'}), (122, 'Review', {'review-2'}),
        (125, 'Overview table of the five daily prayers', {'five-prayers'}),
    ],
    3: [
        (8, 'Fulfilling our duties to Allah', {'iman', 'shahadah'}, 'ilmihal-3/01-duties-to-allah'), (11, 'Surah Al-Fil', {'surah'}),
        (12, 'Amantu billahi – belief in Allah (SWT)', {'iman', 'allah'}), (14, 'Tawhid – Allah is One', {'allah'}), (15, 'Belief in the unseen (ghayb)', {'iman'}),
        (17, 'Kufr, shirk and nifaq', {'iman'}), (20, 'Essential attributes: Wujud, Qidam and Baqa', {'sifat'}),
        (21, 'Essential attributes: Wahdaniyyah, Mukhalafatun lil-hawadith, Qiyamun bi-nafsihi', {'sifat'}),
        (22, 'Positive attributes: Hayat, ‘Ilm, Sam‘ and Basar', {'sifat'}), (23, 'Positive attributes: Iradah, Qudrah, Kalam and Takwin', {'sifat'}),
        (25, 'The beautiful names of Allah – Al-Asma’ al-Husna', {'allah', 'sifat'}), (27, 'Belief in Allah’s angels', {'angels'}),
        (29, 'Other unseen beings – jinn and shayatin', {'angels'}), (31, 'Belief in Allah’s books and scrolls', {'books'}),
        (33, 'The Qur’an – the final revelation', {'books', 'quran'}), (36, 'Belief in Allah’s messengers and their qualities', {'prophets'}),
        (38, 'The miracles of Allah’s messengers', {'prophets'}), (40, 'The Qur’an, Isra and Mi‘raj', {'seerah', 'blessed-nights'}),
        (42, 'Belief in the Last Day', {'iman'}), (44, 'Resurrection after death', {'iman'}), (46, 'Shafa‘ah, Mizan and the Sirat bridge', {'iman'}),
        (48, 'Jannah and Jahannam', {'iman'}), (50, 'Belief in Allah’s decree (qadar), good and bad', {'iman'}), (52, 'Surah Al-Humazah', {'surah'}),
        (53, 'Review', {'review-3'}), (55, 'The Shahadah', {'shahadah'}), (57, 'Salah – the five daily prayers', {'five-prayers', 'salah'}),
        (59, 'The fard parts of Salah', {'salah-steps', 'salah-conditions'}), (61, 'The wajib parts of Salah', {'salah-steps'}),
        (63, 'The sunnah acts of Salah', {'salah-steps'}), (64, 'What is disliked (makruh) in Salah', {'salah'}), (65, 'Surah Al-‘Asr', {'surah'}),
        (66, 'The meaning of praying in congregation', {'salah'}), (68, 'Kinds of Salah by importance', {'salah'}), (70, 'The funeral prayer (janazah)', {'salah'}),
        (72, 'The janazah du‘a', {'dua'}), (73, 'Fasting – the rules and virtues of Ramadan', {'fasting', 'ramadan'}),
        (76, 'Zakah – Baytul-mal', {'zakah'}), (78, 'Sadaqat al-fitr', {'zakah', 'ramadan', 'eid'}), (80, 'Hajj – its rules and virtues', {'hajj'}),
        (83, 'Surah At-Takathur', {'surah'}), (85, 'The best-known hadith collections', {'history'}), (86, 'The duties of adults (mukallaf)', {'akhlaq'}),
        (89, 'Ghusl – the ritual bath', {'ghusl'}), (91, 'Hayd, nifas and istihadah', {'ghusl'}), (92, 'Sahib al-‘udhr (a person with a lasting excuse)', {'wudu'}),
        (93, 'The role of the family', {'akhlaq'}), (95, 'Marriage in Islam', {'akhlaq'}), (98, 'Getting married', {'akhlaq'}),
        (100, 'The culture of dress – the meaning of hijab', {'akhlaq'}), (102, 'Surah Al-Qari‘ah', {'surah'}), (104, 'Review', {'review-3'}),
        (106, 'Responsibility for life and health', {'akhlaq'}), (108, 'Work and a work ethic', {'akhlaq'}), (110, 'Gaining knowledge', {'akhlaq'}),
        (112, 'Obedience and care for parents', {'akhlaq'}), (115, 'Keeping family ties', {'akhlaq'}), (117, 'Duties to neighbours', {'akhlaq'}),
        (119, 'Friendship', {'akhlaq'}), (121, 'Respect for elders', {'akhlaq'}), (123, 'Piety and God-consciousness (taqwa)', {'akhlaq'}),
        (125, 'Sincerity and justice', {'akhlaq'}), (126, 'Devotion and patience', {'akhlaq'}), (128, 'Truthfulness and trustworthiness', {'akhlaq'}),
        (129, 'Kindness and perseverance', {'akhlaq'}), (131, 'Mercy and forgiveness', {'akhlaq'}), (133, 'Stinginess and envy', {'akhlaq'}),
        (135, 'Backbiting', {'akhlaq'}), (136, 'Arrogance', {'akhlaq'}), (138, 'Hatred and jealousy', {'akhlaq'}), (140, 'Hostility', {'akhlaq'}),
        (141, 'Drugs – harm and consequences', {'akhlaq'}), (143, 'Alcohol', {'akhlaq'}), (145, 'Tobacco and its harm', {'akhlaq'}),
        (147, 'Immorality – protecting ourselves and its consequences', {'akhlaq'}), (149, 'Internet addiction', {'akhlaq'}),
        (151, 'Horoscopes and modern idolatry', {'iman'}), (153, 'Gambling, games of chance and sports betting', {'akhlaq'}),
        (155, 'Protecting the environment – ecology', {'nature'}), (157, 'How we treat plants and animals', {'nature'}), (159, 'Review', {'review-3'}),
        (161, 'Allah’s messengers mentioned in the Qur’an', {'prophets'}), (163, 'Prophet Nuh (AS)', {'prophets'}), (165, 'Prophet Ibrahim (AS)', {'prophets'}),
        (168, 'Prophet Musa (AS)', {'prophets'}), (171, 'Prophet Isa (AS)', {'prophets'}), (173, 'The childhood of Muhammad (SAW)', {'seerah'}),
        (176, 'The family of Prophet Muhammad (SAW)', {'seerah'}), (178, 'The Hijrah – from Makkah to Madinah', {'seerah', 'calendar'}),
        (182, 'The Battle of Badr', {'seerah'}), (184, 'The Farewell Hajj', {'seerah', 'hajj'}), (186, 'The passing of the Messenger (SAW)', {'seerah'}),
        (188, 'Qul id‘ullaha (Al-Isra 110–111)', {'surah'}), (189, 'Beautiful Muslim names', {'akhlaq'}), (191, 'A good word', {'akhlaq'}),
        (192, 'The Islamic Community – its history', {'history'}), (196, 'The Day of Mosques and Jama‘ats', {'history'}),
        (198, 'The rights and duties of jama‘at members', {'history'}), (199, 'Maktab, mosque and school – foundations of education', {'history'}),
        (201, 'Educational institutions of the Islamic Community', {'history'}), (203, 'The rightly guided caliphs: Abu Bakr, ‘Umar, ‘Uthman and ‘Ali (RA)', {'seerah'}),
        (205, 'Chosen women mentioned in the Qur’an and hadith', {'seerah'}), (206, 'Famous waqfs and waqf buildings in Bosnia and Herzegovina', {'history'}),
        (209, 'Bosniak poets and writers', {'history'}), (210, 'Review', {'review-3'}),
    ],
}
